import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {requireTreasurer} from '@/lib/persis/master-server';
import {loadProgramReport} from '@/lib/persis/program-server';
import {PROGRAM_BASE,PROGRAM_STATUS,type ProgramExpense} from '@/lib/persis/program';
import {UUID} from '@/lib/persis/cash';
import {rupiah} from '@/lib/persis/dues';
import TreasuryNav from '../../TreasuryNav';
import ProgramForm from '../ProgramForm';
import DocumentForm from '../DocumentForm';
import AssignmentForm from '../AssignmentForm';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Detail Program PW Persis Kepri',robots:{index:false,follow:false}};
export default async function ProgramDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string;success?:string;page?:string;docs?:string}>}){
 const {id}=await params,{client}=await requireTreasurer(`${PROGRAM_BASE}/${id}`);if(!UUID.test(id))notFound();
 const {data:record,error:readError}=await client.from('persis_programs').select('year').eq('id',id).maybeSingle();if(readError)throw new Error('Program belum dapat dimuat.');if(!record)notFound();
 const report=await loadProgramReport(client,record.year),program=report.programs.find(p=>p.id===id);if(!program)notFound();
 const query=await searchParams,page=Math.max(1,Math.min(10000,parseInt(query.page||'1')||1)),docsPage=Math.max(1,Math.min(10000,parseInt(query.docs||'1')||1));
 const [expenses,documents,audit]=await Promise.all([
  client.from('persis_program_allocations').select('cash_entry_id,entry:persis_cash_entries(id,transacted_on,party,description,amount,voided_at,void_reason)',{count:'exact'}).eq('program_id',id).order('cash_entry_id').range((page-1)*20,page*20),
  client.from('persis_program_documents').select('id,caption,file_name,created_at',{count:'exact'}).eq('program_id',id).order('created_at',{ascending:false}).order('id').range((docsPage-1)*20,docsPage*20),
  client.from('persis_program_audit').select('before_data,after_data,created_at').eq('entity','persis_programs').eq('entity_id',id).order('id',{ascending:false}).limit(20)
 ]);
 const rows=(expenses.data||[]).slice(0,20).map(a=>a.entry as unknown as ProgramExpense).filter(Boolean);
 return <div lang="id" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><main className="mx-auto max-w-5xl"><Link href={`${PROGRAM_BASE}?year=${program.year}`} className="text-sm font-semibold text-emerald-800 underline">Kembali ke program {program.year}</Link><p className="mt-6 text-sm font-bold uppercase tracking-widest text-emerald-800">PW Persis Kepri · {program.division}</p><h1 className="mt-2 text-3xl font-bold">{program.title}</h1><p className="mt-3 text-slate-600">Penanggung jawab: {program.responsible} · {program.start_date} — {program.end_date}</p><TreasuryNav/>
  {query.error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{query.error}</p>}{query.success&&<p role="status" className="mb-5 rounded-xl bg-emerald-100 p-4 text-emerald-950">Perubahan berhasil disimpan.</p>}
  <div className="grid gap-3 sm:grid-cols-3">{[['Anggaran',program.budget],['Realisasi aktif',program.spent],['Sisa anggaran',program.budget-program.spent]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">{label}</p><p className={`mt-2 text-2xl font-bold ${Number(value)<0?'text-red-700':'text-emerald-900'}`}>{rupiah(Number(value))}</p></div>)}</div>
  {program.spent>program.budget&&<p role="alert" className="mt-4 rounded-lg bg-amber-50 p-4 text-amber-900">Realisasi melebihi anggaran sebesar {rupiah(program.spent-program.budget)}. Periksa belanja dan dasar revisi anggaran.</p>}
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Perkembangan kegiatan</h2><p className="mt-3 font-semibold text-emerald-900">{PROGRAM_STATUS[program.status]} · progres {program.progress}%</p><progress value={program.progress} max={100} aria-label="Progres kegiatan" className="mt-3 h-3 w-full accent-emerald-700"/><h3 className="mt-5 font-bold">Target</h3><p className="mt-2 whitespace-pre-wrap leading-7">{program.target}</p><h3 className="mt-5 font-bold">Rencana sumber dana</h3><p className="mt-2 whitespace-pre-wrap leading-7">{program.funding_source}</p><h3 className="mt-5 font-bold">Laporan perkembangan / hasil</h3><p className="mt-2 whitespace-pre-wrap leading-7">{program.report||'Belum ada laporan perkembangan.'}</p><p className="mt-4 text-sm text-slate-500">Progres kegiatan diperbarui oleh bendahara; realisasi biaya dihitung otomatis dari {program.expense_count} pengeluaran aktif.</p></section>
  <details className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><summary className="cursor-pointer text-xl font-bold">Ubah program, anggaran, atau progres</summary><ProgramForm program={program} year={program.year}/></details>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Pengeluaran terkait ({expenses.count||0})</h2><Link href="/persis-kepri/iuran/bendahara/kas" className="text-sm font-semibold text-emerald-800 underline">Catat pengeluaran di buku kas</Link></div><p className="mt-2 text-sm text-slate-600">Pembatalan transaksi dilakukan di buku kas. Koreksi tautan tidak mengubah nominal atau bukti.</p>
   {expenses.error?<p className="mt-4 text-red-800">Pengeluaran belum dapat dimuat.</p>:!rows.length?<p className="mt-4 text-slate-600">Belum ada pengeluaran pada halaman ini.</p>:<div className="mt-5 grid gap-4 md:grid-cols-2">{rows.map(r=><article key={r.id} className="rounded-xl border border-slate-200 p-4"><p className="text-sm text-slate-500">{r.transacted_on} · KAS-{r.id.slice(0,8)}</p><p className="mt-2 font-bold">{r.party} · {rupiah(r.amount)}</p><p className="mt-2 whitespace-pre-wrap text-sm">{r.description}</p>{r.voided_at&&<p className="mt-2 text-sm text-red-700">Dibatalkan, tidak dihitung: {r.void_reason}</p>}<a href={`/api/persis/cash/${r.id}/receipt`} className="mt-2 inline-block text-sm text-emerald-800 underline">Unduh bukti</a>{!r.voided_at&&<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-emerald-900">Koreksi tautan program</summary><AssignmentForm entryId={r.id} programs={report.programs} year={program.year} currentId={id} returnId={id}/></details>}</article>)}</div>}
   <div className="mt-4 flex gap-5 text-sm">{page>1&&<Link className="underline" href={`${PROGRAM_BASE}/${id}?page=${page-1}&docs=${docsPage}`}>Pengeluaran sebelumnya</Link>}{(expenses.data?.length||0)>20&&<Link className="underline" href={`${PROGRAM_BASE}/${id}?page=${page+1}&docs=${docsPage}`}>Pengeluaran berikutnya</Link>}</div>
  </section>
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Dokumentasi kegiatan ({documents.count||0})</h2>{documents.error?<p className="mt-4 text-red-800">Dokumen belum dapat dimuat.</p>:<ul className="mt-4 space-y-3">{documents.data?.slice(0,20).map(d=><li key={d.id} className="rounded-lg bg-slate-50 p-4"><a href={`/api/persis/program/documents/${d.id}`} className="break-words font-semibold text-emerald-800 underline">{d.caption}</a><p className="mt-1 break-words text-xs text-slate-500">{d.file_name} · {new Date(d.created_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p></li>)}</ul>}<div className="mt-4 flex gap-5 text-sm">{docsPage>1&&<Link className="underline" href={`${PROGRAM_BASE}/${id}?page=${page}&docs=${docsPage-1}`}>Dokumen sebelumnya</Link>}{(documents.data?.length||0)>20&&<Link className="underline" href={`${PROGRAM_BASE}/${id}?page=${page}&docs=${docsPage+1}`}>Dokumen berikutnya</Link>}</div><DocumentForm programId={id}/></section>
  <details className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><summary className="cursor-pointer font-bold">Riwayat perubahan program (20 terakhir)</summary>{audit.error?<p className="mt-4 text-red-800">Riwayat belum dapat dimuat.</p>:<ul className="mt-4 space-y-4">{audit.data?.map((a,i)=><li key={i} className="border-b border-slate-100 pb-4 text-sm"><p className="text-slate-500">{new Date(a.created_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB</p><p className="mt-1">Anggaran: {a.before_data?`${rupiah(Number(a.before_data.budget))} → `:''}{rupiah(Number(a.after_data.budget))} · progres {a.after_data.progress}%</p><p className="mt-1 font-semibold">{a.after_data.change_reason}</p>{a.after_data.report&&<p className="mt-1 whitespace-pre-wrap">{a.after_data.report}</p>}</li>)}</ul>}</details>
 </main></div>;
}
