"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-3-v1";
const SOURCE_URL = "https://ms.wikisource.org/wiki/Bustan_al-Katibin";

const nav = [
  ["introduction", "Pengantar"], ["reading", "Bacaan utama"], ["analysis", "Kerangka bahasa"],
  ["podcast", "Podcast"], ["reflection", "Refleksi"], ["essay", "Esai"], ["quiz", "Kuis"], ["result", "Hasil"],
];

const readings = [
  {
    n: "I",
    title: "Sebuah kebun bagi para penulis",
    text: <><p>Judul lengkap kitab ini ialah <em>Bustan al-Katibin li al-Sibyan al-Muta’allimin</em>, yang dapat dipahami sebagai “kebun para penulis bagi anak-anak yang hendak belajar”. Kata <em>bustan</em> atau kebun memberi gambaran bahwa kemampuan menulis harus ditanam, dirawat, dan ditumbuhkan.</p><p>Kitab ini diselesaikan Raja Ali Haji di Pulau Penyengat pada pertengahan abad ke-19. Susunannya terdiri atas mukadimah, tiga puluh satu fasal, dan khatimah. Pembahasannya bergerak dari keutamaan ilmu dan akal menuju huruf, ejaan, kelas kata, susunan kalimat, dan latihan menulis.</p></>,
    idea: "Bahasa dipelajari sebagai ilmu yang ditumbuhkan melalui latihan, bukan kemampuan yang muncul dengan sendirinya.",
  },
  {
    n: "II",
    title: "Ilmu dan akal sebagai pintu masuk",
    text: <><p>Raja Ali Haji tidak langsung membuka kitab dengan daftar aturan tata bahasa. Ia terlebih dahulu membicarakan keutamaan ilmu dan akal. Dalam mukadimah terdapat peringatan bahwa tanpa ilmu dan akal seseorang tidak akan mencapai kemuliaan dan mudah didekati kehinaan.</p><blockquote>“Apabila tiada ilmu dan akal, alamat tiadalah ia mencium bau kemuliaan.”</blockquote><p>Urutan ini penting: aturan bahasa ditempatkan dalam tujuan intelektual dan moral. Bahasa menjadi jalan untuk memperoleh, menata, menguji, dan menyampaikan pengetahuan.</p></>,
    idea: "Ketertiban bahasa berhubungan dengan ketertiban berpikir karena ilmu memerlukan istilah, hubungan antargagasan, dan penyampaian yang dapat dipahami.",
  },
  {
    n: "III",
    title: "Adab sebelum belajar",
    text: <><p>Pembelajar tidak cukup hanya mendengar sedikit lalu merasa telah menguasai seluruh persoalan. Raja Ali Haji mengkritik sikap tergesa-gesa, kesembronoan menulis, dan kebiasaan menambah atau mengurangi huruf tanpa pengetahuan.</p><p>Karena itu, kesiapan belajar memerlukan kerendahan hati, kesabaran, ketekunan, guru, dan kesediaan memeriksa kesalahan. Adab bukan hiasan di luar ilmu; adab menentukan apakah pengetahuan benar-benar dapat diperoleh.</p></>,
    idea: "Orang yang tertib belajar bersedia membedakan pengetahuan yang sudah dipahami dari pendapat yang baru didengar.",
  },
  {
    n: "IV",
    title: "Huruf, ejaan, dan ketelitian",
    text: <><p>Bagian awal pengajaran teknis memberi perhatian pada huruf dan cara merangkainya. Dalam tradisi Jawi, bentuk, titik, posisi, dan sambungan huruf menentukan bunyi serta makna. Kesalahan kecil dapat mengubah kata atau membuat tulisan sulit dipahami.</p><p>Ketelitian ejaan mengajarkan disiplin intelektual: penulis bertanggung jawab agar pembaca menerima maksud yang benar. Pada masa digital, prinsip ini tetap berlaku dalam penulisan nama, istilah hukum, kutipan, data, dan sumber.</p></>,
    idea: "Ketepatan bentuk tulisan adalah bagian dari amanah menyampaikan makna.",
  },
  {
    n: "V",
    title: "Kata dan susunan pikiran",
    text: <><p><em>Bustan al-Katibin</em> memakai perangkat tata bahasa Arab untuk menerangkan bahasa Melayu. Kata dibahas melalui kategori seperti <em>isim</em>, <em>fi‘il</em>, dan <em>harf</em>; susunan kalimat diterangkan melalui hubungan bagian-bagiannya.</p><p>Kerangka tersebut memperlihatkan usaha sistematis Raja Ali Haji: ujaran tidak dipandang sebagai tumpukan kata, tetapi sebagai struktur. Seseorang perlu mengetahui fungsi sebuah kata dan hubungannya dengan kata lain agar maksudnya lengkap.</p></>,
    idea: "Tata bahasa adalah peta hubungan: siapa atau apa yang dibicarakan, tindakan atau keadaan apa yang dinyatakan, dan bagaimana unsur-unsurnya terhubung.",
  },
  {
    n: "VI",
    title: "Bahasa, adab, dan ruang publik",
    text: <><p>Bahasa yang tertib tidak otomatis menjadikan seseorang bermoral, tetapi kehidupan moral dan sosial sulit dipelihara tanpa bahasa yang dapat dipercaya. Janji, hukum, pengajaran, nasihat, surat resmi, dan keputusan pemerintahan semuanya bergantung pada ketepatan kata.</p><p>Di media sosial, persoalan yang sama muncul dalam bentuk baru: judul menyesatkan, kabar tanpa pemeriksaan, kutipan terpotong, serangan pribadi, dan istilah yang sengaja dikaburkan. Membaca Raja Ali Haji hari ini berarti memulihkan hubungan antara kecakapan berbahasa, kerendahan hati intelektual, dan tanggung jawab publik.</p></>,
    idea: "Menertibkan bahasa bukan sekadar memperbaiki kalimat; ia membantu membangun percakapan publik yang jernih dan dapat dipertanggungjawabkan.",
  },
];

const questions = [
  { q: "Arti metaforis kata bustan dalam judul kitab adalah…", o: ["Gudang senjata", "Kebun tempat kemampuan menulis ditumbuhkan", "Istana pemerintahan", "Catatan perjalanan"], a: 1 },
  { q: "Mengapa kitab tidak langsung dimulai dengan aturan tata bahasa?", o: ["Tata bahasa dianggap tidak penting", "Ilmu bahasa didahului pembahasan tujuan ilmu, akal, dan adab belajar", "Penulis lupa menyusunnya", "Kitab hanya berisi puisi"], a: 1 },
  { q: "Hubungan bahasa dan akal dalam modul ini adalah…", o: ["Bahasa menggantikan akal", "Bahasa membantu menata dan menyampaikan pengetahuan", "Akal tidak membutuhkan bahasa", "Bahasa hanya untuk hiburan"], a: 1 },
  { q: "Sikap pembelajar yang dikritik Raja Ali Haji adalah…", o: ["Rajin memeriksa tulisan", "Mendengar sedikit lalu merasa paling mengetahui", "Belajar kepada guru", "Memperbaiki kesalahan"], a: 1 },
  { q: "Mengapa titik dan sambungan huruf penting dalam tulisan Jawi?", o: ["Hanya sebagai hiasan", "Dapat menentukan bunyi dan makna", "Agar tulisan lebih panjang", "Tidak memiliki fungsi"], a: 1 },
  { q: "Kategori isim, fi‘il, dan harf menunjukkan pengaruh tradisi…", o: ["Tata bahasa Arab", "Matematika Yunani", "Hukum Belanda", "Sastra Tiongkok"], a: 0 },
  { q: "Tata bahasa disebut sebagai peta hubungan karena…", o: ["Kata berdiri sendiri", "Ia menjelaskan fungsi kata dan hubungan antarbagiannya", "Semua kalimat harus sama", "Makna tidak diperlukan"], a: 1 },
  { q: "Ketelitian menulis merupakan amanah karena…", o: ["Penulis bertanggung jawab menyampaikan maksud secara benar", "Tulisan harus selalu panjang", "Pembaca tidak boleh menafsirkan", "Kesalahan tidak berpengaruh"], a: 0 },
  { q: "Contoh penerapan prinsip Bustan al-Katibin di ruang digital adalah…", o: ["Menyebarkan kabar sebelum memeriksa", "Memotong kutipan", "Memeriksa istilah, sumber, dan konteks sebelum memublikasikan", "Mengutamakan serangan pribadi"], a: 2 },
  { q: "Gagasan utama Modul 3 adalah…", o: ["Bahasa hanya masalah ejaan", "Ketertiban bahasa menghubungkan ilmu, akal, adab, dan tanggung jawab publik", "Tata bahasa tidak relevan sekarang", "Semua tradisi bahasa sama"], a: 1 },
];

export default function ModuleThreeLearning() {
  const [active, setActive] = useState("introduction");
  const [reflection, setReflection] = useState("");
  const [essay, setEssay] = useState("");
  const [answers, setAnswers] = useState<AnswerMap>({});
  const [score, setScore] = useState<number | null>(null);
  const [readingDone, setReadingDone] = useState(false);
  const [analysisDone, setAnalysisDone] = useState(false);
  const [podcastDone, setPodcastDone] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const d = JSON.parse(raw); setReflection(d.reflection ?? ""); setEssay(d.essay ?? ""); setAnswers(d.answers ?? {}); setScore(d.score ?? null); setReadingDone(Boolean(d.readingDone)); setAnalysisDone(Boolean(d.analysisDone)); setPodcastDone(Boolean(d.podcastDone)); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; const id = window.setTimeout(() => { void saveModuleProgress(STORAGE_KEY, 3, { reflection, essay, answers, score, readingDone, analysisDone, podcastDone }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200); }); }, 500); return () => window.clearTimeout(id); }, [reflection, essay, answers, score, readingDone, analysisDone, podcastDone, hydrated]);

  const reflectionWords = useMemo(() => countWords(reflection), [reflection]);
  const essayWords = useMemo(() => countWords(essay), [essay]);
  const reflectionDone = reflectionWords >= 100;
  const essayDone = essayWords >= 500;
  const quizDone = score !== null && score >= 70;
  const done = [readingDone, analysisDone, podcastDone, reflectionDone, essayDone, quizDone];
  const progress = Math.round(done.filter(Boolean).length / 6 * 100);
  const complete = done.every(Boolean);

  function submit() { if (Object.keys(answers).length < questions.length) { alert("Jawab seluruh pertanyaan terlebih dahulu."); return; } setScore(questions.filter((q, i) => Number(answers[i]) === q.a).length * 10); setActive("result"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <main className="min-h-screen bg-[#f7f4ee] text-slate-950">
    <header className="border-b border-white/10 bg-[#070916] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-400"><ArrowLeft size={17}/> Kembali ke program</Link><div className="min-w-56"><div className="flex justify-between text-xs"><span>Progres Modul 3</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${progress}%` }}/></div></div></div></header>
    <section className="bg-[#070916] px-5 pb-14 pt-10 text-white sm:px-8 md:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 3 dari 8</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Bahasa, Adab, dan Tata Pikiran</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Membaca <em>Bustan al-Katibin</em> sebagai usaha menertibkan tulisan, membentuk akal, dan menjaga tanggung jawab dalam komunikasi.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 120–150 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Tingkat dasar</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai, dan kuis</span></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id, label], i) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active === id ? "bg-slate-950 text-white" : "hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i + 1).padStart(2, "0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved ? "Tersimpan otomatis ✓" : "Progres tersimpan di perangkat ini"}</div></aside>
      <div className="min-w-0">
        {active === "introduction" && <Panel eyebrow="Mulai di sini" title="Pengantar Modul 3"><p>Setelah Modul 2 membahas karakter melalui <em>Gurindam Dua Belas</em>, Modul 3 beralih kepada alat yang memungkinkan ilmu dan adab disampaikan: bahasa. Bagi Raja Ali Haji, kecakapan berbahasa bukan hanya keterampilan teknis, melainkan bagian dari pembentukan manusia berakal.</p><h3>Tujuan pembelajaran</h3><ol><li>Menjelaskan kedudukan <em>Bustan al-Katibin</em> dalam tradisi bahasa Melayu.</li><li>Menguraikan hubungan ilmu, akal, bahasa, dan adab belajar.</li><li>Menjelaskan pentingnya huruf, ejaan, kata, dan susunan kalimat.</li><li>Menerapkan etika kebahasaan dalam komunikasi kontemporer.</li></ol><blockquote>Jika pikiran disampaikan melalui bahasa, apakah bahasa yang ceroboh juga dapat menghasilkan pengetahuan dan keputusan yang ceroboh?</blockquote><Next onClick={() => setActive("reading")}>Mulai membaca</Next></Panel>}
        {active === "reading" && <Panel eyebrow="Bacaan utama • 30–40 menit" title="Menertibkan bahasa, menumbuhkan akal"><p>Bacaan pembelajaran berikut menyajikan alur pemikiran kitab secara utuh untuk tingkat dasar. Kutipan mempertahankan corak Melayu klasik, sedangkan uraian menggunakan bahasa Indonesia kontemporer.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Baca naskah sumber</p><p className="mt-2 text-sm leading-6 text-slate-600">Edisi Jawi domain publik tersedia melalui Wikisource. Gunakan untuk melihat bentuk asli dan susunan lengkap kitab.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka Bustan al-Katibin <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e => setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 3.</label><Next onClick={() => setActive("analysis")}>Lanjut ke kerangka bahasa</Next></Panel>}
        {active === "analysis" && <Panel eyebrow="Analisis konseptual" title="Bahasa sebagai arsitektur pengetahuan"><div className="grid gap-4 md:grid-cols-3"><Concept n="01" title="Tanda" text="Huruf dan ejaan menjaga agar bentuk tulisan membawa bunyi serta makna secara tepat."/><Concept n="02" title="Susunan" text="Kata memperoleh fungsi melalui hubungan dengan kata lain di dalam kalimat."/><Concept n="03" title="Tanggung jawab" text="Penulis wajib menjaga kebenaran, konteks, dan akibat dari bahasa yang digunakan."/></div><h3>Dari tanda menuju makna</h3><p>Huruf bukan sekadar gambar. Ketepatan titik, bentuk, dan rangkaiannya menentukan kata. Kata kemudian ditempatkan dalam susunan agar membentuk maksud yang lengkap.</p><h3>Dari tata bahasa menuju tata pikiran</h3><p>Kalimat yang tertib memaksa penulis menjelaskan subjek pembicaraan, tindakan atau keadaan, hubungan sebab, batas pernyataan, dan kesimpulan. Tata bahasa dengan demikian melatih penalaran, meskipun ketepatan gramatikal tetap harus disertai kebenaran isi.</p><h3>Dari pengetahuan menuju adab</h3><p>Orang berilmu mengetahui batas pengetahuannya, memeriksa tulisan, dan tidak tergesa-gesa mengaku paling benar. Bahasa menjadi beradab ketika digunakan untuk menjernihkan persoalan, bukan menutupi kesalahan atau merendahkan orang lain.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e => setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami hubungan tanda, susunan, pikiran, dan tanggung jawab.</label><Next onClick={() => setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
        {active === "podcast" && <Panel eyebrow="Podcast • 26 menit" title="Menertibkan Bahasa, Menertibkan Pikiran"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Adab Menulis Raja Ali Haji: Lawan Hoaks</p><p className="mt-1 text-sm text-slate-400">Audio Overview • Bahasa Indonesia • 25:39</p></div></div><audio className="mt-7 w-full" controls preload="metadata" onEnded={() => setPodcastDone(true)}><source src="/audio/adab-menulis-raja-ali-haji-lawan-hoaks.m4a" type="audio/mp4"/>Peramban Anda tidak mendukung pemutar audio.</audio></div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan podcast</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p>Podcast ini membaca <em>Bustan al-Katibin</em> sebagai pendidikan bahasa, akal, dan adab. Raja Ali Haji memulai pembahasannya dari ilmu dan akal sebelum masuk kepada huruf, ejaan, pembagian kata, serta susunan kalimat.</p><p>Ketelitian menulis dipahami sebagai amanah menjaga makna. Pembelajar harus rendah hati, memeriksa kesalahan, memahami batas pengetahuan, dan tidak tergesa-gesa menyampaikan kabar yang belum dipastikan.</p><p>Dalam ruang digital, prinsip tersebut menjadi pertahanan terhadap hoaks: memeriksa istilah, sumber, konteks, perbedaan fakta dan penilaian, serta akibat sebuah pesan sebelum memublikasikannya. Kelancaran bahasa—termasuk tulisan yang dihasilkan AI—tidak otomatis membuktikan kebenaran isinya.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e => setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mendengarkan podcast ini sampai selesai.</label><Next disabled={!podcastDone} onClick={() => setActive("reflection")}>Lanjut ke refleksi</Next></Panel>}
        {active === "reflection" && <Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi bahasa dan tanggung jawab"><p>Ingat satu pengalaman ketika kata, ejaan, kutipan, atau informasi yang tidak tepat menimbulkan salah paham. Jelaskan apa yang seharusnya diperiksa sebelum pesan tersebut disampaikan.</p><textarea value={reflection} onChange={e => setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={() => setActive("essay")}>Simpan dan lanjut ke esai</Next></Panel>}
        {active === "essay" && <Panel eyebrow="Penilaian • 500–700 kata" title="Tugas esai Modul 3"><blockquote>Jelaskan mengapa tata bahasa dalam <em>Bustan al-Katibin</em> dapat dibaca sebagai pendidikan akal dan adab, bukan hanya aturan menulis.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan sedikitnya tiga bagian bacaan Modul 3.</li><li>Jelaskan hubungan ilmu, akal, bahasa, dan adab.</li><li>Bedakan ketepatan bentuk bahasa dari kebenaran isi.</li><li>Berikan satu contoh dari komunikasi digital atau kehidupan publik.</li></ul><textarea value={essay} onChange={e => setEssay(e.target.value)} rows={22} placeholder="Mulai menulis esai…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={500} max={700}/><Next disabled={!essayDone} onClick={() => setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
        {active === "quiz" && <Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 3"><div className="space-y-8">{questions.map((q, i) => <fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i + 1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o, j) => <label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i]) === j ? "border-amber-600 bg-amber-50" : "border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q3-${i}`} checked={Number(answers[i]) === j} value={j} onChange={e => setAnswers({ ...answers, [i]: e.target.value })} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
        {active === "result" && <Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 3"><div className={`border p-7 ${complete ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score ?? 0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone ? "Kuis lulus." : "Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan utama selesai"/><Req done={analysisDone} text="Kerangka bahasa selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai minimal 500 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete ? <div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 3 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menyelesaikan pembelajaran bahasa, adab, dan tata pikiran dalam <em>Bustan al-Katibin</em>.</p><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji/module-4" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 font-bold text-emerald-800 transition hover:bg-emerald-50">Lanjut ke Modul 4 <ArrowRight size={18}/></Link></div> : <button onClick={() => { setAnswers({}); setScore(null); setActive("quiz"); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
      </div>
    </div>
  </main>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>; }
function Next({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>; }
function Words({ count, min, max }: { count: number; min: number; max: number }) { return <p className={`text-sm font-semibold ${count >= min ? "text-emerald-700" : "text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count >= min ? "✓" : ""}</p>; }
function Req({ done, text }: { done: boolean; text: string }) { return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done ? "text-emerald-600" : "text-stone-300"} size={21}/><span className={done ? "font-semibold" : "text-slate-500"}>{text}</span></div>; }
function Concept({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+/).length : 0; }
function ReadingAccordion() { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section, i) => <article key={section.n}><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open === i ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>{open === i && <div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>}</article>)}</div>; }
