-- LexNusa production lead store.
-- Run once in the Supabase SQL editor for the project used by hossibarani.com.

create table if not exists public.lexnusa_pilot_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 120),
  organization text,
  email text not null check (char_length(email) <= 254),
  project_type text not null,
  message text not null check (char_length(message) between 1 and 6000),
  source text not null default 'lexnusa-landing',
  status text not null default 'new' check (status in ('new','contacted','qualified','won','lost','spam')),
  notes text
);

create index if not exists lexnusa_pilot_leads_created_at_idx
  on public.lexnusa_pilot_leads (created_at desc);
create index if not exists lexnusa_pilot_leads_status_idx
  on public.lexnusa_pilot_leads (status);

alter table public.lexnusa_pilot_leads enable row level security;

-- Intentionally create NO anon/authenticated policies.
-- Browser clients therefore cannot read or write the table.
-- The Next.js server action writes with SUPABASE_SERVICE_ROLE_KEY, which must
-- exist only as a server-side Vercel environment variable and never use NEXT_PUBLIC_.

revoke all on table public.lexnusa_pilot_leads from anon, authenticated;
