-- LexNusa CRM v1.3 — Client Conversion & Proposal Operations
-- Stage 1: proposal data model. Apply to a Supabase development branch first.

create sequence if not exists public.lexnusa_proposal_number_seq start 1;

create table if not exists public.lexnusa_proposals (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  lead_id bigint not null references public.lexnusa_pilot_leads(id) on delete cascade,
  proposal_no text not null unique,
  title text not null check (char_length(title) between 1 and 240),
  scope text not null check (char_length(scope) between 1 and 12000),
  deliverables text not null check (char_length(deliverables) between 1 and 12000),
  timeline text not null check (char_length(timeline) between 1 and 4000),
  fee numeric(16,2) not null check (fee >= 0),
  currency text not null default 'USD' check (currency in ('USD','IDR','SGD','MYR')),
  valid_until date,
  terms text,
  status text not null default 'draft' check (status in ('draft','sent','under_review','negotiation','accepted','rejected','expired')),
  created_by uuid references auth.users(id) on delete set null,
  sent_at timestamptz,
  accepted_at timestamptz,
  rejected_at timestamptz,
  lost_reason text
);

create index if not exists lexnusa_proposals_lead_id_idx on public.lexnusa_proposals(lead_id);
create index if not exists lexnusa_proposals_status_idx on public.lexnusa_proposals(status);
create index if not exists lexnusa_proposals_created_at_idx on public.lexnusa_proposals(created_at desc);

alter table public.lexnusa_proposals enable row level security;
revoke all on table public.lexnusa_proposals from anon, authenticated;
grant select, insert, update, delete on table public.lexnusa_proposals to service_role;
grant usage, select on sequence public.lexnusa_proposal_number_seq to service_role;

create or replace function public.lexnusa_next_proposal_no()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  seq_value bigint;
begin
  seq_value := nextval('public.lexnusa_proposal_number_seq');
  return 'LEX-P-' || to_char(now() at time zone 'Asia/Jakarta', 'YYYY') || '-' || lpad(seq_value::text, 3, '0');
end;
$$;

revoke all on function public.lexnusa_next_proposal_no() from public, anon, authenticated;
grant execute on function public.lexnusa_next_proposal_no() to service_role;

-- Extend CRM audit vocabulary for proposal operations while preserving existing activity types.
alter table public.lexnusa_lead_activities
  drop constraint if exists lexnusa_lead_activities_activity_type_check;

alter table public.lexnusa_lead_activities
  add constraint lexnusa_lead_activities_activity_type_check
  check (activity_type in (
    'created','status_changed','note_updated','follow_up_changed','value_changed','owner_changed',
    'email_opened','email_prepared','email_sent','email_sent_manual','email_failed','manual_note',
    'proposal_created','proposal_updated','proposal_sent','proposal_status_changed','proposal_accepted','proposal_rejected'
  ));
