export const coursePath = "/lexnusa/mayantara";
export const roomPath = coursePath + "/workspace";
export const sources = [
 ["UU ITE · UU 11/2008", "https://peraturan.bpk.go.id/Details/37589/uu-no-11-tahun-2008"],
 ["First amendment · UU 19/2016", "https://peraturan.bpk.go.id/Details/37582/uu-no-19-tahun-2016"],
 ["Second amendment · UU 1/2024", "https://peraturan.bpk.go.id/Details/274494/uu-no-1-tahun-2024"],
 ["Personal Data Protection · UU 27/2022", "https://peraturan.bpk.go.id/Details/229798/uu-no-27-tahun-2022"],
 ["Electronic Systems and Transactions · PP 71/2019", "https://peraturan.bpk.go.id/Details/122030/pp-no-71-tahun-2019"],
 ["Electronic Commerce · PP 80/2019", "https://peraturan.bpk.go.id/Details/126143/pp-no-80-tahun-2019"],
 ["Criminal Code · UU 1/2023", "https://peraturan.bpk.go.id/Details/234935/uu-no-1-tahun-2023"],
 ["Criminal-law adjustments · UU 1/2026", "https://peraturan.bpk.go.id/Details/337869/uu-no-1-tahun-2026"],
] as const;
export const units = [
 {n:1,meetings:"1–2",title:"Mapping the digital legal problem",outcome:"Separate facts, legal issues, actors, jurisdiction and uncertainty.",note:"Begin with what happened, when it happened, and who controlled each action. A platform, seller, user and hosting provider are not interchangeable. Make a timeline before naming a legal rule. Distinguish a contractual dispute from a data incident or possible offence; one incident can raise several questions.",activity:"Draw a four-column map: event, actor, evidence, unresolved question. Explain why an allegation is not yet a proven fact.",reading:[0,1,2]},
 {n:2,meetings:"3–4",title:"Electronic agreements and consumer disputes",outcome:"Evaluate how online terms are presented, accepted and evidenced.",note:"Reconstruct the transaction from advertisement to checkout, payment and performance. Preserve the terms that applied at the relevant time. Ask what the parties agreed, what information was available, and which remedies could address the alleged failure. A screenshot of today's terms does not prove yesterday's agreement.",activity:"Compare two versions of fictional checkout terms. Identify missing information and propose a clearer clause without assuming enforceability.",reading:[0,2,4,5]},
 {n:3,meetings:"5–6",title:"Personal data and responsible processing",outcome:"Map a data flow and assess the roles, purposes and potential legal bases involved.",note:"Trace collection, use, disclosure, retention and deletion separately. Identify what data is necessary for each purpose. Do not treat a single consent checkbox as the answer to every processing question. Distinguish what the scenario proves from what you need to ask a controller, processor or affected person.",activity:"Build a data inventory for a fictional campus app. Record purpose, actor, recipient, retention and an unanswered compliance question for each field.",reading:[3,4]},
 {n:4,meetings:"7–8",title:"Mid-semester legal memorandum",outcome:"Develop a source-backed argument and respond to a competing interpretation.",note:"A useful memorandum connects a precise question to an applicable rule and evidence. Present the strongest alternative argument, not a straw man. Cite the exact provision and version checked. Conclusions should state their factual conditions and explain what new evidence could change them.",activity:"Submit the privacy memorandum, then conduct a short oral defence using the published rubric. Meeting numbers are a proposed sequence, not an official exam schedule.",reading:[2,3,4]},
 {n:5,meetings:"9–10",title:"Digital evidence and incident response",outcome:"Document provenance, integrity, uncertainty and lawful handling of electronic material.",note:"Separate the information a file contains from the process used to collect it. Record who obtained an item, from where, when, and how it was stored. A hash may help track a file's integrity but does not by itself prove that the content is true or that collection was lawful. Use only simulated evidence in this classroom.",activity:"Prepare an evidence register and a chronological incident note. Do not access accounts, devices or systems without authorization.",reading:[0,2,4]},
 {n:6,meetings:"11–12",title:"Online speech, platforms and accountability",outcome:"Distinguish speech, alleged harm, platform action and possible legal consequences.",note:"Start with the full context of a disputed post, including its date and audience. Separate platform policy from state law and civil remedies from criminal questions. Verify the applicable statutory text and relevant judicial interpretation before assigning liability. Avoid treating criticism, false information and personal-data disclosure as identical issues.",activity:"Debate a fictional moderation decision from the user, platform and affected person's perspectives. Check the current criminal-law framework and transitional provisions.",reading:[0,2,6,7]},
 {n:7,meetings:"13–14",title:"AI outputs, authorship and professional judgment",outcome:"Audit an unsupported legal answer and document responsible use of external tools.",note:"AI output is a claim to be evaluated, not an authority. Check whether each cited source exists, whether it supports the proposition, and whether its jurisdiction and date fit. Explain all accepted and rejected suggestions. You can complete this exercise using the deliberately flawed classroom text without accessing any AI service.",activity:"Audit this fictional statement: 'A screenshot always proves consent; a platform is never responsible; deleting a post removes every legal consequence.' Identify unsupported assertions and write a qualified correction.",reading:[2,3,4]},
 {n:8,meetings:"15–16",title:"Final opinion and oral defence",outcome:"Produce a coherent legal opinion with evidence limits and proportionate recommendations.",note:"Integrate the actor map, sources, evidence analysis and alternative arguments into a decision-ready opinion. Prioritize recommendations, identify who must act, and state what remains unresolved. Keep a revision log showing how feedback changed the reasoning. A polished conclusion cannot substitute for verifiable authority.",activity:"Submit the final opinion and defend one contested conclusion. The lecturer determines official assessment rules and dates.",reading:[2,3,4,5,6,7]},
] as const;
export const assignments = [
 {id:"issue-map",title:"1 · Issue and authority map",suggested:"After unit 2",case:"Fictional case MY-01: SelatMart advertises a student laptop as new. A buyer receives a refurbished unit. The checkout link now displays different refund terms. The seller blames the platform, while the platform points to its terms. You have an order receipt, an advertisement screenshot without metadata, and two dated versions of the terms.",deliverable:"Write 500–800 words. Separate established facts and assumptions; map seller, buyer and platform; formulate at least three legal questions; identify applicable sources and two competing routes to a remedy.",questions:["Which evidence establishes the terms accepted at checkout?","Which obligations require analysis for each actor?","What additional material would you request before advising the buyer?"]},
 {id:"privacy-memo",title:"2 · Privacy and data-incident memorandum",suggested:"After unit 4 · proposed mid-semester task",case:"Fictional case MY-02: KampusLink collects names, student IDs, locations and event attendance. A contractor maintains the system. A spreadsheet appears in a public folder, but its access history is incomplete. A sponsor requests the attendance list for marketing. The campus wants to delete the folder immediately and describe the event as harmless.",deliverable:"Write 800–1,200 words. Map data flows and actor roles, distinguish established exposure from uncertain access, examine the legal bases and relevant duties, and propose prioritized steps. Cite exact provisions; do not invent notification deadlines or conclude that consent solves every issue.",questions:["Who determines purposes and means for each processing activity?","What facts and applicable provisions must be verified before deciding on notification?","How can evidence be preserved while reducing ongoing exposure?"]},
 {id:"evidence-file",title:"3 · Digital evidence and platform review",suggested:"After unit 6",case:"Fictional case MY-03: A public account accuses a student club of selling member data. A repost adds a private phone number. The platform removes one post but not the repost. Available materials are a cropped screenshot, a downloaded chat, and a witness note written two days later. No one has established who controlled the account.",deliverable:"Write 700–1,000 words plus a plain-text evidence register. For each item record provenance, date, integrity limits, lawful collection and what it can or cannot establish. Compare proportionate platform, civil and possible criminal responses without prejudging liability.",questions:["What is missing from the screenshot's context?","How would you distinguish account identity from the person who posted?","Which current rules and judicial decisions must be checked for the incident date?"]},
 {id:"final-opinion",title:"4 · Integrated opinion and reflection",suggested:"After unit 8 · proposed final task",case:"Fictional case MY-04: NusantaraTutor sells online tutoring subscriptions, uses a contractor's recommendation tool, and stores student profiles. A disputed renewal charge, an exposed profile folder and a misleading promotional claim arise in the same week. Management offers a blanket refund waiver and asks for an AI-generated statement denying all responsibility.",deliverable:"Write 1,200–1,800 words. Create a timeline and actor map, prioritize the separate legal issues, verify primary sources, assess evidence limits, present counterarguments, and recommend a staged response. Include a revision log and declare any external AI use. Prepare a five-minute oral defence.",questions:["Which problems require separate factual and legal analysis?","Which recommendations can be given now and which depend on additional evidence?","How did feedback or source verification change your conclusion?"]},
] as const;
export const rubric = [
 {key:"issue_score",label:"Issue identification and factual discipline",max:20,guide:"High: separates proved facts, assumptions, actors and legal questions. Low: conflates actors or assumes disputed facts."},
 {key:"source_score",label:"Primary sources and citation integrity",max:25,guide:"High: exact provisions, dates and relevant authority are verified. Low: missing, outdated, invented or unsupported citations."},
 {key:"reasoning_score",label:"Application and counterarguments",max:25,guide:"High: applies rules to evidence and addresses a credible alternative. Low: lists rules without application."},
 {key:"remedy_score",label:"Remedies and practical recommendations",max:15,guide:"High: proportionate, prioritized steps with clear conditions. Low: blanket or unsupported recommendations."},
 {key:"integrity_score",label:"Transparency, reflection and presentation",max:15,guide:"High: clear structure, revision trace and honest tool disclosure. Low: concealed assistance or unexplained conclusions."},
] as const;
export function getAssignment(id: string) { return assignments.find(a=>a.id===id); }
