"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-5-v1";
const SOURCE_URL = "https://www.perpusnas.go.id/berita/sah-naskah-karya-raja-ali-haji-masuk-dalam-ingatan-kolektif-nasional";

const nav = [
  ["introduction", "Pengantar"], ["reading", "Bacaan utama"], ["analysis", "Kerangka amanah"],
  ["podcast", "Podcast"], ["reflection", "Refleksi"], ["essay", "Esai"], ["quiz", "Kuis"], ["result", "Hasil"],
];

const readings = [
  { n:"I", title:"Buah dari tugas-tugas yang penting", text:<><p><em>Tsamarat al-Muhimmah</em> membahas tata pemerintahan dan tanggung jawab pemegang jabatan di lingkungan kerajaan Riau–Lingga. Judulnya dapat dipahami sebagai “buah dari tugas-tugas yang penting”: kekuasaan dinilai dari hasil moral dan kemaslahatan yang dilahirkannya.</p><p>Karya ini terdiri atas tiga bagian dan tujuh belas pasal. Pembahasannya mencakup kedudukan raja, pembesar kerajaan, mahkamah, tugas pejabat, serta sifat yang menguatkan atau merusak pemerintahan.</p></>, idea:"Jabatan bukan kehormatan pribadi, melainkan tugas yang harus menghasilkan keadilan dan kemaslahatan." },
  { n:"II", title:"Kekuasaan sebagai amanah", text:<><p>Dalam kerangka Raja Ali Haji, raja dan pejabat tidak bebas memakai kewenangan menurut hawa nafsu. Kekuasaan terikat kepada agama, hukum, keadilan, dan kewajiban menjaga negeri.</p><p>Amanah berarti kewenangan diterima untuk tujuan tertentu dan harus dipertanggungjawabkan. Karena itu, pertanyaan utama bukan hanya siapa yang berkuasa, tetapi untuk apa kekuasaan digunakan dan bagaimana akibatnya bagi rakyat.</p></>, idea:"Legitimasi jabatan harus disertai tanggung jawab atas cara dan akibat penggunaan kekuasaan." },
  { n:"III", title:"Syarat moral dan kecakapan pejabat", text:<><p>Raja Ali Haji menaruh perhatian pada kualitas lahir dan batin seorang pemimpin: kemampuan menjalankan tugas, kejernihan pertimbangan, pengetahuan, marwah, serta pengendalian diri. Moralitas dan kecakapan tidak boleh dipisahkan.</p><p>Orang baik tanpa kemampuan dapat gagal mengurus lembaga. Orang cakap tanpa integritas dapat memakai kemampuannya untuk merusak. Jabatan publik memerlukan keduanya, ditambah kesediaan menerima nasihat dan koreksi.</p></>, idea:"Integritas tanpa kompetensi tidak cukup; kompetensi tanpa integritas berbahaya." },
  { n:"IV", title:"Pembagian tugas dan tertib kelembagaan", text:<><p>Pemerintahan tidak dijalankan oleh raja seorang diri. Terdapat pembesar, penasihat, hakim, katib, dan petugas lain dengan fungsi yang berbeda. Pembagian tugas menjaga agar pekerjaan negara dapat diperiksa dan tidak bergantung pada kehendak satu orang.</p><p>Tertib kelembagaan membutuhkan kejelasan kewenangan, pencatatan, prosedur, dan koordinasi. Ketika tanggung jawab kabur, kesalahan mudah dipindahkan dan keputusan kehilangan pemilik yang dapat dimintai pertanggungjawaban.</p></>, idea:"Akuntabilitas lahir ketika kewenangan, tugas, proses, dan penanggung jawab dapat diketahui." },
  { n:"V", title:"Mahkamah, hukum, dan keadilan", text:<><p><em>Tsamarat al-Muhimmah</em> memberi perhatian khusus kepada penyelenggaraan mahkamah. Hukum harus dijalankan oleh orang yang berpengetahuan, mendengar para pihak, memeriksa bukti, dan tidak tunduk kepada kepentingan pribadi.</p><p>Keadilan bukan sekadar sifat baik dalam hati. Ia harus tampak dalam prosedur dan keputusan: perkara ditangani tanpa pilih kasih, alasan dapat dijelaskan, dan kewenangan tidak digunakan untuk melindungi kerabat atau kelompok sendiri.</p></>, idea:"Keadilan memerlukan watak pejabat sekaligus prosedur yang dapat diperiksa." },
  { n:"VI", title:"Penyakit kekuasaan", text:<><p>Raja Ali Haji mengingatkan sifat yang mencederai pemimpin dan pembesar: takabur, mengikuti hawa nafsu, lalai, tamak, dan mengabaikan nasihat. Penyakit ini membuat jabatan berubah dari amanah menjadi sarana kepentingan diri.</p><p>Bahaya kekuasaan sering tumbuh sedikit demi sedikit—ketika kritik dianggap penghinaan, fasilitas dipandang sebagai milik pribadi, dan loyalitas kepada atasan menggantikan loyalitas kepada tugas. Karena itu, pengendalian diri harus didukung pengawasan kelembagaan.</p></>, idea:"Kerusakan kekuasaan bermula ketika pejabat tidak lagi membedakan kepentingan jabatan dan kepentingan dirinya." },
  { n:"VII", title:"Dari kerajaan menuju pelayanan publik modern", text:<><p>Bentuk negara modern berbeda dari kerajaan Riau–Lingga. Namun pertanyaan normatifnya tetap penting: apakah pejabat memenuhi syarat, memahami tugas, menghindari konflik kepentingan, mengikuti prosedur, menerima pengawasan, dan memberikan alasan atas keputusan?</p><p>Kita tidak memindahkan aturan abad kesembilan belas secara harfiah. Kita mengambil prinsipnya—amanah, kompetensi, pembagian tugas, keadilan, dan pertanggungjawaban—lalu mengujinya dalam administrasi publik, sekolah, kampus, organisasi, dan pemerintahan masa kini.</p></>, idea:"Warisan politik dibaca secara kontekstual: prinsipnya dikembangkan, bentuk kelembagaannya disesuaikan." },
];

const questions = [
  { q:"Pokok bahasan Tsamarat al-Muhimmah adalah…", o:["Teknik pelayaran","Tata pemerintahan dan tanggung jawab pejabat","Kamus bahasa","Hukum perdagangan kolonial"], a:1 },
  { q:"Karya ini tersusun atas…", o:["Tiga bagian dan tujuh belas pasal","Dua belas pasal saja","Seratus bab","Satu syair pendek"], a:0 },
  { q:"Kekuasaan sebagai amanah berarti…", o:["Jabatan menjadi milik pribadi","Kewenangan diterima untuk tujuan yang harus dipertanggungjawabkan","Pemimpin bebas dari hukum","Rakyat tidak boleh menilai"], a:1 },
  { q:"Pejabat yang baik memerlukan…", o:["Keturunan saja","Integritas dan kompetensi","Popularitas saja","Kekayaan pribadi"], a:1 },
  { q:"Pembagian tugas mendukung akuntabilitas karena…", o:["Menghapus semua pemimpin","Membuat kewenangan dan penanggung jawab dapat diketahui","Mencegah pencatatan","Menyerahkan semua urusan kepada satu orang"], a:1 },
  { q:"Keadilan dalam mahkamah memerlukan…", o:["Keputusan tanpa alasan","Pemeriksaan bukti dan perlakuan tanpa pilih kasih","Perlindungan kerabat","Ketaatan kepada orang terkuat"], a:1 },
  { q:"Salah satu penyakit kekuasaan ialah…", o:["Menerima koreksi","Takabur dan mengikuti hawa nafsu","Mencatat keputusan","Membagi kewenangan"], a:1 },
  { q:"Konflik kepentingan terjadi ketika…", o:["Pejabat memisahkan urusan pribadi dan jabatan","Kepentingan pribadi memengaruhi pelaksanaan tugas publik","Keputusan diperiksa","Tugas dijelaskan"], a:1 },
  { q:"Cara tepat membaca karya ini untuk masa kini adalah…", o:["Menyalin seluruh bentuk kerajaan secara harfiah","Mengembangkan prinsip dan menyesuaikan kelembagaannya","Mengabaikannya karena tua","Menghapus konteks sejarah"], a:1 },
  { q:"Rangkaian utama akuntabilitas adalah…", o:["Kewenangan, tugas, proses, hasil, dan pertanggungjawaban","Jabatan, fasilitas, pujian, dan kekebalan","Rahasia, ketaatan, dan hadiah","Keturunan, kekayaan, dan pengaruh"], a:0 },
];

export default function ModuleFiveLearning() {
  const [active, setActive] = useState("introduction");
  const [reflection, setReflection] = useState("");
  const [essay, setEssay] = useState("");
  const [answers, setAnswers] = useState<AnswerMap>({});
  const [score, setScore] = useState<number | null>(null);
  const [readingDone, setReadingDone] = useState(false);
  const [analysisDone, setAnalysisDone] = useState(false);
  const [podcastDone, setPodcastDone] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const d = JSON.parse(raw); setReflection(d.reflection ?? ""); setEssay(d.essay ?? ""); setAnswers(d.answers ?? {}); setScore(d.score ?? null); setReadingDone(Boolean(d.readingDone)); setAnalysisDone(Boolean(d.analysisDone)); setPodcastDone(Boolean(d.podcastDone)); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; const id = window.setTimeout(() => { void saveModuleProgress(STORAGE_KEY, 5, { reflection, essay, answers, score, readingDone, analysisDone, podcastDone }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200); }); }, 500); return () => window.clearTimeout(id); }, [reflection, essay, answers, score, readingDone, analysisDone, podcastDone, hydrated]);

  const reflectionWords = useMemo(() => countWords(reflection), [reflection]);
  const essayWords = useMemo(() => countWords(essay), [essay]);
  const reflectionDone = reflectionWords >= 100;
  const essayDone = essayWords >= 500;
  const quizDone = score !== null && score >= 70;
  const done = [readingDone, analysisDone, podcastDone, reflectionDone, essayDone, quizDone];
  const progress = Math.round(done.filter(Boolean).length / 6 * 100);
  const complete = done.every(Boolean);

  function submit() { if (Object.keys(answers).length < questions.length) { alert("Jawab seluruh pertanyaan terlebih dahulu."); return; } setScore(questions.filter((q, i) => Number(answers[i]) === q.a).length * 10); setActive("result"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <main className="min-h-screen bg-[#f7f4ee] text-slate-950">
    <header className="border-b border-white/10 bg-[#070916] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-400"><ArrowLeft size={17}/> Kembali ke program</Link><div className="min-w-56"><div className="flex justify-between text-xs"><span>Progres Modul 5</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${progress}%` }}/></div></div></div></header>
    <section className="bg-[#070916] px-5 pb-14 pt-10 text-white sm:px-8 md:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 5 dari 8</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Tsamarat al-Muhimmah: Tanggung Jawab Pejabat</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Membaca kekuasaan sebagai amanah, pembagian tugas, keadilan mahkamah, dan pertanggungjawaban pejabat.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 120–150 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Tingkat dasar</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai, dan kuis</span></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id, label], i) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active === id ? "bg-slate-950 text-white" : "hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i + 1).padStart(2, "0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved ? "Tersimpan otomatis ✓" : "Progres tersimpan di perangkat ini"}</div></aside>
      <div className="min-w-0">
        {active === "introduction" && <Panel eyebrow="Mulai di sini" title="Pengantar Modul 5"><p>Setelah mempelajari etika, tata bahasa, dan tata makna, Modul 5 memasuki jantung pemikiran pemerintahan Raja Ali Haji. <em>Tsamarat al-Muhimmah</em> menilai jabatan melalui amanah, kecakapan, keadilan, serta hasil yang dirasakan negeri dan rakyat.</p><h3>Tujuan pembelajaran</h3><ol><li>Menjelaskan konteks dan susunan <em>Tsamarat al-Muhimmah</em>.</li><li>Menganalisis kekuasaan sebagai amanah yang terbatas.</li><li>Menghubungkan integritas, kompetensi, pembagian tugas, dan keadilan.</li><li>Menerapkan prinsip akuntabilitas pada pelayanan publik masa kini.</li></ol><blockquote>Jika sebuah keputusan dibuat sesuai kewenangan, tetapi merugikan rakyat dan tidak dapat dijelaskan, apakah pejabatnya sudah menjalankan amanah?</blockquote><Next onClick={() => setActive("reading")}>Mulai membaca</Next></Panel>}
        {active === "reading" && <Panel eyebrow="Bacaan utama • 35–45 menit" title="Jabatan sebagai amanah yang dapat dinilai"><p>Tujuh bagian bacaan berikut menjelaskan kerangka pemerintahan Raja Ali Haji dan menghubungkannya secara hati-hati dengan akuntabilitas modern. Bentuk kerajaan tidak disalin secara harfiah; prinsip tanggung jawabnya yang diuji.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Lihat rekam naskah sumber</p><p className="mt-2 text-sm leading-6 text-slate-600">Perpustakaan Nasional mencatat naskah W 18 <em>Tsamarat al-Muhimmah</em> sebagai salah satu karya Raja Ali Haji dalam Ingatan Kolektif Nasional.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka catatan Perpustakaan Nasional <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e => setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 5.</label><Next onClick={() => setActive("analysis")}>Lanjut ke kerangka amanah</Next></Panel>}
        {active === "analysis" && <Panel eyebrow="Analisis konseptual" title="Rantai akuntabilitas jabatan"><div className="grid gap-4 md:grid-cols-3"><Concept n="01" title="Amanah" text="Kewenangan diterima untuk tujuan yang melampaui kepentingan pribadi."/><Concept n="02" title="Tertib tugas" text="Wewenang, prosedur, dan penanggung jawab harus diketahui."/><Concept n="03" title="Pertanggungjawaban" text="Keputusan, alasan, proses, dan akibat dapat diperiksa serta dinilai."/></div><h3>Dari jabatan menuju kewajiban</h3><p>Jabatan memberi kewenangan sekaligus memperbesar kewajiban. Semakin luas dampak keputusan, semakin kuat alasan, kehati-hatian, dan pengawasan yang diperlukan.</p><h3>Dari watak menuju sistem</h3><p>Integritas pribadi penting, tetapi tidak cukup. Pembagian tugas, pencatatan, prosedur pemeriksaan, dan saluran koreksi melindungi lembaga dari kelemahan manusia.</p><h3>Dari keputusan menuju akibat</h3><p>Akuntabilitas tidak berhenti pada kalimat “sudah sesuai prosedur”. Pejabat juga harus melihat tujuan kewenangan, kelompok yang terdampak, serta tindakan perbaikan ketika hasilnya menyimpang.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e => setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami hubungan amanah, tertib tugas, dan pertanggungjawaban.</label><Next onClick={() => setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
        {active === "podcast" && <Panel eyebrow="Podcast • akan ditambahkan" title="Ketika Jabatan Menjadi Amanah"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Podcast Modul 5 sedang disiapkan</p><p className="mt-1 text-sm text-slate-400">Pemutar akan diaktifkan setelah Audio Overview tersedia.</p></div></div></div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan sementara</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p><em>Tsamarat al-Muhimmah</em> menempatkan jabatan sebagai amanah yang harus menghasilkan keadilan dan kemaslahatan. Moralitas pejabat harus berjalan bersama kecakapan dan tertib kelembagaan.</p><p>Dalam konteks modern, gagasan itu dapat dibaca melalui pembagian tugas, konflik kepentingan, alasan keputusan, pemeriksaan prosedur, akibat kebijakan, dan kewajiban memperbaiki kesalahan.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e => setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari ringkasan podcast.</label><Next onClick={() => setActive("reflection")}>Lanjut ke refleksi</Next></Panel>}
        {active === "reflection" && <Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi tentang amanah"><p>Ingat satu jabatan publik atau organisasi yang Anda kenal. Jelaskan kewenangannya, siapa yang terdampak, dan bentuk pertanggungjawaban yang semestinya tersedia.</p><textarea value={reflection} onChange={e => setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={() => setActive("essay")}>Simpan dan lanjut ke esai</Next></Panel>}
        {active === "essay" && <Panel eyebrow="Penilaian • 500–700 kata" title="Tugas esai Modul 5"><blockquote>Jelaskan bagaimana prinsip amanah dalam <em>Tsamarat al-Muhimmah</em> dapat dikembangkan menjadi kerangka akuntabilitas pejabat publik masa kini.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan sedikitnya tiga bagian bacaan Modul 5.</li><li>Bahas integritas, kompetensi, dan pembagian tugas.</li><li>Jelaskan pentingnya prosedur serta akibat keputusan.</li><li>Gunakan satu contoh lembaga atau pelayanan publik kontemporer.</li></ul><textarea value={essay} onChange={e => setEssay(e.target.value)} rows={22} placeholder="Mulai menulis esai…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={500} max={700}/><Next disabled={!essayDone} onClick={() => setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
        {active === "quiz" && <Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 5"><div className="space-y-8">{questions.map((q, i) => <fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i + 1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o, j) => <label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i]) === j ? "border-amber-600 bg-amber-50" : "border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q5-${i}`} checked={Number(answers[i]) === j} value={j} onChange={e => setAnswers({ ...answers, [i]: e.target.value })} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
        {active === "result" && <Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 5"><div className={`border p-7 ${complete ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score ?? 0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone ? "Kuis lulus." : "Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan utama selesai"/><Req done={analysisDone} text="Kerangka amanah selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai minimal 500 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete ? <div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 5 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menyelesaikan pembelajaran amanah, tertib tugas, keadilan, dan pertanggungjawaban pejabat dalam <em>Tsamarat al-Muhimmah</em>.</p><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji/module-6" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 font-bold text-emerald-800 transition hover:bg-emerald-50">Lanjut ke Modul 6 <ArrowRight size={18}/></Link></div> : <button onClick={() => { setAnswers({}); setScore(null); setActive("quiz"); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
      </div>
    </div>
  </main>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>; }
function Next({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>; }
function Words({ count, min, max }: { count: number; min: number; max: number }) { return <p className={`text-sm font-semibold ${count >= min ? "text-emerald-700" : "text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count >= min ? "✓" : ""}</p>; }
function Req({ done, text }: { done: boolean; text: string }) { return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done ? "text-emerald-600" : "text-stone-300"} size={21}/><span className={done ? "font-semibold" : "text-slate-500"}>{text}</span></div>; }
function Concept({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+/).length : 0; }
function ReadingAccordion() { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section, i) => <article key={section.n}><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open === i ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>{open === i && <div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>}</article>)}</div>; }
