import Link from "next/link";
import { stages } from "@/lib/lexnusa/cohort";
export const metadata = { title: "Legal AI Cohort | LexNusa", alternates: { canonical: "/lexnusa/cohort" } };
export default function Page() {
  return <main className="bg-[#f7f5ef] text-slate-900">
    <section className="bg-[#101d2a] px-6 py-20 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-widest text-amber-300">LexNusa · Legal AI Cohort</p><h1 className="mt-5 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">Belajar hukum. Praktik dengan AI. Pertanggungjawabkan hasilnya.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Kelas empat minggu untuk menyusun dan meninjau kontrak kerja. Kerjakan satu kasus dari brief sampai revisi, simpan setiap versi, dan terima umpan balik fasilitator.</p><div className="mt-8 flex flex-wrap gap-4"><Link className="rounded-xl bg-amber-400 px-6 py-4 font-bold text-slate-950" href="/lexnusa/cohort/workspace">Masuk kelas</Link><Link className="rounded-xl border border-white/30 px-6 py-4" href="/lexnusa/cohort/register">Buat akun belajar</Link></div><p className="mt-5 text-sm text-slate-300">Tanggal, biaya, dan pembukaan pendaftaran diumumkan setelah kelas siap. Akun Institute dapat digunakan untuk masuk.</p></div></section>
    <section className="mx-auto max-w-6xl px-6 py-16"><h2 className="text-3xl font-bold">Satu kasus, lima hasil kerja</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{stages.map((s,i)=><article key={s.key} className="rounded-2xl border bg-white p-6"><p className="font-bold text-teal-700">Minggu {s.week} · Tahap {i+1}</p><h3 className="mt-3 text-xl font-bold">{s.title}</h3><p className="mt-3 leading-7 text-slate-600">{s.help}</p></article>)}</div><div className="mt-10 rounded-2xl bg-teal-800 p-8 text-white"><h2 className="text-2xl font-bold">Portofolio pribadi dan review manusia</h2><p className="mt-4 leading-7">Brief, instruksi, draf, catatan evaluasi, dan revisi menjadi bukti belajar. Nilai kemampuan peserta terpisah dari skor mutu keluaran LEX-EVAL. Semua pekerjaan bersifat privat; fasilitator kelas memberikan keputusan akhir.</p><Link className="mt-5 inline-block underline" href="/lexnusa/lex-eval">Pelajari metodologi LEX-EVAL</Link></div></section>
  </main>;
}
