const assert = require('node:assert/strict');
const ts = require('typescript');
const fs = require('node:fs');
const Module = require('node:module');
const m = new Module('cji-model');
m._compile(ts.transpileModule(fs.readFileSync('lib/cji/model.ts', 'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,'cji-model.js');
const {parseRecord}=m.exports;
const client={id:'00000000-0000-4000-8000-000000000001',kind:'client',title:'Klien uji',status:'Aktif',details:{}};
assert.equal(parseRecord(client).title,'Klien uji');
assert.throws(()=>parseRecord({...client,kind:'constructor'}));
assert.throws(()=>parseRecord({...client,status:'invented'}));
assert.throws(()=>parseRecord({...client,details:{email:'bad'}}));
assert.throws(()=>parseRecord({...client,kind:'matter',status:'Aktif'}));
const finance={...client,kind:'finance',status:'Dibayar',due_at:'2026-09-29T09:00:00+07:00',details:{amount:'50000',direction:'Pemasukan'}};
assert.equal(parseRecord(finance).due_at,'2026-09-29T02:00:00.000Z');
assert.throws(()=>parseRecord({...finance,details:{amount:'-1',direction:'Pemasukan'}}));
assert.throws(()=>parseRecord({...finance,details:{amount:'1.5',direction:'Pemasukan'}}));
assert.throws(()=>parseRecord({...client,kind:'decision',status:'Dicatat',parent_id:'00000000-0000-4000-8000-000000000002',details:{source_url:'javascript:alert(1)'}}));
console.log('PASS: CJI validation, required relations, currency, WIB conversion, safe source URLs');
