import Link from "next/link";
import { lecturerSession } from "@/lib/lexnusa/mayantara/access";
import { assignments, rubric, coursePath } from "@/lib/lexnusa/mayantara/course";
import { reviewWork,setMemberStatus } from "../actions";
import ActionForm from "../ActionForm";
export const metadata={title:"Cybercrime Law Lecturer Dashboard | LexNusa",robots:{index:false,follow:false}};
export default async function Page(){
 const {db,user}=await lecturerSession();
 const [{data:members,error:me},{data:works,error:we},{data:reviews,error:re}]=await Promise.all([db.from("lexnusa_mayantara_members").select("*").order("created_at"),db.from("lexnusa_mayantara_work").select("*").order("version_number",{ascending:false}),db.from("lexnusa_mayantara_reviews").select("*")]);
 if(me||we||re)return <main className="p-10"><h1>Class data could not be loaded</h1><p>Refresh before reviewing work.</p></main>;
 return <main className="mx-auto max-w-6xl space-y-8 px-6 py-12"><Link href={coursePath} className="text-teal-800 underline">Course materials and rubric</Link><h1 className="text-4xl font-bold">Hukum Kejahatan Mayantara · Lecturer dashboard</h1><p>{members?.length??0} membership requests · {members?.filter(m=>m.status==="active").length??0} active students</p><aside className="rounded-xl bg-amber-50 p-5">Verify students against your class list before admitting them. Scores here are formative, not an official transcript or workshop certificate. UMRAH · Law Programme · Semester V · 2 SKS. Confirm dates and the draft RPS weights before teaching; record quizzes, participation and oral scores separately.</aside>
 <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">Teaching guide · first meeting and assessment</summary><ol className="mt-4 list-decimal space-y-3 pl-5"><li>Ask students to map the actors and uncertainties in HKM-01 (SelatTiket) before reading legislation.</li><li>Open one primary source together. Demonstrate how to identify its version, provision and supported proposition.</li><li>Have students request membership with their NIM. Admit only verified class members.</li><li>Ask each student to save an initial issue map, then submit it with source notes and the integrity declaration.</li><li>Use the five written-work rubric criteria. The RPS uses levels 0–4: level/4 × criterion maximum; the classroom stores whole points, so round criterion results to the nearest whole point and explain the level in feedback. Give one strength, one source problem and one revision request.</li><li>Use an oral defence to probe reasoning. New work versions need a new review; earlier feedback remains visible.</li><li>Set the fictional incident date and provide the same synthetic evidence package to all students before assessment. Never ask students to intrude into real systems.</li><li>Use T1 in week 4, UTS in week 8, T2 in week 12 and UAS in week 16. Record oral defence separately (20% of UAS); written opinion contributes 80%.</li><li>Target feedback within seven days and a revision within the next seven days where possible. Announce revision grading, attendance, late-work and accessibility arrangements.</li></ol><Link href={coursePath+"#assessment"} className="mt-4 inline-block text-teal-800 underline">View proposed assessment weights</Link></details>
 {!members?.length&&<p>No students have requested membership yet. Share the course link with your class.</p>}
 {members?.map(m=><article key={m.user_id} className="space-y-5 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">{m.display_name}</h2><p>NIM {m.student_number} · {m.status}</p><ActionForm action={setMemberStatus}><input type="hidden" name="student_id" value={m.user_id}/><button name="status" value={m.status==="active"?"suspended":"active"} className="rounded-lg border px-4 py-3 font-bold">{m.status==="active"?"Suspend submission access":"Admit student"}</button></ActionForm>
 {assignments.map(a=>{const w=works?.find(w=>w.user_id===m.user_id&&w.assignment===a.id);const review=reviews?.find(r=>r.work_id===w?.id);return <details key={a.id} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{a.title} · {review?review.score+"/100":w?.submitted?"Awaiting review":w?"Draft":"Not started"}</summary>{w&&<div className="mt-4 space-y-4"><p>Version {w.version_number} · {new Date(w.created_at).toLocaleString("en-GB",{timeZone:"Asia/Jakarta"})} WIB</p><h3 className="font-bold">Analysis</h3><p className="whitespace-pre-wrap break-words">{w.answer}</p><h3 className="font-bold">Sources</h3><p className="whitespace-pre-wrap break-words">{w.sources}</p><h3 className="font-bold">Reflection</h3><p className="whitespace-pre-wrap break-words">{w.reflection}</p>{review?<div className="rounded-lg bg-teal-50 p-4"><strong>{review.decision} · {review.score}/100</strong><p className="whitespace-pre-wrap">{review.feedback}</p></div>:w.submitted&&m.user_id!==user.id?<ActionForm action={reviewWork}><input type="hidden" name="work_id" value={w.id}/>{rubric.map(r=><label key={r.key} className="block">{r.label} (0–{r.max})<input required name={r.key} type="number" min={0} max={r.max} step={1} className="ml-3 w-24 rounded border p-2"/></label>)}<label className="block">Feedback<textarea required name="feedback" minLength={40} maxLength={10000} rows={5} className="mt-2 w-full rounded border p-3"/></label><label className="block">Decision<select name="decision" className="ml-3 rounded border p-3"><option value="revise">Revision required</option><option value="reviewed">Reviewed</option></select></label><button className="rounded-lg bg-teal-800 px-5 py-3 font-bold text-white">Record review</button></ActionForm>:<p className="text-sm">Only submitted work can be reviewed. Self-review is not permitted.</p>}</div>}</details>;})}</article>)}</main>;
}
