import Link from "next/link";
import { lecturerSession } from "@/lib/lexnusa/mayantara/access";
import { assignments, rubric, coursePath, membershipLabel, reviewLabel } from "@/lib/lexnusa/mayantara/course";
import { reviewWork,setMemberStatus } from "../actions";
import ActionForm from "../ActionForm";
export const metadata={title:"Dasbor Dosen Hukum Kejahatan Mayantara | LexNusa",robots:{index:false,follow:false}};
export default async function Page(){
 const {db,user}=await lecturerSession();
 const [{data:members,error:me},{data:works,error:we},{data:reviews,error:re}]=await Promise.all([db.from("lexnusa_mayantara_members").select("*").order("created_at"),db.from("lexnusa_mayantara_work").select("*").order("version_number",{ascending:false}),db.from("lexnusa_mayantara_reviews").select("*")]);
 if(me||we||re)return <main className="p-10"><h1>Data kelas tidak dapat dimuat</h1><p>Muat ulang halaman sebelum meninjau tugas.</p></main>;
 return <main className="mx-auto max-w-6xl space-y-8 px-6 py-12"><Link href={coursePath} className="text-teal-800 underline">Materi kuliah dan rubrik</Link><h1 className="text-4xl font-bold">Hukum Kejahatan Mayantara · Dasbor dosen</h1><p>{members?.length??0} pengajuan keanggotaan · {members?.filter(m=>m.status==="active").length??0} mahasiswa aktif</p><aside className="rounded-xl bg-amber-50 p-5">Cocokkan mahasiswa dengan daftar kelas sebelum menerima mereka. Nilai di sini bersifat formatif, bukan transkrip resmi atau sertifikat lokakarya. UMRAH · Program Studi Ilmu Hukum · Semester V · 2 SKS. Konfirmasikan tanggal dan bobot draf RPS sebelum mengajar; catat nilai kuis, partisipasi, dan lisan secara terpisah.</aside>
 <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">Panduan mengajar · pertemuan pertama dan penilaian</summary><ol className="mt-4 list-decimal space-y-3 pl-5"><li>Minta mahasiswa memetakan para pihak dan ketidakpastian dalam HKM-01 (SelatTiket) sebelum membaca peraturan.</li><li>Buka satu sumber primer bersama. Tunjukkan cara mengidentifikasi versi, ketentuan, dan pernyataan yang didukungnya.</li><li>Minta mahasiswa mengajukan keanggotaan dengan NIM. Terima hanya anggota kelas yang sudah diverifikasi.</li><li>Minta setiap mahasiswa menyimpan peta isu awal, lalu mengumpulkannya dengan catatan sumber dan pernyataan integritas.</li><li>Gunakan lima kriteria rubrik tugas tertulis. RPS menggunakan tingkat 0–4: tingkat/4 × nilai maksimum kriteria. Aplikasi menyimpan poin bulat, sehingga hasil setiap kriteria dibulatkan ke bilangan bulat terdekat dan tingkatnya dijelaskan dalam umpan balik. Berikan satu kelebihan, satu persoalan sumber, dan satu permintaan revisi.</li><li>Gunakan pembelaan lisan untuk mendalami penalaran. Versi tugas baru memerlukan tinjauan baru; umpan balik sebelumnya tetap terlihat.</li><li>Tetapkan tanggal kejadian fiktif dan berikan paket bukti simulasi yang sama kepada seluruh mahasiswa sebelum penilaian. Jangan meminta mahasiswa menyusup ke sistem nyata.</li><li>Gunakan T1 pada minggu 4, UTS pada minggu 8, T2 pada minggu 12, dan UAS pada minggu 16. Catat pembelaan lisan secara terpisah (20% dari UAS); pendapat tertulis berkontribusi 80%.</li><li>Targetkan umpan balik dalam tujuh hari dan revisi dalam tujuh hari berikutnya jika memungkinkan. Umumkan ketentuan penilaian revisi, kehadiran, keterlambatan tugas, dan aksesibilitas.</li></ol><Link href={coursePath+"#assessment"} className="mt-4 inline-block text-teal-800 underline">Lihat usulan bobot penilaian</Link></details>
 {!members?.length&&<p>Belum ada mahasiswa yang mengajukan keanggotaan. Bagikan tautan kuliah kepada kelas Anda.</p>}
 {members?.map(m=><article key={m.user_id} className="space-y-5 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">{m.display_name}</h2><p>NIM {m.student_number} · {membershipLabel(m.status)}</p><ActionForm action={setMemberStatus}><input type="hidden" name="student_id" value={m.user_id}/><button name="status" value={m.status==="active"?"suspended":"active"} className="rounded-lg border px-4 py-3 font-bold">{m.status==="active"?"Tangguhkan akses pengumpulan":"Terima mahasiswa"}</button></ActionForm>
 {assignments.map(a=>{const w=works?.find(w=>w.user_id===m.user_id&&w.assignment===a.id);const review=reviews?.find(r=>r.work_id===w?.id);return <details key={a.id} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{a.title} · {review?review.score+"/100":w?.submitted?"Menunggu tinjauan":w?"Draf":"Belum dimulai"}</summary>{w&&<div className="mt-4 space-y-4"><p>Versi {w.version_number} · {new Date(w.created_at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})} WIB</p><h3 className="font-bold">Analisis</h3><p className="whitespace-pre-wrap break-words">{w.answer}</p><h3 className="font-bold">Sumber</h3><p className="whitespace-pre-wrap break-words">{w.sources}</p><h3 className="font-bold">Refleksi</h3><p className="whitespace-pre-wrap break-words">{w.reflection}</p>{review?<div className="rounded-lg bg-teal-50 p-4"><strong>{reviewLabel(review.decision)} · {review.score}/100</strong><p className="whitespace-pre-wrap">{review.feedback}</p></div>:w.submitted&&m.user_id!==user.id?<ActionForm action={reviewWork}><input type="hidden" name="work_id" value={w.id}/>{rubric.map(r=><label key={r.key} className="block">{r.label} (0–{r.max})<input required name={r.key} type="number" min={0} max={r.max} step={1} className="ml-3 w-24 rounded border p-2"/></label>)}<label className="block">Umpan balik<textarea required name="feedback" minLength={40} maxLength={10000} rows={5} className="mt-2 w-full rounded border p-3"/></label><label className="block">Keputusan<select name="decision" className="ml-3 rounded border p-3"><option value="revise">Perlu revisi</option><option value="reviewed">Sudah ditinjau</option></select></label><button className="rounded-lg bg-teal-800 px-5 py-3 font-bold text-white">Simpan tinjauan</button></ActionForm>:<p className="text-sm">Hanya tugas yang sudah dikumpulkan yang dapat ditinjau. Meninjau tugas sendiri tidak diperbolehkan.</p>}</div>}</details>;})}</article>)}</main>;
}
