import Link from "next/link";
import { assignments, units, sources, rubric, roomPath } from "@/lib/lexnusa/mayantara/course";
export const metadata={title:"Cyber Law Classroom | Hukum Mayantara | LexNusa",description:"A case-based cyber law classroom with primary-source reading, private student work, and lecturer review."};
export default function Page(){return <main className="bg-stone-50 text-slate-950">
 <section className="bg-slate-950 px-6 py-16 text-white"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-widest text-amber-300">LexNusa Classroom · Academic teaching</p><h1 className="mt-4 text-4xl font-bold sm:text-6xl">Cyber Law<br/><span className="text-teal-300">Hukum Mayantara</span></h1><p className="mt-6 max-w-3xl text-lg leading-8">Learn to investigate digital legal problems, verify sources, build arguments, and defend a reasoned opinion. Your work and lecturer feedback stay in one private classroom.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={roomPath} className="rounded-xl bg-amber-400 px-5 py-3 font-bold text-slate-950">Enter classroom</Link><Link href="/lexnusa/mayantara/register" className="rounded-xl border border-white/40 px-5 py-3 font-bold">Create student account</Link><Link href="/lexnusa/mayantara/lecturer" className="rounded-xl border border-white/40 px-5 py-3 font-bold">Lecturer dashboard</Link></div></div></section>
 <div className="mx-auto max-w-6xl space-y-12 px-6 py-12">
 <aside className="rounded-2xl border border-amber-300 bg-amber-50 p-6"><h2 className="text-xl font-bold">Class preparation for the coming teaching period</h2><p className="mt-3 leading-7">The eight units below propose a 16-meeting sequence. Semester label, credits, dates, university RPS alignment and official assessment weights await the lecturer&apos;s confirmation. Students can request a place now; the lecturer approves access to submissions.</p><p className="mt-3 leading-7"><strong>AI assistance is unavailable.</strong> All exercises work manually. There is no requirement to purchase an AI subscription. Use fictional data; do not upload private case records. Assignments may be written in Indonesian or English.</p></aside>
 <section><h2 className="text-3xl font-bold">What students will be able to do</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{["Identify actors, facts, jurisdiction and legal issues in digital disputes.","Find and verify relevant primary authorities and their temporal application.","Evaluate digital evidence, data-processing roles and competing legal arguments.","Write a practical legal opinion and explain revisions transparently."].map(x=><li key={x} className="rounded-xl border bg-white p-5">{x}</li>)}</ul></section>
 <section><h2 className="text-3xl font-bold">Eight learning units</h2><p className="mt-3 text-slate-600">For each unit: read the note, open the sources, complete the classroom activity, and discuss your reasoning.</p><div className="mt-6 space-y-4">{units.map(u=><details key={u.n} className="rounded-2xl border bg-white p-6" open={u.n===1}><summary className="cursor-pointer text-xl font-bold">{u.n}. {u.title} <span className="block text-sm font-normal text-teal-800">Proposed meetings {u.meetings}</span></summary><p className="mt-4 font-semibold">Learning outcome: {u.outcome}</p><p className="mt-4 leading-8">{u.note}</p><p className="mt-4 rounded-xl bg-teal-50 p-4 leading-7"><strong>In-class activity:</strong> {u.activity}</p><ul className="mt-4 space-y-2">{u.reading.map(i=><li key={i}><a className="text-teal-800 underline" href={sources[i][1]}>{sources[i][0]}</a></li>)}</ul></details>)}</div></section>
 <section><h2 className="text-3xl font-bold">Four practical assignments</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{assignments.map(a=><article key={a.id} className="rounded-2xl border bg-white p-6"><p className="text-sm font-semibold text-teal-800">{a.suggested}</p><h3 className="mt-2 text-2xl font-bold">{a.title}</h3><p className="mt-4 leading-7">{a.case}</p><p className="mt-4 leading-7"><strong>Deliverable:</strong> {a.deliverable}</p><ul className="mt-4 list-disc space-y-2 pl-5">{a.questions.map(q=><li key={q}>{q}</li>)}</ul><Link href={roomPath+"?assignment="+a.id} className="mt-5 inline-block rounded-lg bg-teal-800 px-4 py-3 font-bold text-white">Open this assignment</Link></article>)}</div></section>
 <section><h2 className="text-3xl font-bold">Published assessment rubric</h2><p className="mt-3 text-slate-600">Each task is reviewed out of 100. These are formative classroom scores; official course weighting and grades remain the lecturer&apos;s responsibility.</p><div className="mt-5 space-y-3">{rubric.map(r=><article key={r.key} className="rounded-xl border bg-white p-5"><h3 className="font-bold">{r.label} · {r.max} points</h3><p className="mt-2 leading-7">{r.guide}</p></article>)}</div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Primary-source reading desk</h2><p className="mt-3 leading-7">Starting references checked on 8 September 2026. Read the original statute with its amendments and relevant court decisions. For criminal questions, check the 2026 framework and transitional provisions against the incident date. This list is a starting point, not a consolidated statement of every current rule.</p><ul className="mt-5 space-y-3">{sources.map(([title,url])=><li key={url}><a href={url} className="text-teal-800 underline">{title}</a></li>)}</ul></section>
 </div></main>;}
