import Link from 'next/link';
import type {Metadata} from 'next';
import {requireTreasurer} from '@/lib/persis/master-server';
import {loadReminderData} from '@/lib/persis/reminders-server';
import {REMINDER_BASE,reminderMonth,reminderState,LOG_STATUS,type ReminderData} from '@/lib/persis/reminders';
import {jakartaDate,rupiah,monthLabel,REGIONS} from '@/lib/persis/dues';
import TreasuryNav from '../TreasuryNav';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Pengingat Iuran PW Persis Kepri',robots:{index:false,follow:false}};
export default async function RemindersPage({searchParams}:{searchParams:Promise<{month?:string;status?:string;region?:string;q?:string;page?:string}>}){
 const {client}=await requireTreasurer(REMINDER_BASE),params=await searchParams,today=jakartaDate(),month=reminderMonth(params.month),status=params.status||'needs',query=(params.q||'').slice(0,120).toLowerCase(),region=REGIONS.includes(params.region as typeof REGIONS[number])?params.region!:'';
 let data:ReminderData|null=null,error='';try{data=await loadReminderData(client);}catch(e){error=e instanceof Error?e.message:'Data belum dapat dimuat.';}
 const all=data?.members.map(m=>reminderState(m,data!.rates,data!.payments,month,today))||[];
 const rows=all.filter(r=>(!region||r.member.region===region)&&(!query||`${r.member.full_name} ${r.member.member_number}`.toLowerCase().includes(query))).filter(r=>status==='all'||(status==='ready'?r.eligible:status==='pending'?r.pending>0:status==='data'?(!r.member.user_id||r.unknown||!r.member.contact?.verified_at):status==='paused'?r.member.contact?.paused:status==='due'?!!r.member.latest?.next_followup&&r.member.latest.next_followup<=today:r.amount>0||r.unknown||r.pending>0||!r.member.user_id)).sort((a,b)=>b.amount-a.amount||a.member.full_name.localeCompare(b.member.full_name,'id'));
 const page=Math.min(Math.max(1,parseInt(params.page||'1')||1),Math.max(1,Math.ceil(rows.length/20))),url=(p:number)=>`${REMINDER_BASE}?${new URLSearchParams({month,status,region,q:params.q||'',page:String(p)})}`;
 const paid=data?.payments.filter(p=>p.period===`${month}-01`&&p.status==='verified').reduce((s,p)=>s+p.amount,0)||0,pending=data?.payments.filter(p=>p.period===`${month}-01`&&p.status==='pending').reduce((s,p)=>s+p.amount,0)||0,arrears=all.filter(r=>r.member.user_id&&!r.unknown).reduce((s,r)=>s+r.monthlyArrears,0),incomplete=all.filter(r=>!r.member.user_id||r.unknown).length;
 return <div lang="id" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><main className="mx-auto max-w-6xl"><Link href="/persis-kepri/iuran" className="text-sm font-semibold text-emerald-800 underline">Kembali ke iuran anggota</Link><p className="mt-6 text-sm font-bold uppercase tracking-widest text-emerald-800">Ruang bendahara · PW Persis Kepri</p><h1 className="mt-2 text-3xl font-bold">Pengingat iuran & tindak lanjut</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">Siapkan pesan personal, periksa penerima, lalu kirim sendiri melalui WhatsApp. Sistem tidak mengirim pesan otomatis.</p><TreasuryNav/>
 {error?<p role="alert" className="rounded-xl bg-red-50 p-5 text-red-800">{error}</p>:<>
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Ringkasan bulan iuran {monthLabel(`${month}-01`)} · seluruh data</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{[['Terverifikasi',paid],['Menunggu verifikasi',pending],['Kekurangan jatuh tempo terhitung',arrears]].map(([label,n])=><div key={String(label)} className="rounded-xl bg-emerald-50 p-4"><p className="text-sm text-slate-600">{label}</p><p className="mt-2 text-xl font-bold text-emerald-900">{rupiah(Number(n))}</p></div>)}</div><p className="mt-3 text-sm leading-6 text-slate-600">Berdasarkan bulan tagihan, bukan tanggal penerimaan kas. {incomplete} anggota belum dapat dihitung lengkap karena akun/ketentuan belum siap. Pembayaran menunggu verifikasi belum dianggap lunas dan pengingatnya ditahan.</p></section>
 <form className="my-6 flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-5"><label className="grid gap-2 text-sm font-semibold">Tagihan sampai bulan<input type="month" name="month" required min="2020-01" max={today.slice(0,7)} defaultValue={month} className="rounded-lg border p-3"/></label><label className="grid gap-2 text-sm font-semibold">Tampilkan<select name="status" defaultValue={status} className="rounded-lg border p-3"><option value="needs">Perlu ditinjau</option><option value="ready">Siap diingatkan</option><option value="pending">Menunggu verifikasi</option><option value="data">Lengkapi data</option><option value="paused">Pengingat dijeda</option><option value="due">Jadwal tindak lanjut tiba</option><option value="all">Semua anggota</option></select></label><label className="grid gap-2 text-sm font-semibold">Daerah<select name="region" defaultValue={region} className="rounded-lg border p-3"><option value="">Semua daerah</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Nama / KTA<input name="q" maxLength={120} defaultValue={params.q} className="rounded-lg border p-3"/></label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Tampilkan</button></form>
 <p className="mb-4 text-sm text-slate-600">{rows.length} anggota sesuai filter. Rincian pengingat menghitung kekurangan sejak mulai wajib sampai bulan pilihan, termasuk tahun sebelumnya.</p>
 {!rows.length?<p className="rounded-xl border bg-white p-6 text-slate-600">Tidak ada anggota sesuai filter. Tambahkan anggota atau lengkapi ketentuan melalui menu pengelolaan.</p>:<div className="grid gap-4 md:grid-cols-2">{rows.slice((page-1)*20,page*20).map(r=><article key={r.member.id} className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-lg font-bold">{r.member.full_name}</h2><p className="mt-1 text-sm text-slate-500">{r.member.region} · {r.member.member_number||'KTA belum diisi'}</p><p className="mt-3 font-semibold">Kekurangan terhitung: {rupiah(r.amount)} · {r.debt.length} bulan</p><p className={`mt-2 text-sm ${r.eligible?'text-emerald-800':'text-amber-900'}`}>{r.blocked||'Siap diperiksa dan diingatkan'}</p>{r.pending>0&&<p className="mt-2 text-sm">Menunggu verifikasi (semua periode): {rupiah(r.pending)}</p>}{r.member.latest&&<p className="mt-3 text-xs leading-6 text-slate-500">Terakhir: {LOG_STATUS[r.member.latest.status]} · {new Date(r.member.latest.sent_at||r.member.latest.created_at).toLocaleDateString('id-ID',{timeZone:'Asia/Jakarta'})}{r.member.latest.next_followup?` · Tindak lanjut ${r.member.latest.next_followup}`:''}</p>}<Link href={`${REMINDER_BASE}/${r.member.id}?month=${month}`} className="mt-4 inline-block rounded-lg border border-emerald-700 px-4 py-2 text-sm font-bold text-emerald-900">Rincian & tindak lanjut</Link></article>)}</div>}
 <nav className="mt-6 flex gap-5 text-sm" aria-label="Halaman pengingat">{page>1&&<Link className="underline" href={url(page-1)}>Sebelumnya</Link>}<span>Halaman {page} / {Math.max(1,Math.ceil(rows.length/20))}</span>{page*20<rows.length&&<Link className="underline" href={url(page+1)}>Berikutnya</Link>}</nav>
 </>}
 </main></div>;
}
