import Link from "next/link";
import { cohortCode, stages, dimensions } from "@/lib/lexnusa/cohort";
import { enroll, saveVersion } from "./actions";
import {session} from "@/lib/lexnusa/cohort-access";
export const metadata={title:"Ruang Praktik | LexNusa Cohort",robots:{index:false,follow:false}};
export default async function Page({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}) {
 const query=await searchParams;const {supabase,user}=await session();
 const [{data:cohort,error:cohortError},{data:member}]=await Promise.all([
  supabase.from("lexnusa_cohorts").select("title,enrollment_open").eq("code",cohortCode).maybeSingle(),
  supabase.from("lexnusa_cohort_members").select("user_id").eq("cohort_code",cohortCode).eq("user_id",user.id).maybeSingle()]);
 if(cohortError||!cohort) return <main className="p-10"><h1 className="text-3xl font-bold">Kelas sedang disiapkan</h1><p className="mt-4">Ruang praktik belum dapat diakses. Silakan kembali setelah pengumuman pembukaan kelas.</p><Link href="/lexnusa/cohort" className="mt-5 inline-block underline">Kembali ke informasi kelas</Link></main>;
 if(!member)return <main className="mx-auto max-w-xl px-6 py-16"><h1 className="text-3xl font-bold">{cohort.title}</h1>{query.error&&<p role="alert">Pendaftaran belum berhasil. Silakan coba kembali.</p>}<p className="my-6">{cohort.enrollment_open?"Bergabung untuk menyimpan pekerjaan pribadi dan menerima umpan balik fasilitator.":"Pendaftaran belum dibuka. Peserta undangan akan diberi akses oleh pengelola kelas."}</p>{cohort.enrollment_open&&<form action={enroll}><button className="rounded-xl bg-teal-800 px-6 py-3 text-white">Gabung cohort</button></form>}</main>;
 const {data:versions,error}=await supabase.from("lexnusa_cohort_versions").select("*").eq("user_id",user.id).eq("cohort_code",cohortCode).order("created_at",{ascending:false});
 if(error) return <main className="p-10"><h1>Riwayat belum dapat dimuat</h1><p>Coba muat ulang sebelum melanjutkan agar pekerjaan sebelumnya tetap tersedia.</p></main>;
 const latest=versions?.[0];const {data:reviews}=await supabase.from("lexnusa_cohort_reviews").select("version_id,participant_score,decision,notes,created_at").eq("cohort_code",cohortCode).eq("participant_id",user.id).order("created_at",{ascending:false});
 return <main className="bg-stone-50 px-6 py-14 text-slate-900"><div className="mx-auto max-w-6xl"><Link href="/lexnusa/cohort" className="text-teal-800 underline">Informasi kelas</Link><p className="mt-8 text-sm font-bold uppercase tracking-widest text-teal-700">{cohortCode} · Ruang praktik pribadi</p><h1 className="mt-3 text-4xl font-bold">Kontrak kerja: dari kebutuhan ke revisi</h1>
 {query.saved&&<p role="status" className="mt-5 rounded-xl bg-emerald-100 p-4">Versi baru tersimpan. Versi sebelumnya tetap tersedia.</p>}{query.error&&<p role="alert" className="mt-5 rounded-xl bg-red-100 p-4">{query.error==="incomplete"?"Isi kelima tahap minimal 20 karakter untuk mengirim tugas. Maksimal 20.000 karakter per tahap.":"Penyimpanan belum berhasil. Silakan coba kembali."}</p>}
 <article className="my-8 rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Kasus LN-KK-01 · Selat Digital Nusantara</h2><p className="mt-3 leading-7">Perusahaan fiktif di Tanjungpinang merekrut Raka Pratama untuk digitalisasi 12.000 arsip lama. Estimasi 1 Oktober 2026–31 Maret 2027, upah pokok Rp6 juta + tunjangan tetap Rp1 juta, Senin–Jumat 08.00–17.00 dengan satu jam istirahat. Manajemen meminta masa percobaan, lembur termasuk upah, dan tanpa kompensasi akhir kontrak. Uji permintaan tersebut; jangan langsung menyetujuinya.</p><p className="mt-3 text-sm text-slate-600">Gunakan data simulasi. Klarifikasi sifat proyek, kewenangan penandatangan, upah minimum dan hak normatif bersama fasilitator.</p></article>
 <div className="mb-8 rounded-xl bg-amber-50 p-5">Ruang ini menyimpan proses dan hasil kerja. Generasi AI belum diaktifkan pada cohort ini; instruksi dan keluaran dari sesi praktik dapat dicatat di bawah. Skor LEX-EVAL tidak dihitung otomatis.</div>
 <form action={saveVersion} className="space-y-6">{stages.map((s,i)=><section key={`${s.key}-${latest?.id??'new'}`} className="rounded-2xl border bg-white p-6"><p className="text-sm font-bold text-teal-700">Minggu {s.week} · {i+1}/5</p><label htmlFor={s.key} className="mt-2 block text-2xl font-bold">{s.title}</label><p id={`${s.key}-help`} className="my-3 leading-7 text-slate-600">{s.help}</p><textarea id={s.key} name={s.key} aria-describedby={`${s.key}-help`} rows={8} maxLength={20000} defaultValue={latest?.[s.key]??""} className="w-full rounded-xl border border-slate-400 p-4"/></section>)}<div className="flex flex-wrap gap-4"><button name="intent" value="save" className="rounded-xl border bg-white px-6 py-4 font-bold">Simpan versi kerja</button><button name="intent" value="submit" className="rounded-xl bg-teal-800 px-6 py-4 font-bold text-white">Kirim untuk review fasilitator</button></div></form>
 <section className="mt-12 grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Riwayat versi</h2>{versions?.length?versions.map(v=><details key={v.id} className="mt-4 border-t pt-4"><summary className="cursor-pointer font-semibold">{new Date(v.created_at).toLocaleString("id-ID")} · {v.submitted?"Dikirim":"Versi kerja"}</summary>{stages.map(s=><div key={s.key} className="mt-3"><h3 className="font-bold">{s.title}</h3><p className="whitespace-pre-wrap break-words">{v[s.key]||"Belum diisi"}</p></div>)}</details>):<p className="mt-3">Belum ada versi tersimpan.</p>}</article><article className="rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">Umpan balik fasilitator</h2>{reviews?.length?reviews.map(r=><div key={`${r.version_id}-${r.created_at}`} className="mt-4 border-t pt-4"><p className="font-bold">{r.decision} · Nilai peserta {r.participant_score}/100</p><p className="text-xs">Versi {r.version_id}</p><p className="mt-2 whitespace-pre-wrap">{r.notes}</p></div>):<p className="mt-3">Belum ada review. Nilai peserta terpisah dari penilaian keluaran AI.</p>}<h3 className="mt-8 font-bold">Bobot LEX-EVAL</h3>{dimensions.map(([name,weight])=><p key={name} className="mt-2 flex justify-between gap-4"><span>{name}</span><b>{weight}</b></p>)}</article></section>
 </div></main>;
}
