import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {requireTreasurer} from '@/lib/persis/master-server';
import {loadReminderData} from '@/lib/persis/reminders-server';
import {REMINDER_BASE,reminderMonth,reminderState,FOLLOWUP,LOG_STATUS,type ReminderLog} from '@/lib/persis/reminders';
import {UUID} from '@/lib/persis/cash';
import {jakartaDate,rupiah,monthLabel} from '@/lib/persis/dues';
import TreasuryNav from '../../TreasuryNav';
import SubmitButton from '../../program/SubmitButton';
import MessageComposer from '../MessageComposer';
import {saveContact,confirmSent,addFollowup} from '../actions';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Tindak Lanjut Iuran Persis',robots:{index:false,follow:false}};
const field='rounded-lg border border-slate-300 bg-white p-3';
export default async function ReminderDetail({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{month?:string;page?:string;error?:string;success?:string}>}){
 const {id}=await params,{client}=await requireTreasurer(`${REMINDER_BASE}/${id}`);if(!UUID.test(id))notFound();
 const query=await searchParams,month=reminderMonth(query.month),today=jakartaDate(),data=await loadReminderData(client,id),member=data.members[0];if(!member)notFound();const state=reminderState(member,data.rates,data.payments,month,today),page=Math.max(1,Math.min(10000,parseInt(query.page||'1')||1));
 const {data:history,error}=await client.from('persis_reminders').select('*').eq('member_id',id).order('created_at',{ascending:false}).order('id').range((page-1)*20,page*20);
 return <div lang="id" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><main className="mx-auto max-w-5xl"><Link href={`${REMINDER_BASE}?month=${month}`} className="text-sm font-semibold text-emerald-800 underline">Kembali ke daftar pengingat</Link><h1 className="mt-6 text-3xl font-bold">{member.full_name}</h1><p className="mt-2 text-slate-600">{member.region} · iuran sampai {monthLabel(`${month}-01`)}</p><TreasuryNav/>
 {query.error&&<p role="alert" className="mb-5 rounded-lg bg-red-50 p-4 text-red-800">{query.error}</p>}{query.success&&<p role="status" className="mb-5 rounded-lg bg-emerald-100 p-4 text-emerald-900">{query.success==='sent'?'Konfirmasi pengiriman berhasil dicatat. Ini bukan bukti pesan diterima/dibaca.':'Data berhasil disimpan.'}</p>}
 <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Rincian kekurangan jatuh tempo</h2><p className="mt-2 text-2xl font-bold text-emerald-900">{rupiah(state.amount)}</p>{(!member.user_id||state.unknown)&&<p className="mt-3 text-amber-900">Angka belum lengkap/terkonfirmasi karena data akun atau ketentuan iuran belum siap.</p>}{state.pending>0&&<p className="mt-3 text-amber-900">Ada {rupiah(state.pending)} menunggu verifikasi (semua periode). Pengingat ditahan.</p>}
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-emerald-50"><tr>{['Bulan','Kewajiban','Terverifikasi','Kekurangan','Status'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{state.debt.map(b=><tr key={b.month} className="border-b"><td className="p-3">{monthLabel(b.month)}</td><td className="p-3 whitespace-nowrap">{rupiah(b.expected||0)}</td><td className="p-3 whitespace-nowrap">{rupiah(b.paid)}</td><td className="p-3 whitespace-nowrap">{rupiah(b.arrears)}</td><td className="p-3">{b.status}</td></tr>)}</tbody></table>{!state.debt.length&&<p className="p-4 text-slate-500">Tidak ada kekurangan jatuh tempo yang terhitung.</p>}</div><div className="mt-4 flex flex-wrap gap-5 text-sm"><Link className="text-emerald-800 underline" href="/persis-kepri/iuran/bendahara">Periksa pembayaran</Link><Link className="text-emerald-800 underline" href="/persis-kepri/iuran/bendahara/anggota">Perbaiki master anggota</Link></div></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Kontak WhatsApp anggota</h2><p className="mt-2 text-sm leading-6 text-slate-600">Isi nomor yang diberikan anggota dan cocokkan dengan identitasnya. Nomor dan catatan tindak lanjut hanya dapat diakses bendahara.</p><form action={saveContact} className="mt-4 grid gap-4"><input type="hidden" name="member_id" value={id}/><input type="hidden" name="month" value={month}/><input type="hidden" name="version" value={member.contact?.updated_at||''}/><label className="grid gap-2 text-sm font-semibold">Nomor WhatsApp<input type="tel" name="phone" maxLength={30} defaultValue={member.contact?.phone||''} placeholder="08… atau +628…" className={field}/></label><label className="flex gap-3 text-sm"><input type="checkbox" name="confirm" value="yes"/>Saya sudah memastikan nomor ini milik {member.full_name}.</label><label className="flex gap-3 text-sm"><input type="checkbox" name="paused" value="yes" defaultChecked={member.contact?.paused}/>Jeda pengingat untuk anggota ini</label><SubmitButton label="Simpan kontak & pengaturan"/></form></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Pesan pengingat personal</h2><MessageComposer key={`${id}-${month}-${member.contact?.updated_at||''}-${query.success||''}`} memberId={id} month={month} name={member.full_name} phone={member.contact?.phone||''} blocked={state.blocked}/></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Catat hasil tindak lanjut</h2><p className="mt-2 text-sm text-slate-600">Janji atau konfirmasi anggota tidak mengubah status lunas. Pembayaran tetap melalui verifikasi iuran.</p><form action={addFollowup} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="member_id" value={id}/><input type="hidden" name="month" value={month}/><label className="grid gap-2 text-sm font-semibold">Hasil<select name="status" className={field}>{Object.entries(FOLLOWUP).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="grid gap-2 text-sm font-semibold">Tindak lanjut berikutnya (opsional)<input type="date" name="next_followup" min={today} max="2100-12-31" className={field}/></label><label className="grid gap-2 text-sm font-semibold sm:col-span-2">Catatan<textarea name="note" required minLength={3} maxLength={1000} rows={3} className={field}/></label><SubmitButton label="Simpan catatan"/></form></section>
 <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-bold">Riwayat pengingat & tindak lanjut</h2>{error?<p className="mt-4 text-red-800">Riwayat belum dapat dimuat.</p>:<div className="mt-4 space-y-4">{((history||[]).slice(0,20) as ReminderLog[]).map(r=><article key={r.id} className="rounded-xl border border-slate-200 p-4"><p className="font-semibold">{LOG_STATUS[r.status]}</p><p className="mt-1 text-xs text-slate-500">Dicatat {new Date(r.created_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB{r.sent_at?` · Dikonfirmasi dikirim ${new Date(r.sent_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB`:''}</p>{r.note&&<p className="mt-2 whitespace-pre-wrap text-sm">{r.note}</p>}{r.next_followup&&<p className="mt-2 text-sm">Jadwal tindak lanjut: {r.next_followup}</p>}{r.message&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-emerald-800">Lihat pesan tersimpan · {rupiah(r.amount)}</summary><p className="mt-2 text-slate-500">Nomor saat disiapkan: +{r.phone}</p><p className="mt-2 whitespace-pre-wrap leading-6">{r.message}</p></details>}{r.status==='draft'&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-emerald-800">Sudah dikirim melalui WhatsApp?</summary><form action={confirmSent} className="mt-3 grid gap-3"><input type="hidden" name="member_id" value={id}/><input type="hidden" name="month" value={month}/><input type="hidden" name="draft_id" value={r.id}/><label className="flex gap-3"><input type="checkbox" name="confirm_sent" value="yes" required/>Saya sudah mengirim pesan ini.</label><SubmitButton label="Catat konfirmasi pengiriman"/></form></details>}</article>)}</div>}<nav className="mt-5 flex gap-5 text-sm" aria-label="Halaman riwayat">{page>1&&<Link className="underline" href={`${REMINDER_BASE}/${id}?month=${month}&page=${page-1}`}>Sebelumnya</Link>}{(history?.length||0)>20&&<Link className="underline" href={`${REMINDER_BASE}/${id}?month=${month}&page=${page+1}`}>Berikutnya</Link>}</nav></section>
 </main></div>;
}
