import {loadProgramOptions} from '@/lib/persis/program-server';
import type {ProgramOption} from '@/lib/persis/program';
import type {Metadata} from 'next';
import Link from 'next/link';
import {randomUUID} from 'node:crypto';
import {requireTreasurer} from '@/lib/persis/master-server';
import {loadCashReport} from '@/lib/persis/cash-server';
import {CASH_BASE,cashMonth,METHODS,type CashReport} from '@/lib/persis/cash';
import {jakartaDate,rupiah,monthLabel} from '@/lib/persis/dues';
import TreasuryNav from '../TreasuryNav';
import CashForm from './CashForm';
import {saveOpening,voidCashEntry} from './actions';
export const metadata:Metadata={title:'Buku Kas PW Persis Kepri',robots:{index:false,follow:false}};
export const dynamic='force-dynamic';
const input='rounded-lg border border-slate-300 bg-white p-3 text-base font-normal';
export default async function CashPage({searchParams}:{searchParams:Promise<{month?:string;page?:string;error?:string;success?:string}>}){
 const {client}=await requireTreasurer(CASH_BASE),params=await searchParams,month=cashMonth(params.month),today=jakartaDate();
 let report:CashReport|null=null,loadError='';
 try{report=await loadCashReport(client,month);}catch(e){loadError=e instanceof Error?e.message:'Laporan belum dapat dimuat.';}
 let programs:ProgramOption[]=[];let programsError='';
 try{programs=await loadProgramOptions(client);}catch(e){programsError=e instanceof Error?e.message:'Pilihan program belum dapat dimuat.';}
 const settings=report?.settings,tooEarly=!!settings&&month<settings.start_date.slice(0,7);
 const page=Math.min(Math.max(1,parseInt(params.page||'1')||1),Math.max(1,Math.ceil((report?.rows.length||0)/25)));
 const {data:audit,error:auditError}=await client.from('persis_cash_audit').select('action,before_data,after_data,created_at').eq('entity','persis_cash_settings').order('id',{ascending:false}).limit(10);
 return <div lang="id" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><main className="mx-auto max-w-6xl">
  <Link href="/persis-kepri/iuran" className="text-sm font-semibold text-emerald-800 underline">Kembali ke iuran anggota</Link>
  <p className="mt-6 text-sm font-bold uppercase tracking-widest text-emerald-800">Ruang bendahara · PW Persis Kepri</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Buku kas & laporan bulanan</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">Pantau penerimaan, penggunaan dana, dan saldo organisasi. Iuran terverifikasi masuk otomatis berdasarkan tanggal pembayaran, bukan bulan tagihan.</p><TreasuryNav/>
  {params.error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{params.error}</p>}
  {params.success&&<p role="status" className="mb-5 rounded-xl bg-emerald-100 p-4 text-emerald-950">{params.success==='void'?'Transaksi dibatalkan. Riwayat dan bukti tetap tersimpan.':params.success==='opening'?'Saldo awal berhasil disimpan.':'Transaksi dan bukti berhasil disimpan.'}</p>}
  {loadError?<p role="alert" className="rounded-xl bg-red-50 p-6 text-red-800">{loadError}</p>:<>
   <details open={!settings} className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><summary className="cursor-pointer font-bold text-emerald-900">{settings?`Saldo awal pembukuan · ${rupiah(settings.opening_balance)} · mulai ${settings.start_date}`:'Langkah pertama: tetapkan saldo awal buku kas'}</summary>
    <p className="mt-4 max-w-3xl text-sm leading-6 text-slate-600">Isi saldo kas dan bank organisasi tepat sebelum tanggal mulai. Seluruh iuran yang dibayar sebelum tanggal itu dianggap sudah tercakup dalam saldo awal dan tidak ditambahkan lagi. Tanggal mulai tidak dapat diubah setelah disimpan; nominal dapat dikoreksi dengan alasan.</p>
    <form action={saveOpening} className="mt-5 grid gap-4 sm:grid-cols-2"><input type="hidden" name="version" value={settings?.updated_at||''}/>
     <label className="grid gap-2 text-sm font-semibold">Tanggal mulai buku kas<input type="date" name="start_date" required min="2020-01-01" max={today} defaultValue={settings?.start_date||`${today.slice(0,7)}-01`} readOnly={!!settings} className={input}/></label>
     <label className="grid gap-2 text-sm font-semibold">Saldo awal (Rp)<input type="number" name="opening_balance" min="0" max="100000000000" step="1" required defaultValue={settings?.opening_balance} className={input}/></label>
     <label className="grid gap-2 text-sm font-semibold sm:col-span-2">{settings?'Alasan koreksi saldo awal':'Dasar penetapan saldo awal'}<textarea name="note" minLength={3} maxLength={500} required rows={2} placeholder="Contoh: Rekonsiliasi kas dan saldo rekening per akhir bulan sebelumnya" className={input}/></label>
     <button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white sm:col-span-2">{settings?'Simpan koreksi saldo awal':'Mulai buku kas'}</button>
    </form>
    {settings&&<div className="mt-5 border-t border-slate-200 pt-4 text-sm"><h2 className="font-bold">Riwayat saldo awal (10 terakhir)</h2>{auditError?<p className="mt-2 text-red-800">Riwayat belum dapat dimuat.</p>:<ul className="mt-3 space-y-2">{audit?.map((a,i)=><li key={i}>{new Date(a.created_at).toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB · {a.before_data?`${rupiah(Number(a.before_data.opening_balance))} → `:''}{rupiah(Number(a.after_data.opening_balance))} · {a.after_data.note}</li>)}</ul>}</div>}
   </details>
   {settings&&report&&<>
    <form className="my-6 flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm font-semibold">Bulan laporan<input type="month" name="month" defaultValue={month} min={settings.start_date.slice(0,7)} max="2100-12" required className={input}/></label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Tampilkan laporan</button></form>
    {tooEarly?<p role="alert" className="rounded-lg bg-amber-50 p-5 text-amber-900">Pembukuan dimulai {settings.start_date}. Pilih bulan mulai atau sesudahnya.</p>:<>
     <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Saldo awal bulan',report.opening],['Pemasukan bulan ini',report.income],['Pengeluaran bulan ini',report.expense],['Saldo akhir bulan',report.closing]].map(([title,value])=><div key={String(title)} className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">{title}</p><p className={`mt-2 text-2xl font-bold ${Number(value)<0?'text-red-700':'text-emerald-900'}`}>{rupiah(Number(value))}</p></div>)}</div>
     {report.closing<0&&<p role="alert" className="mt-4 rounded-lg bg-amber-50 p-4 text-amber-900">Saldo tercatat negatif. Periksa kelengkapan pemasukan, saldo awal, dan pengeluaran terhadap kas/rekening.</p>}
     <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold">Laporan {monthLabel(`${month}-01`)}</h2><p className="mt-1 text-sm text-slate-600">{report.rows.length} transaksi aktif · saldo gabungan kas dan bank</p></div><div className="flex flex-wrap gap-2"><a href={`/api/persis/cash/export?month=${month}&format=xlsx`} className="rounded-lg border border-emerald-700 px-4 py-2 text-sm font-bold text-emerald-900">Unduh Excel</a><a href={`/api/persis/cash/export?month=${month}&format=pdf`} className="rounded-lg bg-emerald-800 px-4 py-2 text-sm font-bold text-white">Unduh PDF</a></div></div>
      <p className="mt-4 text-sm leading-6 text-slate-600">Hanya iuran terverifikasi dan transaksi aktif yang dihitung. Pembatalan atau verifikasi terlambat memperbarui laporan bulan terkait. Saldo awal bulan membawa saldo bulan sebelumnya secara otomatis.</p>
      {!report.rows.length?<p className="mt-6 rounded-lg bg-slate-50 p-5 text-slate-600">Belum ada transaksi aktif pada bulan ini.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-emerald-50 text-emerald-950"><tr>{['Tanggal / ref.','Uraian','Masuk','Keluar','Saldo','Bukti / koreksi'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{report.rows.slice((page-1)*25,page*25).map(r=><tr key={`${r.source}-${r.id}`} className="border-b border-slate-100 align-top"><td className="p-3 whitespace-nowrap">{r.transacted_on}<span className="mt-1 block text-xs text-slate-500">{r.source==='dues'?'IUR':'KAS'}-{r.id.slice(0,8)}</span></td><td className="max-w-sm p-3"><p className="font-semibold">{r.party}</p><p className="mt-1 whitespace-pre-wrap break-words">{r.description}</p>{r.program_id&&<Link href={`/persis-kepri/iuran/bendahara/program/${r.program_id}`} className="mt-1 block text-xs font-semibold text-emerald-800 underline">Program: {r.program_title}</Link>}<p className="mt-1 text-xs text-slate-500">{r.category} · {METHODS[r.method]}{r.activity?` · ${r.activity}`:''}</p></td><td className="p-3 whitespace-nowrap">{r.kind==='income'?rupiah(r.amount):'—'}</td><td className="p-3 whitespace-nowrap">{r.kind==='expense'?rupiah(r.amount):'—'}</td><td className="p-3 whitespace-nowrap font-semibold">{rupiah(r.balance)}</td><td className="min-w-44 p-3"><a href={`/api/persis/${r.source==='dues'?'dues':'cash'}/${r.id}/receipt`} className="font-semibold text-emerald-800 underline">Unduh bukti</a>{r.source==='manual'&&<details className="mt-3"><summary className="cursor-pointer text-red-800">Batalkan</summary><form action={voidCashEntry} className="mt-3 grid gap-3"><input type="hidden" name="id" value={r.id}/><input type="hidden" name="month" value={month}/><label className="grid gap-1">Alasan pembatalan<textarea name="reason" minLength={3} maxLength={500} required rows={3} className="rounded border p-2"/></label><label className="flex gap-2"><input type="checkbox" name="confirm" value="yes" required/>Saya membatalkan transaksi ini</label><button className="rounded bg-red-700 p-2 font-semibold text-white">Simpan pembatalan</button></form></details>}</td></tr>)}</tbody></table></div>}
      {report.rows.length>25&&<div className="mt-4 flex items-center gap-5 text-sm">{page>1&&<Link href={`${CASH_BASE}?month=${month}&page=${page-1}`} className="underline">Sebelumnya</Link>}<span>Halaman {page} / {Math.ceil(report.rows.length/25)}</span>{page*25<report.rows.length&&<Link href={`${CASH_BASE}?month=${month}&page=${page+1}`} className="underline">Berikutnya</Link>}</div>}
      {!!report.voided.length&&<details className="mt-6 border-t pt-4"><summary className="cursor-pointer font-semibold">Transaksi dibatalkan ({report.voided.length}) — tidak masuk saldo</summary><ul className="mt-4 space-y-4">{report.voided.map(r=><li key={r.id} className="rounded-lg bg-slate-50 p-4 text-sm"><p>{r.transacted_on} · {r.party} · {rupiah(r.amount)} · {r.description}</p><p className="mt-1 text-red-800">Alasan: {r.void_reason}</p><a href={`/api/persis/cash/${r.id}/receipt`} className="mt-2 inline-block text-emerald-800 underline">Bukti tetap tersedia</a></li>)}</ul></details>}
     </section>
    </>}
    <section className="mt-6 max-w-3xl rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold">Catat transaksi baru</h2><p className="mt-2 text-sm leading-6 text-slate-600">Untuk infak, donasi, bantuan, dan pengeluaran organisasi. Pembayaran iuran dicatat melalui menu iuran agar tidak dihitung dua kali.</p><div className="mt-3"><Link href="/persis-kepri/iuran/bendahara/program" className="text-sm font-semibold text-emerald-800 underline">Kelola program dan anggaran</Link></div>{programsError?<p role="alert" className="mt-4 text-red-800">{programsError}</p>:<CashForm id={randomUUID()} today={today} startDate={settings.start_date} programs={programs}/>}</section>
   </>}
  </>}
 </main></div>;
}
