import Link from "next/link";
import { requireRahiAdmin } from "../../admin";
import { reviewPortfolio } from "./actions";

const rubric=[['Pemahaman konsep Raja Ali Haji',20],['Kedalaman analisis',20],['Penggunaan evidence / sumber',15],['Penerapan pada problem kontemporer',20],['Argumentasi & komunikasi',15],['Originalitas & refleksi',10]] as const;
type Project={id:string;user_id:string;track:string;title:string;problem_statement:string;visibility:string;status:string;profiles:{full_name:string;institution:string|null}|null};
type Version={id:string;project_id:string;version_number:number;artifact_url:string|null;narrative:string;evidence:unknown;submitted_at:string};

export default async function PortfolioReviewQueue({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
 const query=await searchParams;const {admin}=await requireRahiAdmin("/raja-ali-haji/admin/pilot-01/portfolio");
 const {data:rows}=await admin.from("rahi_portfolio_projects").select("id,user_id,track,title,problem_statement,visibility,status,profiles!rahi_portfolio_projects_user_id_fkey(full_name,institution)").eq("cohort_code","RAHI-PILOT-01").in("status",["submitted","revision_requested","verified"]).order("updated_at",{ascending:false});
 const projects=(rows||[]) as unknown as Project[];const ids=projects.map(p=>p.id);
 const {data:versionRows}=ids.length?await admin.from("rahi_portfolio_versions").select("id,project_id,version_number,artifact_url,narrative,evidence,submitted_at").in("project_id",ids).order("version_number",{ascending:false}):{data:[]};
 const versions=(versionRows||[]) as Version[];
 return <main className="min-h-screen bg-[#f3f0e9] px-5 py-12 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/raja-ali-haji/admin/pilot-01" className="font-bold text-amber-800">← Dashboard cohort</Link><p className="mt-8 text-xs font-bold uppercase tracking-[.24em] text-amber-700">Restricted · Human decision control</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Portfolio Review Queue</h1><p className="mt-4 max-w-3xl text-slate-600">Reviewer manusia menilai versi submission terbaru. AI boleh memberi advisory terpisah, tetapi tidak memiliki jalur untuk menetapkan VERIFIED.</p>{query.saved&&<p className="mt-6 border border-emerald-300 bg-emerald-50 p-4 font-bold text-emerald-800">Review tersimpan.</p>}{query.error&&<p className="mt-6 border border-red-300 bg-red-50 p-4 text-red-800">{query.error}</p>}
 <div className="mt-8 space-y-7">{projects.length===0?<div className="rounded-2xl border bg-white p-8 text-slate-500">Belum ada portfolio dalam antrean review.</div>:projects.map(p=>{const latest=versions.filter(v=>v.project_id===p.id).sort((a,b)=>b.version_number-a.version_number)[0];return <article key={p.id} className="rounded-2xl border border-stone-300 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-700">{p.track} · {p.status}</p><h2 className="mt-2 text-2xl font-black">{p.title}</h2><p className="mt-2 text-slate-600">{p.profiles?.full_name||p.user_id}{p.profiles?.institution?` · ${p.profiles.institution}`:""}</p></div><Link className="font-bold text-amber-800" href={`/raja-ali-haji/admin/pilot-01/${p.user_id}`}>Participant case file →</Link></div><p className="mt-5 leading-7">{p.problem_statement||"Problem statement belum diisi."}</p>{latest?<><div className="mt-5 rounded-xl bg-stone-50 p-5"><div className="flex flex-wrap justify-between gap-3"><b>Submission v{latest.version_number}</b><span className="text-sm text-stone-500">{new Date(latest.submitted_at).toLocaleString("id-ID")}</span></div><p className="mt-4 whitespace-pre-wrap leading-7">{latest.narrative}</p>{latest.artifact_url&&<a href={latest.artifact_url} target="_blank" rel="noreferrer" className="mt-4 inline-block font-bold text-amber-800">Buka artifact ↗</a>}</div><form action={reviewPortfolio} className="mt-6 border-t pt-6"><input type="hidden" name="projectId" value={p.id}/><input type="hidden" name="versionId" value={latest.id}/><input type="hidden" name="participantId" value={p.user_id}/><div className="grid gap-4 md:grid-cols-2">{rubric.map(([label,max],i)=><label key={label} className="font-bold">{label} <span className="text-stone-500">/ {max}</span><input name={`score${i+1}`} type="number" min={0} max={max} required className="mt-2 w-full border p-3 font-normal"/></label>)}</div><label className="mt-5 block font-bold">Reviewer notes<textarea name="notes" rows={5} maxLength={6000} className="mt-2 w-full border p-3 font-normal"/></label><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="font-bold">Decision<select name="decision" defaultValue="revision_requested" className="mt-2 w-full border p-3 font-normal"><option value="revision_requested">Request revision</option><option value="verified">Verified (minimum 60)</option></select></label><label className="flex items-center gap-3 self-end border p-3 font-bold"><input name="showcaseApproved" type="checkbox"/> Approve public showcase (hanya efektif bila visibility Public + Verified)</label></div><button className="mt-5 bg-slate-950 px-6 py-4 font-black text-white">Record Human Decision</button></form></>:<p className="mt-5 rounded-xl bg-amber-50 p-4">Project belum memiliki submission version.</p>}</article>})}</div></div></main>;
}
