"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-6-v1";
const SOURCE_URL = "https://www.researchgate.net/publication/343449910_Asas-Asas_Umum_Pemerintahan_yang_Baik_dalam_Pemikiran_Raja_Ali_Haji";

const nav = [
  ["introduction", "Pengantar"], ["reading", "Bacaan utama"], ["analysis", "Kerangka musyawarah"],
  ["podcast", "Podcast"], ["reflection", "Refleksi"], ["essay", "Esai"], ["quiz", "Kuis"], ["result", "Hasil"],
];

const readings = [
  { n:"I", title:"Risalah tentang tertib tugas seorang raja", text:<><p><em>Muqaddimah fi Intizam Waza’if al-Malik</em> merupakan risalah politik Raja Ali Haji tentang kewajiban pemegang kekuasaan dalam mengurus negeri. Judulnya menunjuk pada pengantar mengenai penertiban tugas-tugas seorang raja.</p><p>Risalah ini ringkas, tetapi arah pemikirannya tegas: pemerintahan tidak boleh bergantung pada kehendak sesaat. Kekuasaan perlu ditata melalui perhatian kepada rakyat, kehati-hatian menerima pengaduan, pertimbangan bersama, dan perlakuan yang tidak membeda-bedakan.</p></>, idea:"Tertib pemerintahan dimulai ketika kekuasaan memahami tugas dan batasnya." },
  { n:"II", title:"Tiga wazifah sebagai disiplin kekuasaan", text:<><p>Karya ini dikenal memuat tiga <em>wazifah</em> atau kewajiban pokok. Pertama, penguasa perlu menjaga hubungan dan kepercayaan rakyat. Kedua, ia harus cermat ketika menerima aduan. Ketiga, pertolongan dan perlakuan kepada rakyat tidak boleh ditentukan oleh kesukaan pribadi.</p><p>Ketiganya membentuk satu alur: dengarkan keadaan rakyat, periksa informasi sebelum bertindak, lalu berikan respons yang patut. Pemerintahan yang baik bukan hanya cepat mengambil keputusan, tetapi benar dalam mengetahui masalah dan adil dalam menanganinya.</p></>, idea:"Mendengar, memeriksa, dan bertindak adil adalah rangkaian tanggung jawab." },
  { n:"III", title:"Musyawarah bukan sekadar berkumpul", text:<><p>Musyawarah adalah proses memperluas pertimbangan sebelum keputusan diambil. Ia memungkinkan pemimpin mengetahui fakta yang tidak dilihatnya, mendengar keberatan, membandingkan pilihan, dan menilai akibat bagi kelompok yang berbeda.</p><p>Musyawarah tidak terpenuhi hanya karena rapat pernah diadakan. Peserta harus memperoleh informasi yang cukup, dapat berbicara tanpa takut, dan mengetahui bagaimana masukannya digunakan. Keputusan akhir harus memiliki alasan, penanggung jawab, serta tindak lanjut.</p></>, idea:"Musyawarah yang bermakna memperbaiki pengetahuan dan alasan keputusan." },
  { n:"IV", title:"Menjaga diri dari adu-aduan", text:<><p>Raja Ali Haji mengingatkan bahaya menerima pengaduan tanpa pemeriksaan. Sebuah laporan dapat lahir dari kepedulian yang benar, tetapi dapat pula didorong kepentingan, iri hati, atau upaya menjatuhkan pihak lain. Pejabat tidak boleh menolak semua aduan, tetapi juga tidak boleh langsung menghukum berdasarkan satu cerita.</p><p>Kecermatan memerlukan pemisahan antara pelapor, fakta, bukti, tafsir, dan kepentingan. Pihak yang dilaporkan perlu didengar secara wajar. Kerahasiaan, perlindungan pelapor, dan larangan pembalasan harus diseimbangkan dengan pemeriksaan yang adil.</p></>, idea:"Pengaduan harus membuka pemeriksaan, bukan otomatis menjadi vonis." },
  { n:"V", title:"Tanggung jawab bersama tanpa mengaburkan penanggung jawab", text:<><p>Pemerintahan membutuhkan raja, penasihat, pembesar, pelaksana, dan masyarakat. Keputusan yang baik lahir dari kerja bersama, tetapi kerja bersama tidak berarti semua orang dapat saling melempar kesalahan.</p><p>Setiap tahap harus memiliki pemilik tanggung jawab: siapa menyediakan data, siapa memberi pertimbangan, siapa memutuskan, siapa menjalankan, dan siapa mengawasi. Pemimpin tidak dapat menyalahkan bawahan untuk keputusan yang disetujuinya; bawahan juga tidak bebas melakukan pelanggaran hanya karena diperintah.</p></>, idea:"Tanggung jawab dapat dibagi, tetapi tidak boleh dibuat hilang." },
  { n:"VI", title:"Ketidakberpihakan dan kepentingan umum", text:<><p>Perhatian kepada rakyat menuntut penguasa tidak membeda-bedakan berdasarkan kedekatan, asal, kekayaan, atau kemampuan memberi balasan. Bantuan dapat berbeda sesuai kebutuhan, tetapi ukuran perbedaannya harus dapat dijelaskan secara umum.</p><p>Ketidakberpihakan bukan berarti pejabat tidak memiliki nilai. Ia berarti keputusan didasarkan pada tujuan jabatan, fakta yang relevan, dan ukuran yang konsisten. Konflik kepentingan harus dinyatakan, dan pejabat perlu mengundurkan diri dari keputusan ketika kepentingan pribadinya mengganggu penilaian.</p></>, idea:"Adil tidak selalu berarti sama, tetapi perbedaan perlakuan memerlukan alasan yang sah." },
  { n:"VII", title:"Dari mufakat menuju tindakan dan evaluasi", text:<><p>Musyawarah kehilangan arti jika berhenti pada percakapan. Hasilnya perlu diterjemahkan menjadi keputusan, pembagian tugas, tenggat, sumber daya, serta ukuran keberhasilan. Setelah dilaksanakan, dampaknya harus dievaluasi dan kekeliruan diperbaiki.</p><p>Dalam sekolah, kampus, organisasi, atau pemerintahan modern, siklusnya dapat dirumuskan: masalah bersama, informasi yang dapat diperiksa, suara yang relevan, alasan keputusan, pelaksanaan yang jelas, dan evaluasi terbuka. Inilah cara tanggung jawab bersama menghasilkan tindakan, bukan kebuntuan.</p></>, idea:"Musyawarah selesai ketika keputusan dapat dilaksanakan, dinilai, dan dikoreksi." },
];

const questions = [
  { q:"Muqaddimah fi Intizam Waza’if al-Malik terutama membahas…", o:["Teknik pelayaran","Penertiban tugas pemegang kekuasaan","Kamus bahasa","Hukum dagang kolonial"], a:1 },
  { q:"Tiga wazifah dapat diringkas sebagai…", o:["Mendengar rakyat, mencermati aduan, dan bertindak adil","Memperluas istana, pajak, dan tentara","Menulis, membaca, dan berpidato","Memerintah, menghukum, dan menutup kritik"], a:0 },
  { q:"Musyawarah yang bermakna memerlukan…", o:["Rapat tanpa informasi","Informasi, ruang bicara, alasan keputusan, dan tindak lanjut","Persetujuan kepada pemimpin sejak awal","Keputusan tanpa penanggung jawab"], a:1 },
  { q:"Pengaduan yang diterima pejabat seharusnya…", o:["Langsung menjadi vonis","Membuka pemeriksaan yang cermat dan adil","Selalu diabaikan","Disebarkan kepada publik"], a:1 },
  { q:"Tanggung jawab bersama berarti…", o:["Tidak seorang pun bertanggung jawab","Peran dibagi tetapi penanggung jawab tiap tahap tetap jelas","Semua keputusan dibuat satu orang","Bawahan selalu menanggung kesalahan"], a:1 },
  { q:"Ketidakberpihakan berarti keputusan didasarkan pada…", o:["Kedekatan pribadi","Tujuan jabatan, fakta relevan, dan ukuran konsisten","Kemampuan memberi hadiah","Desakan kelompok terkuat"], a:1 },
  { q:"Konflik kepentingan perlu…", o:["Disembunyikan","Dinyatakan dan dikelola, termasuk mengundurkan diri dari keputusan bila perlu","Dianggap biasa","Diserahkan kepada keluarga"], a:1 },
  { q:"Musyawarah tidak cukup hanya berupa…", o:["Pertukaran alasan","Rapat yang tidak memengaruhi keputusan","Pemeriksaan fakta","Evaluasi hasil"], a:1 },
  { q:"Setelah mufakat, langkah yang diperlukan ialah…", o:["Menutup catatan","Menetapkan tugas, tenggat, pelaksanaan, dan evaluasi","Mengulang rapat tanpa tindakan","Menghapus penanggung jawab"], a:1 },
  { q:"Cara tepat membaca risalah ini untuk masa kini adalah…", o:["Menyalin bentuk kerajaan secara harfiah","Mengembangkan prinsipnya dalam lembaga modern secara kontekstual","Menghapus konteks sejarah","Menganggap semua keputusan lama selalu berlaku"], a:1 },
];

export default function ModuleSixLearning() {
  const [active, setActive] = useState("introduction");
  const [reflection, setReflection] = useState("");
  const [essay, setEssay] = useState("");
  const [answers, setAnswers] = useState<AnswerMap>({});
  const [score, setScore] = useState<number | null>(null);
  const [readingDone, setReadingDone] = useState(false);
  const [analysisDone, setAnalysisDone] = useState(false);
  const [podcastDone, setPodcastDone] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const d = JSON.parse(raw); setReflection(d.reflection ?? ""); setEssay(d.essay ?? ""); setAnswers(d.answers ?? {}); setScore(d.score ?? null); setReadingDone(Boolean(d.readingDone)); setAnalysisDone(Boolean(d.analysisDone)); setPodcastDone(Boolean(d.podcastDone)); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; const id = window.setTimeout(() => { void saveModuleProgress(STORAGE_KEY, 6, { reflection, essay, answers, score, readingDone, analysisDone, podcastDone }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200); }); }, 500); return () => window.clearTimeout(id); }, [reflection, essay, answers, score, readingDone, analysisDone, podcastDone, hydrated]);

  const reflectionWords = useMemo(() => countWords(reflection), [reflection]);
  const essayWords = useMemo(() => countWords(essay), [essay]);
  const reflectionDone = reflectionWords >= 100;
  const essayDone = essayWords >= 500;
  const quizDone = score !== null && score >= 70;
  const done = [readingDone, analysisDone, podcastDone, reflectionDone, essayDone, quizDone];
  const progress = Math.round(done.filter(Boolean).length / 6 * 100);
  const complete = done.every(Boolean);

  function submit() { if (Object.keys(answers).length < questions.length) { alert("Jawab seluruh pertanyaan terlebih dahulu."); return; } setScore(questions.filter((q, i) => Number(answers[i]) === q.a).length * 10); setActive("result"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <main className="min-h-screen bg-[#f7f4ee] text-slate-950">
    <header className="border-b border-white/10 bg-[#070916] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-400"><ArrowLeft size={17}/> Kembali ke program</Link><div className="min-w-56"><div className="flex justify-between text-xs"><span>Progres Modul 6</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${progress}%` }}/></div></div></div></header>
    <section className="bg-[#070916] px-5 pb-14 pt-10 text-white sm:px-8 md:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 6 dari 8</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Musyawarah dan Tanggung Jawab Bersama</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Membaca Muqaddimah fi Intizam Waza’if al-Malik tentang musyawarah, kecermatan menerima aduan, dan tanggung jawab bersama.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 120–150 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Tingkat dasar</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai, dan kuis</span></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id, label], i) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active === id ? "bg-slate-950 text-white" : "hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i + 1).padStart(2, "0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved ? "Tersimpan otomatis ✓" : "Progres tersimpan di perangkat ini"}</div></aside>
      <div className="min-w-0">
        {active === "introduction" && <Panel eyebrow="Mulai di sini" title="Pengantar Modul 6"><p>Setelah mempelajari amanah pejabat dalam Modul 5, Modul 6 beralih kepada cara keputusan bersama dibentuk. <em>Muqaddimah fi Intizam Waza’if al-Malik</em> mengajarkan perhatian kepada rakyat, kecermatan terhadap aduan, musyawarah, dan perlakuan yang adil.</p><h3>Tujuan pembelajaran</h3><ol><li>Menjelaskan konteks dan tiga kewajiban pokok dalam <em>Muqaddimah fi Intizam Waza’if al-Malik</em>.</li><li>Menganalisis musyawarah sebagai proses memperbaiki pengetahuan dan keputusan.</li><li>Menerapkan kecermatan dalam menerima pengaduan dan mengelola konflik kepentingan.</li><li>Merancang tanggung jawab bersama tanpa mengaburkan penanggung jawab.</li></ol><blockquote>Jika semua orang ikut bermusyawarah tetapi tidak seorang pun bertanggung jawab atas hasilnya, apakah keputusan itu benar-benar keputusan bersama?</blockquote><Next onClick={() => setActive("reading")}>Mulai membaca</Next></Panel>}
        {active === "reading" && <Panel eyebrow="Bacaan utama • 35–45 menit" title="Dari musyawarah menuju tindakan bersama"><p>Tujuh bagian bacaan berikut membaca risalah Raja Ali Haji secara kontekstual. Bentuk kerajaan tidak disalin secara harfiah; prinsip perhatian kepada rakyat, kecermatan, musyawarah, ketidakberpihakan, dan tindak lanjutnya yang dikembangkan.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Baca kajian pendukung</p><p className="mt-2 text-sm leading-6 text-slate-600">Kajian hukum administrasi menemukan prinsip musyawarah, kecermatan, keadilan, ketidakberpihakan, profesionalitas, akuntabilitas, kepastian hukum, kepentingan umum, dan larangan mencampuradukkan kewenangan dalam karya politik Raja Ali Haji.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka kajian asas pemerintahan yang baik <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e => setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 6.</label><Next onClick={() => setActive("analysis")}>Lanjut ke kerangka musyawarah</Next></Panel>}
        {active === "analysis" && <Panel eyebrow="Analisis konseptual" title="Siklus musyawarah yang bertanggung jawab"><div className="grid gap-4 md:grid-cols-3"><Concept n="01" title="Dengar" text="Masalah dan pengalaman pihak yang terdampak harus masuk ke dalam pertimbangan."/><Concept n="02" title="Timbang" text="Fakta, pilihan, keberatan, kepentingan, dan akibat diperiksa secara terbuka."/><Concept n="03" title="Kerjakan" text="Keputusan memiliki alasan, penanggung jawab, tindak lanjut, evaluasi, dan koreksi."/></div><h3>Dari suara menuju pertimbangan</h3><p>Musyawarah bukan pengumpulan pendapat tanpa arah. Informasi harus dapat diperiksa, pihak yang terdampak memperoleh ruang bicara, dan keberatan dijawab dengan alasan.</p><h3>Dari pertimbangan menuju keputusan</h3><p>Tidak semua musyawarah menghasilkan kesepakatan penuh. Ketika keputusan harus dibuat, pihak yang berwenang wajib menjelaskan pilihan, dasar, tujuan, dan cara melindungi pihak yang berbeda pendapat.</p><h3>Dari keputusan menuju evaluasi</h3><p>Tanggung jawab bersama menjadi nyata ketika tugas, tenggat, sumber daya, ukuran keberhasilan, dan jalur koreksi ditetapkan. Mufakat tanpa pelaksanaan hanya menghasilkan harapan.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e => setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami hubungan mendengar, menimbang, memutuskan, melaksanakan, dan mengevaluasi.</label><Next onClick={() => setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
        {active === "podcast" && <Panel eyebrow="Podcast • 15 menit" title="Algoritma Raja Ali Haji Lawan Kekacauan Digital"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Algoritma Raja Ali Haji Lawan Kekacauan Digital</p><p className="mt-1 text-sm text-slate-400">Audio Overview • Bahasa Indonesia • 15:27</p></div></div><audio className="mt-7 w-full" controls preload="metadata" onEnded={() => setPodcastDone(true)}><source src="/audio/algoritma-raja-ali-haji-lawan-kekacauan-digital.m4a" type="audio/mp4"/>Peramban Anda tidak mendukung pemutar audio.</audio></div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan podcast</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p><em>Muqaddimah fi Intizam Waza’if al-Malik</em> menghubungkan perhatian kepada rakyat, kecermatan menerima aduan, dan perlakuan yang adil. Musyawarah dipahami sebagai cara memperbaiki pertimbangan, bukan sekadar menyelenggarakan rapat.</p><p>Dalam konteks modern, tanggung jawab bersama memerlukan informasi yang dapat diperiksa, ruang bicara yang aman, alasan keputusan, penanggung jawab pelaksanaan, evaluasi hasil, dan mekanisme koreksi. Prinsip ini membantu menghadapi arus informasi serta kekacauan keputusan di ruang digital.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e => setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mendengarkan podcast ini sampai selesai.</label><Next disabled={!podcastDone} onClick={() => setActive("reflection")}>Lanjut ke refleksi</Next></Panel>}
        {active === "reflection" && <Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi tentang musyawarah"><p>Ingat satu rapat atau pengambilan keputusan bersama yang pernah Anda ikuti. Jelaskan siapa yang didengar, informasi apa yang digunakan, siapa yang memutuskan, dan bagaimana hasilnya ditindaklanjuti.</p><textarea value={reflection} onChange={e => setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={() => setActive("essay")}>Simpan dan lanjut ke esai</Next></Panel>}
        {active === "essay" && <Panel eyebrow="Penilaian • 500–700 kata" title="Tugas esai Modul 6"><blockquote>Jelaskan bagaimana prinsip musyawarah dalam <em>Muqaddimah fi Intizam Waza’if al-Malik</em> dapat dikembangkan menjadi pengambilan keputusan bersama yang bertanggung jawab pada masa kini.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan sedikitnya tiga bagian bacaan Modul 6.</li><li>Bahas perhatian kepada rakyat, kecermatan terhadap aduan, dan ketidakberpihakan.</li><li>Jelaskan hubungan partisipasi, alasan keputusan, pelaksanaan, dan evaluasi.</li><li>Gunakan satu contoh sekolah, kampus, organisasi, atau pelayanan publik kontemporer.</li></ul><textarea value={essay} onChange={e => setEssay(e.target.value)} rows={22} placeholder="Mulai menulis esai…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={500} max={700}/><Next disabled={!essayDone} onClick={() => setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
        {active === "quiz" && <Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 6"><div className="space-y-8">{questions.map((q, i) => <fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i + 1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o, j) => <label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i]) === j ? "border-amber-600 bg-amber-50" : "border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q6-${i}`} checked={Number(answers[i]) === j} value={j} onChange={e => setAnswers({ ...answers, [i]: e.target.value })} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
        {active === "result" && <Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 6"><div className={`border p-7 ${complete ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score ?? 0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone ? "Kuis lulus." : "Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan utama selesai"/><Req done={analysisDone} text="Kerangka musyawarah selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai minimal 500 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete ? <div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 6 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menyelesaikan pembelajaran musyawarah, kecermatan menerima aduan, ketidakberpihakan, pelaksanaan, dan tanggung jawab bersama dalam <em>Muqaddimah fi Intizam Waza’if al-Malik</em>.</p></div> : <button onClick={() => { setAnswers({}); setScore(null); setActive("quiz"); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
      </div>
    </div>
  </main>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>; }
function Next({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>; }
function Words({ count, min, max }: { count: number; min: number; max: number }) { return <p className={`text-sm font-semibold ${count >= min ? "text-emerald-700" : "text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count >= min ? "✓" : ""}</p>; }
function Req({ done, text }: { done: boolean; text: string }) { return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done ? "text-emerald-600" : "text-stone-300"} size={21}/><span className={done ? "font-semibold" : "text-slate-500"}>{text}</span></div>; }
function Concept({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+/).length : 0; }
function ReadingAccordion() { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section, i) => <article key={section.n}><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open === i ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>{open === i && <div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>}</article>)}</div>; }
