import {toggleEnrollment,review} from "./actions";
import {staffSession} from "@/lib/lexnusa/cohort-access";
import {cohortCode,stages} from "@/lib/lexnusa/cohort";
export const metadata={title:"Fasilitator | LexNusa Cohort",robots:{index:false,follow:false}};
export default async function Page({searchParams}:{searchParams:Promise<{error?:string;saved?:string}>}){
 const query=await searchParams;const {supabase}=await staffSession();
 const [{data:cohort},{data:members},{data:versions,error},{data:reviews}]=await Promise.all([
 supabase.from("lexnusa_cohorts").select("enrollment_open").eq("code",cohortCode).single(),
 supabase.from("lexnusa_cohort_members").select("user_id").eq("cohort_code",cohortCode),
 supabase.from("lexnusa_cohort_versions").select("*").eq("cohort_code",cohortCode).order("created_at",{ascending:false}),
 supabase.from("lexnusa_cohort_reviews").select("version_id,decision,participant_score,notes,created_at").eq("cohort_code",cohortCode).order("created_at",{ascending:false})]);
 return <main className="mx-auto max-w-6xl px-6 py-16"><h1 className="text-4xl font-bold">Fasilitator LexNusa Cohort</h1><p className="mt-3">{members?.length??0} peserta · {versions?.filter(v=>v.submitted).length??0} versi dikirim</p>{query.saved&&<p role="status" className="my-4 bg-emerald-50 p-4">Perubahan tersimpan.</p>}{(query.error||error)&&<p role="alert" className="my-4 bg-red-50 p-4">Proses belum berhasil. Verifikasi membutuhkan nilai minimal 75; Anda tidak dapat menilai pekerjaan sendiri.</p>}
 <form action={toggleEnrollment} className="my-8"><input type="hidden" name="open" value={String(!cohort?.enrollment_open)}/><button className="rounded-xl bg-teal-800 px-6 py-3 text-white">{cohort?.enrollment_open?"Tutup pendaftaran":"Buka pendaftaran"}</button></form>
 <p className="mb-8">Review menilai versi tertentu. Versi baru memerlukan review baru. Skor peserta bukan skor LEX-EVAL; verifikasi tidak menerbitkan sertifikat otomatis.</p>
 <section className="mb-8 rounded-xl border p-5"><h2 className="text-xl font-bold">Progres peserta</h2>{members?.map(m=>{const latest=versions?.find(v=>v.user_id===m.user_id);return <p className="mt-3 break-all" key={m.user_id}>Peserta {m.user_id}: {latest?stages.filter(s=>latest[s.key]?.trim().length>=20).length:0}/5 tahap terisi</p>;})}</section>
 {versions?.filter(v=>v.submitted).map(v=><article key={v.id} className="mb-8 rounded-2xl border bg-stone-50 p-6"><h2 className="break-all font-bold">Peserta {v.user_id}</h2><p className="text-sm">{new Date(v.created_at).toLocaleString("id-ID")}</p>{stages.map(s=><details key={s.key} className="mt-4"><summary className="cursor-pointer font-bold">{s.title}</summary><p className="mt-2 whitespace-pre-wrap break-words">{v[s.key]}</p></details>)}{reviews?.filter(r=>r.version_id===v.id).map(r=><p key={r.created_at} className="my-4 rounded-lg bg-white p-4">{r.decision} · {r.participant_score}/100 · {r.notes}</p>)}<form action={review} className="mt-6 grid gap-4"><input type="hidden" name="version" value={v.id}/><label>Nilai kemampuan peserta (0–100)<input required name="score" type="number" min="0" max="100" className="ml-4 w-24 border bg-white p-2"/></label><label>Keputusan<select name="decision" className="ml-4 border bg-white p-2"><option value="revision_requested">Perlu revisi</option><option value="verified">Terverifikasi</option></select></label><label>Umpan balik dan alasan keputusan<textarea required name="notes" minLength={20} maxLength={10000} rows={4} className="mt-2 w-full border bg-white p-3"/></label><button className="rounded-xl bg-slate-900 px-6 py-3 text-white">Simpan review versi ini</button></form></article>)}
 </main>;
}
