import { createClient } from "@supabase/supabase-js";
import { certificateEligible, completedModules, expectedModulesAt, pilotWeekAt, type PilotEnrollment } from "./pilot-metrics";
import { createAutomaticSnapshot } from "./report-automation";
import { renderTemplate, type TemplateRecord } from "./templates";

const cohort="RAHI-PILOT-01",programme="RAHI-01";
const esc=(v:string)=>v.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c));
function serviceClient(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase service configuration unavailable");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
async function deliver(to:string,subject:string,body:string){const key=process.env.RESEND_API_KEY,from=process.env.RAHI_EMAIL_FROM||process.env.LEXNUSA_LEAD_FROM_EMAIL||"Raja Ali Haji Institute <onboarding@resend.dev>";if(!key)return {status:"skipped" as const,id:null,error:"RESEND_API_KEY is not configured"};try{const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({from,to:[to],subject,text:body,html:`<div style="font-family:Arial,sans-serif;line-height:1.7;color:#111827"><h2 style="color:#92400e">Raja Ali Haji Institute</h2><div>${esc(body).replace(/\n/g,"<br/>")}</div></div>`})});if(!response.ok)return {status:"failed" as const,id:null,error:(await response.text()).slice(0,1000)};const data=await response.json().catch(()=>null) as {id?:string}|null;return {status:"sent" as const,id:data?.id||null,error:null};}catch(error){return {status:"failed" as const,id:null,error:error instanceof Error?error.message:"Unknown delivery error"};}}

export async function runPilotAutomation(now=new Date()){
  const admin=serviceClient(),week=pilotWeekAt(now),expected=expectedModulesAt(now),weekday=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Jakarta",weekday:"short"}).format(now);const snapshot=await createAutomaticSnapshot(admin,now);
  if(week<1||now.getTime()>Date.parse("2026-11-02T23:59:59+07:00"))return {ok:true,active:false,week,snapshot:!!snapshot,sent:0,skipped:0,failed:0};
  const [{data:profiles},{data:enrollments},{data:templates},{data:certificateRows},{data:{users}}]=await Promise.all([admin.from("profiles").select("id,full_name").eq("cohort_code",cohort),admin.from("enrollments").select("id,user_id,module_progress(module_number,completed,quiz_score)").eq("programme_code",programme),admin.from("rahi_communication_templates").select("template_key,name,channel,subject_template,body_template,allowed_variables,active").eq("active",true),admin.from("certificates").select("enrollment_id,certificate_number"),admin.auth.admin.listUsers({page:1,perPage:1000})]);
  const templateMap=new Map(((templates||[]) as TemplateRecord[]).map(x=>[x.template_key,x]));const emailMap=new Map(users.map(u=>[u.id,u.email||""]));const enrollmentMap=new Map(((enrollments||[]) as PilotEnrollment[]).map(x=>[x.user_id,x]));const certMap=new Map((certificateRows||[]).map(x=>[x.enrollment_id,x.certificate_number]));let sent=0,skipped=0,failed=0;
  for(const person of profiles||[]){const email=emailMap.get(person.id),enrollment=enrollmentMap.get(person.id);if(!email||!enrollment)continue;const completed=completedModules(enrollment),certificate=certMap.get(enrollment.id);const kinds:string[]=[];if(weekday==="Mon")kinds.push("weekly");if(completed<expected)kinds.push("behind_reminder");if(completed>=8)kinds.push("completion");if(certificate)kinds.push("certificate");if(now.getTime()>=Date.parse("2026-11-02T00:00:00+07:00"))kinds.push("final_thanks");
    for(const kind of kinds){const template=templateMap.get(kind);if(!template||!template.active)continue;const logWeek=Math.min(4,Math.max(1,week));const {data:existing}=await admin.from("rahi_pilot_message_log").select("id").eq("user_id",person.id).eq("cohort_code",cohort).eq("week_number",logWeek).eq("message_kind",kind).maybeSingle();if(existing){skipped++;continue;}const variables={name:person.full_name,week:logWeek,expected,completed,dashboard_url:"https://www.hossibarani.com/dashboard",certificate_number:certificate||"",certificate_url:certificate?`https://www.hossibarani.com/certificates/${certificate}`:""};const subject=renderTemplate(template.subject_template,variables),body=renderTemplate(template.body_template,variables);const {data:log,error}=await admin.from("rahi_pilot_message_log").insert({user_id:person.id,cohort_code:cohort,week_number:logWeek,message_kind:kind,recipient_email:email,expected_modules:expected,completed_modules:completed,delivery_status:"queued"}).select("id").single();if(error||!log){failed++;continue;}const result=await deliver(email,subject,body);await admin.from("rahi_pilot_message_log").update({delivery_status:result.status,provider_id:result.id,error_message:result.error,sent_at:result.status==="sent"?new Date().toISOString():null}).eq("id",log.id);if(result.status==="sent")sent++;else if(result.status==="skipped")skipped++;else failed++;}
  }
  return {ok:true,active:true,week,expected,snapshot:!!snapshot,sent,skipped,failed,eligible:(enrollments||[]).filter(x=>certificateEligible(x as PilotEnrollment)).length};
}
