type ReportInput={generatedAt:string;participants:number;baseline:number;endline:number;evaluation:number;completed:number;eligible:number;certificates:number;averageChange:number|null;checkins:number;messagesSent:number;interventions:number;resolved:number;categorySummary:string;recommendations:string[]};
type Line={text:string;size?:number;bold?:boolean;gap?:number};
const W=595,H=842,X=50,TOP=790,BOTTOM=55;
const clean=(v:string)=>v.replace(/[–—]/g,"-").replace(/[‘’]/g,"'").replace(/[“”]/g,'"').normalize("NFKD").replace(/[^\x20-\x7E\n\r\t]/g,"?");
const escape=(v:string)=>clean(v).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)");
function wrap(value:string,max=88){const out:string[]=[];for(const p of clean(value).split("\n")){const words=p.trim().split(/\s+/);let line="";for(const word of words){if(!word)continue;if(!line)line=word;else if(`${line} ${word}`.length<=max)line+=` ${word}`;else{out.push(line);line=word;}}out.push(line||" ");}return out;}
function section(lines:Line[],title:string,values:string[]){lines.push({text:title.toUpperCase(),size:12,bold:true,gap:4});for(const value of values)for(const row of wrap(value))lines.push({text:row,size:10,gap:1});lines.push({text:" ",size:6,gap:6});}
function content(input:ReportInput){const lines:Line[]=[{text:"RAJA ALI HAJI INSTITUTE",size:18,bold:true,gap:3},{text:"PILOT COHORT 1 - EXECUTIVE REPORT",size:14,bold:true,gap:8},{text:"Program Dasar Pemikiran Raja Ali Haji",size:11},{text:"Period: 5 October - 1 November 2026",size:10},{text:`Generated: ${input.generatedAt}`,size:9,gap:14}];section(lines,"Executive Snapshot",[`Participants: ${input.participants}`,`Completed 8 modules: ${input.completed} (${input.participants?Math.round(input.completed/input.participants*100):0}%)`,`Certificate eligible: ${input.eligible}`,`Certificates issued: ${input.certificates}`]);section(lines,"Measurement",[`Baseline completed: ${input.baseline}`,`Endline completed: ${input.endline}`,`Program evaluation completed: ${input.evaluation}`,`Average baseline-endline change: ${input.averageChange===null?"Not available":input.averageChange.toFixed(1)+" points"}`,`Weekly check-ins submitted: ${input.checkins}`]);section(lines,"Facilitation",[`Automated messages sent: ${input.messagesSent}`,`Interventions recorded: ${input.interventions}`,`Interventions resolved: ${input.resolved}`,`Participant categories: ${input.categorySummary||"Not available"}`]);section(lines,"Certificate Validation",["Eligibility requires completion of all eight modules and quiz scores of at least 70 in all eight modules. Completion of Module 8 includes the final reflection requirement in the learning flow."]);section(lines,"Recommendations",input.recommendations.map((x,i)=>`${i+1}. ${x}`));lines.push({text:"Prepared by Raja Ali Haji Institute",size:10,bold:true},{text:"Malay Ethical Constitutionalism - Research, Learning, Collaboration",size:9});return lines;}
function paginate(lines:Line[]){const pages:Line[][]=[];let page:Line[]=[],y=TOP;for(const line of lines){const size=line.size||10,height=Math.max(12,size+4)+(line.gap||0);if(y-height<BOTTOM&&page.length){pages.push(page);page=[];y=TOP;}page.push(line);y-=height;}if(page.length)pages.push(page);return pages;}
function stream(lines:Line[],page:number,count:number){let y=TOP;const c=["0.05 0.11 0.16 rg"];for(const line of lines){const size=line.size||10;c.push(`BT ${line.bold?"/F2":"/F1"} ${size} Tf 1 0 0 1 ${X} ${y} Tm (${escape(line.text)}) Tj ET`);y-=Math.max(12,size+4)+(line.gap||0);}c.push("0.45 0.48 0.52 rg",`BT /F1 8 Tf 1 0 0 1 ${X} 30 Tm (RAHI Pilot Cohort 1 - ${page}/${count}) Tj ET`);return c.join("\n");}
export function renderExecutiveReportPdf(input:ReportInput){const pages=paginate(content(input));const objects:string[]=["","","","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"],ids:number[]=[];for(let i=0;i<pages.length;i++){const s=stream(pages[i],i+1,pages.length),cid=objects.length;objects.push(`<< /Length ${Buffer.byteLength(s,"latin1")} >>\nstream\n${s}\nendstream`);const pid=objects.length;objects.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} ${H}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${cid} 0 R >>`);ids.push(pid);}objects[1]="<< /Type /Catalog /Pages 2 0 R >>";objects[2]=`<< /Type /Pages /Count ${ids.length} /Kids [${ids.map(id=>`${id} 0 R`).join(" ")}] >>`;let pdf="%PDF-1.4\n%RAHI\n";const offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=Buffer.byteLength(pdf,"latin1");pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const xref=Buffer.byteLength(pdf,"latin1");pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;return Buffer.from(pdf,"latin1");}
