import Link from "next/link";

const texts = [
  ["Gurindam Dua Belas", "Ethics, character, and responsible leadership"],
  ["Tsamarat al-Muhimmah", "Public office, justice, and accountability"],
  ["Muqaddimah fi Intizam Waza’if al-Malik", "Governmental organisation and limitation of power"],
];

export default function HomeHighlights() { return <section className="bg-white py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-amber-700">Flagship intellectual programme</p><h2 className="font-academic mt-4 text-4xl font-bold leading-tight text-slate-950 sm:text-5xl">Classical Malay texts. Contemporary constitutional questions.</h2><p className="mt-6 text-lg leading-8 text-slate-600">Malay Ethical Constitutionalism recovers Raja Ali Haji as a constitutional thinker and places the Malay world in conversation with global constitutional theory.</p><Link href="/research/malay-ethical-constitutionalism" className="mt-8 inline-flex rounded-xl bg-slate-950 px-6 py-3.5 font-semibold text-white hover:bg-amber-700">Read the complete framework →</Link></div><div className="overflow-hidden rounded-3xl bg-slate-950 p-7 text-white sm:p-9"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-amber-300">Three primary works</p><div className="mt-6 divide-y divide-white/10">{texts.map(([title, text], index) => <div key={title} className="grid gap-3 py-6 sm:grid-cols-[3rem_1fr]"><span className="font-academic text-2xl text-amber-300">0{index + 1}</span><div><h3 className="font-academic text-xl font-bold">{title}</h3><p className="mt-2 leading-7 text-slate-300">{text}</p></div></div>)}</div><div className="mt-7 border-t border-white/10 pt-7"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-slate-400">Resulting framework</p><p className="mt-3 text-lg leading-8 text-white">Ethical Authority · Justice · Consultation · Accountability · Limitation of Power</p></div></div></div></div></section>; }
