import { notFound } from "next/navigation";
import Link from "next/link";
import { CheckCircle2, CircleAlert, MessageCircle } from "lucide-react";
import { requireRahiAdmin } from "../../admin";
import { createIntervention, updateInterventionStatus } from "../actions";

type Progress={module_number:number;completed:boolean;quiz_score:number};
type Checkin={week_number:number;confidence:number;workload_status:string;blocker:string;support_request:string};
type Intervention={id:string;risk_status:string;note:string;action_status:string;created_at:string};
const waNumber=(input:string|null)=>{if(!input)return null;const digits=input.replace(/\D/g,"");return digits.startsWith("0")?`62${digits.slice(1)}`:digits;};

export default async function ParticipantDetail({params,searchParams}:{params:Promise<{participantId:string}>;searchParams:Promise<{saved?:string;error?:string}>}){
  const {participantId}=await params;const query=await searchParams;
  const {admin}=await requireRahiAdmin(`/raja-ali-haji/admin/pilot-01/${participantId}`);
  const [{data:profile},{data:enrollment},{data:assessments},{data:checkinRows}]=await Promise.all([
    admin.from("profiles").select("id,full_name,institution,participant_category,cohort_code,whatsapp_number").eq("id",participantId).eq("cohort_code","RAHI-PILOT-01").maybeSingle(),
    admin.from("enrollments").select("id,user_id,module_progress(module_number,completed,quiz_score)").eq("user_id",participantId).eq("programme_code","RAHI-01").maybeSingle(),
    admin.from("rahi_pilot_assessments").select("assessment_type,total_score").eq("user_id",participantId).eq("cohort_code","RAHI-PILOT-01"),
    admin.from("rahi_pilot_checkins").select("week_number,confidence,workload_status,blocker,support_request").eq("user_id",participantId).eq("cohort_code","RAHI-PILOT-01").order("week_number"),
  ]);
  if(!profile)notFound();
  const {data:interventionRows}=enrollment?.id?await admin.from("rahi_pilot_interventions").select("id,risk_status,note,action_status,created_at").eq("enrollment_id",enrollment.id).order("created_at",{ascending:false}):{data:[]};
  const progress=((enrollment?.module_progress||[]) as Progress[]).sort((a,b)=>a.module_number-b.module_number);const completed=progress.filter(x=>x.completed).length;
  const checkins=(checkinRows||[]) as Checkin[];const interventions=(interventionRows||[]) as Intervention[];const risk=completed>=8?"green":completed>=6?"yellow":"red";const number=waNumber(profile.whatsapp_number);
  const message=encodeURIComponent(`Assalamu'alaikum ${profile.full_name}. Kami dari Raja Ali Haji Institute ingin mendampingi progres belajar Anda. Saat ini ${completed}/8 modul telah selesai. Apakah ada kendala yang dapat kami bantu?`);
  return <main className="min-h-screen bg-[#f3f0e9] px-5 py-12 text-slate-950 sm:px-8"><div className="mx-auto max-w-6xl">
    <Link href="/raja-ali-haji/admin/pilot-01" className="font-bold text-amber-800">← Dashboard cohort</Link>
    <div className="mt-8 flex flex-wrap items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-amber-700">Participant case file · Restricted</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">{profile.full_name}</h1><p className="mt-3 text-slate-600">{profile.institution||"Tanpa institusi"} · {profile.participant_category||"Kategori belum diisi"}</p></div>{number?<a href={`https://wa.me/${number}?text=${message}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-5 py-4 font-black text-white"><MessageCircle size={19}/> Hubungi via WhatsApp</a>:<span className="rounded-xl bg-stone-200 px-5 py-4 font-bold text-stone-600">Nomor WhatsApp belum tersedia</span>}</div>
    {query.saved&&<p className="mt-6 border border-emerald-300 bg-emerald-50 p-4 font-bold text-emerald-800">Catatan intervensi tersimpan.</p>}{query.error&&<p className="mt-6 border border-red-300 bg-red-50 p-4 font-bold text-red-800">{query.error}</p>}
    <section className="mt-8 grid gap-5 lg:grid-cols-3"><Stat dark label="Progres modul" value={`${completed}/8`} note={`${progress.filter(x=>x.quiz_score>=70).length} kuis mencapai nilai 70`}/><Stat label="Asesmen" value={`${assessments?.length||0}/3`} note="Baseline, endline, dan evaluasi"/><Stat label="Check-in mingguan" value={`${checkins.length}/4`} note="Sinyal pendampingan peserta"/></section>
    <section className="mt-8 grid gap-7 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-7">
      <article className="rounded-2xl border border-stone-300 bg-white p-6"><h2 className="text-2xl font-black">Kemajuan modul</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[1,2,3,4,5,6,7,8].map(n=>{const row=progress.find(x=>x.module_number===n);return <div key={n} className={`rounded-xl border p-4 ${row?.completed?"border-emerald-300 bg-emerald-50":"border-stone-200"}`}><p className="font-black">Modul {n}</p><p className="mt-1 text-sm text-slate-600">{row?`Kuis ${row.quiz_score||0}`:"Belum dimulai"}</p></div>})}</div></article>
      <article className="rounded-2xl border border-stone-300 bg-white p-6"><h2 className="text-2xl font-black">Check-in peserta</h2><div className="mt-5 space-y-4">{checkins.length===0?<p className="text-slate-500">Belum ada check-in.</p>:checkins.map(x=><div key={x.week_number} className="rounded-xl bg-stone-50 p-5"><div className="flex flex-wrap justify-between gap-3"><b>Minggu {x.week_number}</b><span className="font-bold">Keyakinan {x.confidence}/5 · {x.workload_status}</span></div>{x.blocker&&<p className="mt-3"><b>Kendala:</b> {x.blocker}</p>}{x.support_request&&<p className="mt-2"><b>Dukungan:</b> {x.support_request}</p>}</div>)}</div></article>
    </div><aside className="space-y-7">
      <form action={createIntervention} className="rounded-2xl bg-[#111526] p-6 text-white"><CircleAlert className="text-amber-400"/><h2 className="mt-4 text-2xl font-black">Catat intervensi</h2>{enrollment?<><input type="hidden" name="enrollmentId" value={enrollment.id}/><input type="hidden" name="participantId" value={participantId}/><label className="mt-5 block font-bold">Status risiko<select name="riskStatus" defaultValue={risk} className="mt-2 w-full bg-white p-3 text-slate-950"><option value="green">Hijau</option><option value="yellow">Kuning</option><option value="red">Merah</option></select></label><label className="mt-5 block font-bold">Catatan dan tindakan<textarea name="note" required minLength={2} rows={6} className="mt-2 w-full bg-white p-3 font-normal text-slate-950"/></label><button className="mt-5 w-full rounded-xl bg-amber-400 px-5 py-4 font-black text-slate-950">Simpan intervensi</button></>:<p className="mt-4 text-slate-300">Peserta belum memiliki enrollment aktif.</p>}</form>
      <article className="rounded-2xl border border-stone-300 bg-white p-6"><h2 className="text-2xl font-black">Riwayat tindak lanjut</h2><div className="mt-5 space-y-4">{interventions.length===0?<p className="text-slate-500">Belum ada intervensi.</p>:interventions.map(x=><div key={x.id} className="rounded-xl border border-stone-200 p-4"><div className="flex items-center justify-between gap-3"><span className="font-black capitalize">{x.risk_status}</span><span className="text-xs text-slate-500">{new Date(x.created_at).toLocaleDateString("id-ID")}</span></div><p className="mt-3 leading-7">{x.note}</p><form action={updateInterventionStatus} className="mt-4 flex gap-2"><input type="hidden" name="id" value={x.id}/><input type="hidden" name="participantId" value={participantId}/><select name="status" defaultValue={x.action_status} className="min-w-0 flex-1 border border-stone-300 p-2"><option value="open">Terbuka</option><option value="contacted">Sudah dihubungi</option><option value="resolved">Selesai</option></select><button aria-label="Simpan status" className="rounded-lg bg-slate-950 px-3 font-bold text-white"><CheckCircle2 size={17}/></button></form></div>)}</div></article>
    </aside></section>
  </div></main>;
}

function Stat({label,value,note,dark=false}:{label:string;value:string;note:string;dark?:boolean}){return <article className={`rounded-2xl p-6 ${dark?"bg-slate-950 text-white":"border border-stone-300 bg-white"}`}><p className={dark?"text-sm text-slate-300":"text-sm text-slate-500"}>{label}</p><p className="mt-2 text-4xl font-black">{value}</p><p className={`mt-3 text-sm ${dark?"text-slate-300":"text-slate-500"}`}>{note}</p></article>}
