"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-4-v1";
const SOURCE_URL = "https://books.google.com/books/about/Kitab_pengetahuan_bahasa.html?id=ln0T0QEACAAJ";

const nav = [
  ["introduction", "Pengantar"], ["reading", "Bacaan utama"], ["analysis", "Kerangka bahasa"],
  ["podcast", "Podcast"], ["reflection", "Refleksi"], ["essay", "Esai"], ["quiz", "Kuis"], ["result", "Hasil"],
];

const readings = [
  { n:"I", title:"Kamus yang melampaui daftar kata", text:<><p>Judul lengkap karya ini ialah <em>Kitab Pengetahuan Bahasa, yaitu Kamus Logat Melayu Johor, Pahang, Riau, dan Lingga</em>. Namun bentuknya tidak sama dengan kamus ringkas modern. Sebuah lema dapat berkembang menjadi uraian tentang agama, sejarah, budi pekerti, kehidupan sosial, atau pemerintahan.</p><p>Raja Ali Haji menyusun karya ini pada paruh kedua abad ke-19. Versi yang dikenal tidak selesai dan hanya mencakup sebagian urutan huruf. Ketidaklengkapan itu tidak menghapus nilainya: kitab ini menunjukkan bagaimana seorang cendekiawan Melayu berusaha mendefinisikan dunianya dengan bahasanya sendiri.</p></>, idea:"Kamus dapat menjadi peta pengetahuan dan kebudayaan, bukan hanya alat mencari padanan kata." },
  { n:"II", title:"Dari tata bahasa menuju pengetahuan makna", text:<><p>Bagian awal kitab kembali memakai kerangka tata bahasa yang berhubungan dengan <em>Bustan al-Katibin</em>. Sesudah itu, pembahasan bergerak kepada kata-kata Melayu dan penjelasan maknanya.</p><p>Peralihan ini memperlihatkan dua tugas ilmu bahasa. Tata bahasa menelaah bagaimana unsur bahasa tersusun, sedangkan kamus membantu menjelaskan apa yang dimaksud oleh kata dan bagaimana kata itu digunakan. Susunan tanpa makna akan kosong; makna tanpa susunan akan sulit disampaikan.</p></>, idea:"Modul 3 dan Modul 4 membentuk satu rangkaian: tata susun bahasa dan tata makna bahasa." },
  { n:"III", title:"Definisi sebagai penetapan batas", text:<><p>Mendefinisikan berarti menentukan ciri yang membuat sebuah pengertian dapat dibedakan dari pengertian lain. Definisi yang terlalu luas memasukkan hal yang bukan bagiannya; definisi yang terlalu sempit membuang bagian yang seharusnya termasuk.</p><p>Raja Ali Haji sering tidak berhenti pada sinonim. Ia memberi uraian, ciri, contoh, hubungan, dan penilaian. Cara ini memperlihatkan bahwa makna tumbuh di dalam jaringan pengetahuan. Karena itu, pembaca perlu membedakan penjelasan leksikal, keterangan ensiklopedis, dan penilaian normatif.</p></>, idea:"Definisi bukan sekadar mengganti satu kata dengan kata lain, tetapi menjelaskan batas dan jaringan maknanya." },
  { n:"IV", title:"Kata menyimpan pandangan dunia", text:<><p>Istilah tentang ilmu, agama, akhlak, kekuasaan, tubuh, dan hubungan sosial membawa cara tertentu dalam memahami manusia serta masyarakat. Ketika sebuah kata didefinisikan, nilai dan pengalaman budaya yang menyertainya ikut dijelaskan.</p><p>Inilah sebabnya kamus dapat dibaca sebagai arsip peradaban. Ia mencatat bukan hanya apa yang disebut oleh masyarakat, tetapi juga bagaimana masyarakat membedakan yang baik dan buruk, terpuji dan tercela, sah dan tidak sah, dekat dan asing.</p></>, idea:"Kosakata adalah tempat pengalaman sejarah dan nilai budaya disimpan serta diwariskan." },
  { n:"V", title:"Bahasa Melayu sebagai bahasa ilmu", text:<><p>Dengan menulis kamus ekabahasa yang luas, Raja Ali Haji memperlihatkan bahwa bahasa Melayu mampu menerangkan pengetahuan menggunakan sumber dayanya sendiri. Pengaruh bahasa Arab tampak pada istilah dan perangkat analisis, tetapi penjelasannya diarahkan kepada pembaca dunia Melayu.</p><p>Pekerjaan ini bukan upaya membekukan bahasa. Bahasa selalu berubah. Yang dipertahankan ialah kemampuan bahasa untuk menyampaikan pengetahuan secara cermat, membangun kesinambungan antargenerasi, dan menjadi ruang perjumpaan masyarakat Johor, Pahang, Riau, serta Lingga.</p></>, idea:"Pemeliharaan bahasa berarti menjaga daya bahasa untuk berpikir dan menjelaskan dunia, bukan menolak seluruh perubahan." },
  { n:"VI", title:"Perebutan makna di ruang publik", text:<><p>Kehidupan publik modern dipenuhi kata yang diperebutkan: adil, rakyat, demokrasi, agama, Melayu, kemajuan, bahkan fakta. Perbedaan pendapat sering menjadi buntu karena orang memakai kata yang sama dengan pengertian berbeda.</p><p>Pelajaran dari <em>Kitab Pengetahuan Bahasa</em> adalah kebiasaan bertanya sebelum berdebat: apa definisinya, cirinya, konteksnya, dan akibat penggunaan kata tersebut? Sikap ini tidak menghapus perbedaan, tetapi membuat perbedaan dapat diperiksa secara lebih jujur.</p></>, idea:"Menjernihkan istilah adalah langkah awal menjernihkan perdebatan dan keputusan publik." },
];

const questions = [
  { q:"Kitab Pengetahuan Bahasa paling tepat dipahami sebagai…", o:["Daftar kata yang sangat singkat","Kamus ensiklopedis yang juga memuat pengetahuan dan nilai","Kumpulan syair perang","Buku administrasi kolonial"], a:1 },
  { q:"Wilayah bahasa yang disebut dalam judul kitab adalah…", o:["Johor, Pahang, Riau, dan Lingga","Jawa, Sunda, dan Bali","Aceh dan Minangkabau","Malaka dan Batavia saja"], a:0 },
  { q:"Hubungan Modul 3 dan Modul 4 adalah…", o:["Tidak berhubungan","Tata susun bahasa dilanjutkan dengan tata makna","Keduanya hanya membahas puisi","Modul 4 membatalkan Modul 3"], a:1 },
  { q:"Mendefinisikan kata berarti…", o:["Memperpanjang tulisan","Menentukan ciri dan batas pengertian","Menghapus konteks","Mengganti semua kata asing"], a:1 },
  { q:"Definisi terlalu luas akan…", o:["Memasukkan hal yang bukan bagiannya","Selalu menjadi benar","Menghapus seluruh contoh","Menjadi puisi"], a:0 },
  { q:"Mengapa kamus dapat disebut arsip peradaban?", o:["Karena selalu sangat tua","Karena menyimpan pengalaman, nilai, dan pembedaan budaya dalam kosakata","Karena hanya mencatat nama raja","Karena tidak pernah berubah"], a:1 },
  { q:"Bahasa Melayu sebagai bahasa ilmu berarti…", o:["Hanya boleh digunakan di sekolah","Mampu menerangkan pengetahuan secara cermat","Tidak boleh menyerap istilah","Harus memiliki satu dialek"], a:1 },
  { q:"Pemeliharaan bahasa dalam modul ini berarti…", o:["Menolak seluruh perubahan","Menjaga daya bahasa untuk berpikir sambil memahami perubahan","Melarang bahasa sehari-hari","Menghapus variasi"], a:1 },
  { q:"Langkah awal menghadapi perebutan makna di ruang publik adalah…", o:["Meninggikan suara","Menjernihkan definisi, ciri, dan konteks istilah","Menghindari semua perdebatan","Mengulang slogan"], a:1 },
  { q:"Gagasan utama Modul 4 adalah…", o:["Kata bersifat netral dan tanpa sejarah","Makna kata membentuk pengetahuan, identitas, dan percakapan publik","Kamus hanya berguna untuk ejaan","Semua definisi pasti sama"], a:1 },
];

export default function ModuleFourLearning() {
  const [active, setActive] = useState("introduction");
  const [reflection, setReflection] = useState("");
  const [essay, setEssay] = useState("");
  const [answers, setAnswers] = useState<AnswerMap>({});
  const [score, setScore] = useState<number | null>(null);
  const [readingDone, setReadingDone] = useState(false);
  const [analysisDone, setAnalysisDone] = useState(false);
  const [podcastDone, setPodcastDone] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const d = JSON.parse(raw); setReflection(d.reflection ?? ""); setEssay(d.essay ?? ""); setAnswers(d.answers ?? {}); setScore(d.score ?? null); setReadingDone(Boolean(d.readingDone)); setAnalysisDone(Boolean(d.analysisDone)); setPodcastDone(Boolean(d.podcastDone)); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; const id = window.setTimeout(() => { void saveModuleProgress(STORAGE_KEY, 4, { reflection, essay, answers, score, readingDone, analysisDone, podcastDone }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200); }); }, 500); return () => window.clearTimeout(id); }, [reflection, essay, answers, score, readingDone, analysisDone, podcastDone, hydrated]);

  const reflectionWords = useMemo(() => countWords(reflection), [reflection]);
  const essayWords = useMemo(() => countWords(essay), [essay]);
  const reflectionDone = reflectionWords >= 100;
  const essayDone = essayWords >= 500;
  const quizDone = score !== null && score >= 70;
  const done = [readingDone, analysisDone, podcastDone, reflectionDone, essayDone, quizDone];
  const progress = Math.round(done.filter(Boolean).length / 6 * 100);
  const complete = done.every(Boolean);

  function submit() { if (Object.keys(answers).length < questions.length) { alert("Jawab seluruh pertanyaan terlebih dahulu."); return; } setScore(questions.filter((q, i) => Number(answers[i]) === q.a).length * 10); setActive("result"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <main className="min-h-screen bg-[#f7f4ee] text-slate-950">
    <header className="border-b border-white/10 bg-[#070916] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-400"><ArrowLeft size={17}/> Kembali ke program</Link><div className="min-w-56"><div className="flex justify-between text-xs"><span>Progres Modul 4</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${progress}%` }}/></div></div></div></header>
    <section className="bg-[#070916] px-5 pb-14 pt-10 text-white sm:px-8 md:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 4 dari 8</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Kata, Makna, dan Dunia Melayu</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Membaca <em>Kitab Pengetahuan Bahasa</em> sebagai kamus, peta pengetahuan, dan arsip pandangan dunia Melayu.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 120–150 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Tingkat dasar</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai, dan kuis</span></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id, label], i) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active === id ? "bg-slate-950 text-white" : "hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i + 1).padStart(2, "0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved ? "Tersimpan otomatis ✓" : "Progres tersimpan di perangkat ini"}</div></aside>
      <div className="min-w-0">
        {active === "introduction" && <Panel eyebrow="Mulai di sini" title="Pengantar Modul 4"><p>Modul 3 mempelajari cara bahasa disusun. Modul 4 bergerak kepada cara kata diberi makna. Melalui <em>Kitab Pengetahuan Bahasa</em>, Raja Ali Haji menunjukkan bahwa kamus dapat menjadi peta ilmu, nilai, sejarah, dan identitas masyarakat.</p><h3>Tujuan pembelajaran</h3><ol><li>Menjelaskan sifat ensiklopedis <em>Kitab Pengetahuan Bahasa</em>.</li><li>Membedakan susunan bahasa, makna leksikal, keterangan ensiklopedis, dan penilaian normatif.</li><li>Menganalisis hubungan kosakata dengan pandangan dunia Melayu.</li><li>Menerapkan kejernihan definisi dalam percakapan publik.</li></ol><blockquote>Ketika dua orang memakai kata yang sama tetapi memberikan makna berbeda, apakah mereka sedang memperdebatkan persoalan yang sama?</blockquote><Next onClick={() => setActive("reading")}>Mulai membaca</Next></Panel>}
        {active === "reading" && <Panel eyebrow="Bacaan utama • 30–40 menit" title="Kamus sebagai peta sebuah peradaban"><p>Bacaan berikut menyajikan alur pemikiran utama kitab untuk pembelajar tingkat dasar. Uraian membedakan informasi tentang karya, cara mendefinisikan, dan penafsiran kontemporer.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Lihat edisi sumber</p><p className="mt-2 text-sm leading-6 text-slate-600">Katalog edisi Departemen Pendidikan dan Kebudayaan tahun 1986 mencatat kitab ini sebagai kamus logat Melayu Johor, Pahang, Riau, dan Lingga.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka Kitab Pengetahuan Bahasa <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e => setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 4.</label><Next onClick={() => setActive("analysis")}>Lanjut ke kerangka makna</Next></Panel>}
        {active === "analysis" && <Panel eyebrow="Analisis konseptual" title="Dari kata menuju pandangan dunia"><div className="grid gap-4 md:grid-cols-3"><Concept n="01" title="Lema" text="Kata yang dipilih sebagai pintu masuk menuju penjelasan."/><Concept n="02" title="Definisi" text="Ciri dan batas yang membedakan satu pengertian dari pengertian lain."/><Concept n="03" title="Dunia makna" text="Hubungan kata dengan sejarah, nilai, pengalaman, dan lembaga sosial."/></div><h3>Dari kata menuju definisi</h3><p>Definisi yang baik membantu pembaca mengetahui apa yang termasuk dan tidak termasuk dalam sebuah pengertian. Ia juga menjelaskan konteks penggunaan agar kata tidak dipindahkan secara sembarangan.</p><h3>Dari definisi menuju kebudayaan</h3><p>Ketika sebuah kamus menguraikan istilah ilmu, agama, kekuasaan, dan budi pekerti, ia sekaligus merekam cara masyarakat memahami dunia. Karena itu, kamus dapat dibaca sebagai arsip peradaban.</p><h3>Dari bahasa menuju ruang publik</h3><p>Perdebatan menjadi lebih jernih ketika peserta menyatakan definisi dan ukuran yang digunakan. Menjernihkan istilah tidak menghapus perbedaan nilai, tetapi mencegah orang berdebat atas pengertian yang tidak pernah disepakati.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e => setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami hubungan lema, definisi, kebudayaan, dan ruang publik.</label><Next onClick={() => setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
        {active === "podcast" && <Panel eyebrow="Podcast • 18 menit" title="Kata yang Membentuk Dunia"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Raja Ali Haji: Penawar Kekacauan Era Digital</p><p className="mt-1 text-sm text-slate-400">Audio Overview • Bahasa Indonesia • 18:39</p></div></div><audio className="mt-7 w-full" controls preload="metadata" onEnded={() => setPodcastDone(true)}><source src="/audio/raja-ali-haji-penawar-kekacauan-era-digital.m4a" type="audio/mp4"/>Peramban Anda tidak mendukung pemutar audio.</audio></div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan podcast</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p>Podcast membaca <em>Kitab Pengetahuan Bahasa</em> sebagai karya leksikografi yang melampaui daftar arti. Kata, definisi, dan contoh pemakaian menjadi jalan untuk memahami ilmu, nilai, identitas Melayu, serta cara manusia menata dunia.</p><p>Di tengah banjir informasi digital, ketelitian mendefinisikan istilah membantu kita membedakan fakta, pendapat, slogan, dan manipulasi. Warisan Raja Ali Haji mengingatkan bahwa kejernihan bahasa merupakan bagian dari kejernihan pikiran dan tanggung jawab publik.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e => setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mendengarkan podcast ini sampai selesai.</label><Next onClick={() => setActive("reflection")} disabled={!podcastDone}>Lanjut ke refleksi</Next></Panel>}
        {active === "reflection" && <Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi tentang makna"><p>Pilih satu kata yang sering diperdebatkan—misalnya adil, Melayu, rakyat, agama, atau kemajuan. Jelaskan pengertian yang Anda gunakan, cirinya, dan mengapa definisi tersebut penting.</p><textarea value={reflection} onChange={e => setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={() => setActive("essay")}>Simpan dan lanjut ke esai</Next></Panel>}
        {active === "essay" && <Panel eyebrow="Penilaian • 500–700 kata" title="Tugas esai Modul 4"><blockquote>Jelaskan bagaimana <em>Kitab Pengetahuan Bahasa</em> mengubah kamus dari daftar kata menjadi peta pengetahuan dan pandangan dunia Melayu.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan sedikitnya tiga bagian bacaan Modul 4.</li><li>Jelaskan perbedaan makna leksikal, uraian ensiklopedis, dan penilaian normatif.</li><li>Bahas hubungan bahasa dengan identitas atau kekuasaan.</li><li>Berikan satu contoh perebutan makna kontemporer.</li></ul><textarea value={essay} onChange={e => setEssay(e.target.value)} rows={22} placeholder="Mulai menulis esai…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={500} max={700}/><Next disabled={!essayDone} onClick={() => setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
        {active === "quiz" && <Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 4"><div className="space-y-8">{questions.map((q, i) => <fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i + 1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o, j) => <label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i]) === j ? "border-amber-600 bg-amber-50" : "border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q4-${i}`} checked={Number(answers[i]) === j} value={j} onChange={e => setAnswers({ ...answers, [i]: e.target.value })} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
        {active === "result" && <Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 4"><div className={`border p-7 ${complete ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score ?? 0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone ? "Kuis lulus." : "Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan utama selesai"/><Req done={analysisDone} text="Kerangka makna selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai minimal 500 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete ? <div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 4 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menyelesaikan pembelajaran kata, makna, dan pandangan dunia Melayu dalam <em>Kitab Pengetahuan Bahasa</em>.</p><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji/module-5" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-4 font-bold text-emerald-800 transition hover:bg-emerald-50">Lanjut ke Modul 5 <ArrowRight size={18}/></Link></div> : <button onClick={() => { setAnswers({}); setScore(null); setActive("quiz"); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
      </div>
    </div>
  </main>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>; }
function Next({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>; }
function Words({ count, min, max }: { count: number; min: number; max: number }) { return <p className={`text-sm font-semibold ${count >= min ? "text-emerald-700" : "text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count >= min ? "✓" : ""}</p>; }
function Req({ done, text }: { done: boolean; text: string }) { return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done ? "text-emerald-600" : "text-stone-300"} size={21}/><span className={done ? "font-semibold" : "text-slate-500"}>{text}</span></div>; }
function Concept({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+/).length : 0; }
function ReadingAccordion() { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section, i) => <article key={section.n}><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open === i ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>{open === i && <div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>}</article>)}</div>; }
