import type {Metadata} from 'next';
import Link from 'next/link';
import {requireTreasurer} from '@/lib/persis/master-server';
import {loadProgramReport} from '@/lib/persis/program-server';
import {PROGRAM_BASE,PROGRAM_STATUS,programYear,programTotals,type ProgramReport} from '@/lib/persis/program';
import {rupiah} from '@/lib/persis/dues';
import TreasuryNav from '../TreasuryNav';
import ProgramForm from './ProgramForm';
import AssignmentForm from './AssignmentForm';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Program & Anggaran PW Persis Kepri',robots:{index:false,follow:false}};
export default async function ProgramsPage({searchParams}:{searchParams:Promise<{year?:string;page?:string;error?:string;success?:string}>}){
 const {client}=await requireTreasurer(PROGRAM_BASE),params=await searchParams,year=programYear(params.year);
 let report:ProgramReport|null=null,error='';try{report=await loadProgramReport(client,year);}catch(e){error=e instanceof Error?e.message:'Laporan belum dapat dimuat.';}
 const totals=report?programTotals(report):null,page=Math.min(Math.max(1,parseInt(params.page||'1')||1),Math.max(1,Math.ceil((report?.unassigned.length||0)/20)));
 return <div lang="id" className="min-h-screen bg-slate-50 px-4 py-10 text-slate-900 sm:px-6"><main className="mx-auto max-w-6xl"><Link href="/persis-kepri/iuran" className="text-sm font-semibold text-emerald-800 underline">Kembali ke iuran anggota</Link><p className="mt-6 text-sm font-bold uppercase tracking-widest text-emerald-800">Ruang bendahara · PW Persis Kepri</p><h1 className="mt-2 text-3xl font-bold sm:text-4xl">Program, anggaran & realisasi</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">Hubungkan rencana kerja dengan pengeluaran nyata. Realisasi dihitung dari pengeluaran buku kas yang aktif dan sudah ditautkan ke program.</p><TreasuryNav/>
  {params.error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{params.error}</p>}{params.success&&<p role="status" className="mb-5 rounded-xl bg-emerald-100 p-4 text-emerald-950">Tautan program berhasil disimpan. Realisasi diperbarui otomatis.</p>}
  <form className="my-6 flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm font-semibold">Tahun anggaran<input name="year" type="number" min="2020" max="2100" defaultValue={year} required className="w-36 rounded-lg border border-slate-300 bg-white p-3"/></label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Tampilkan</button><a href="#program-baru" className="rounded-lg border border-emerald-700 px-5 py-3 font-semibold text-emerald-900">Tambah program</a></form>
  {error?<p role="alert" className="rounded-xl bg-red-50 p-5 text-red-800">{error}</p>:report&&totals&&<>
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Anggaran tercatat',totals.budget],['Realisasi tertaut',totals.spent],['Sisa anggaran',totals.remaining],['Pengeluaran belum tertaut',totals.unassigned]].map(([label,value])=><div key={String(label)} className="rounded-2xl border border-emerald-100 bg-white p-5"><p className="text-sm text-slate-600">{label}</p><p className={`mt-2 text-2xl font-bold ${Number(value)<0?'text-red-700':'text-emerald-900'}`}>{rupiah(Number(value))}</p></div>)}</div>
   <p className="mt-4 text-sm leading-6 text-slate-600">{report.programs.length} program · {totals.completed} selesai · {totals.over} melebihi anggaran. Rekap mencakup program dibatalkan agar jejak anggaran dan belanja tetap terlihat. Rencana sumber dana bukan penerimaan kas.</p>
   {!report.cash_start_date?<p className="mt-4 rounded-xl bg-amber-50 p-4 text-amber-900">Buku kas belum dimulai. Program dan anggaran dapat disusun sekarang; <Link href="/persis-kepri/iuran/bendahara/kas" className="font-semibold underline">tetapkan saldo awal</Link> sebelum mencatat pengeluaran.</p>:<p className="mt-2 text-sm text-slate-600">Realisasi hanya mencakup transaksi buku kas sejak {report.cash_start_date}. Pengeluaran sebelum pembukuan tidak ditambahkan dari saldo awal.</p>}
   <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-bold">Program kerja {year}</h2><div className="flex gap-2"><a href={`/api/persis/program/export?year=${year}&format=xlsx`} className="rounded-lg border border-emerald-700 px-4 py-2 text-sm font-bold text-emerald-900">Unduh Excel</a><a href={`/api/persis/program/export?year=${year}&format=pdf`} className="rounded-lg bg-emerald-800 px-4 py-2 text-sm font-bold text-white">Unduh PDF</a></div></div>
    {!report.programs.length?<p className="mt-5 rounded-xl bg-slate-50 p-5 text-slate-600">Belum ada program pada tahun ini. Tambahkan program berdasarkan rencana dan anggaran yang ditetapkan pengurus.</p>:<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-emerald-50 text-emerald-950"><tr>{['Program / penanggung jawab','Jadwal / progres','Anggaran','Realisasi','Sisa'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{report.programs.map(p=><tr key={p.id} className="border-b border-slate-100 align-top"><td className="max-w-sm p-3"><Link href={`${PROGRAM_BASE}/${p.id}`} className="font-bold text-emerald-800 underline">{p.title}</Link><p className="mt-1 text-slate-600">{p.division} · {p.responsible}</p><span className="mt-2 inline-block rounded-full bg-slate-100 px-3 py-1 text-xs">{PROGRAM_STATUS[p.status]}</span></td><td className="p-3"><p className="whitespace-nowrap">{p.start_date} — {p.end_date}</p><p className="mt-2">Progres kegiatan {p.progress}%</p><progress value={p.progress} max={100} aria-label={`Progres ${p.title}`} className="mt-1 h-2 w-full accent-emerald-700"/></td><td className="p-3 whitespace-nowrap">{rupiah(p.budget)}</td><td className="p-3 whitespace-nowrap">{rupiah(p.spent)}<p className="mt-1 text-xs text-slate-500">{p.budget?`${Math.round(p.spent/p.budget*100)}% terserap`:p.spent?'Belanja tanpa anggaran':'Anggaran nol'}</p></td><td className={`p-3 whitespace-nowrap font-semibold ${p.spent>p.budget?'text-red-700':'text-emerald-900'}`}>{rupiah(p.budget-p.spent)}{p.spent>p.budget&&<p className="mt-1 text-xs">Melebihi anggaran</p>}</td></tr>)}</tbody></table></div>}
   </section>
   <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold">Pengeluaran belum ditautkan ({report.unassigned.length})</h2><p className="mt-2 text-sm leading-6 text-slate-600">Pengeluaran umum tetap masuk buku kas. Jika untuk suatu program, tautkan seluruh nominal ke satu program pada tahun yang sama. Penautan tidak menambah transaksi kas.</p>
    {!report.unassigned.length?<p className="mt-4 text-slate-600">Tidak ada pengeluaran aktif yang belum ditautkan pada tahun ini.</p>:<div className="mt-5 grid gap-4 md:grid-cols-2">{report.unassigned.slice((page-1)*20,page*20).map(r=><article key={r.id} className="rounded-xl border border-slate-200 p-4"><p className="text-sm text-slate-500">{r.transacted_on} · KAS-{r.id.slice(0,8)}</p><h3 className="mt-2 font-bold">{r.party} · {rupiah(r.amount)}</h3><p className="mt-2 whitespace-pre-wrap text-sm">{r.description}</p><a href={`/api/persis/cash/${r.id}/receipt`} className="mt-2 inline-block text-sm text-emerald-800 underline">Unduh bukti</a><details className="mt-3"><summary className="cursor-pointer font-semibold text-emerald-900">Tautkan ke program</summary><AssignmentForm entryId={r.id} programs={report.programs} year={year}/></details></article>)}</div>}
    {report.unassigned.length>20&&<div className="mt-4 flex gap-5 text-sm">{page>1&&<Link className="underline" href={`${PROGRAM_BASE}?year=${year}&page=${page-1}`}>Sebelumnya</Link>}<span>Halaman {page} / {Math.ceil(report.unassigned.length/20)}</span>{page*20<report.unassigned.length&&<Link className="underline" href={`${PROGRAM_BASE}?year=${year}&page=${page+1}`}>Berikutnya</Link>}</div>}
   </section>
  </>}
  <section id="program-baru" className="mt-6 max-w-4xl scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-xl font-bold">Tambah program kerja</h2><ProgramForm year={year}/></section>
 </main></div>;
}
