"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-8-v1";
const SOURCE_URL = "https://repository.uin-suska.ac.id/69870/1/PEMIKIRAN%20ETIKA%20POLITIK.pdf";
const nav = [["introduction","Pengantar"],["reading","Bacaan sintesis"],["analysis","Kerangka aktualisasi"],["podcast","Podcast"],["reflection","Refleksi"],["essay","Esai akhir"],["quiz","Kuis"],["result","Hasil"]];

const readings = [
  {n:"I",title:"Membaca warisan tanpa membekukannya",text:<><p>Relevansi tidak berarti menyalin seluruh bentuk kehidupan abad kesembilan belas ke masa kini. Raja Ali Haji hidup dalam dunia Riau–Lingga yang memiliki struktur politik, teknologi, dan hubungan sosial berbeda dari negara modern.</p><p>Yang dapat diaktualkan ialah pertanyaan, nilai, dan cara berpikirnya: bagaimana manusia menertibkan diri, bagaimana bahasa menjaga akal sehat, bagaimana pengetahuan membentuk adab, dan bagaimana kekuasaan diarahkan kepada keadilan.</p></>,idea:"Aktualisasi mempertemukan pertanyaan lama dengan persoalan baru tanpa menghapus konteks sejarah."},
  {n:"II",title:"Diri dan karakter di tengah ekonomi perhatian",text:<><p><em>Gurindam Dua Belas</em> memulai perubahan sosial dari pengenalan dan pengendalian diri. Lidah, mata, telinga, tangan, perut, dan hati harus dipelihara karena tindakan lahir berawal dari kebiasaan batin.</p><p>Dalam ekonomi perhatian, manusia didorong bereaksi cepat, mengejar pengakuan, dan membandingkan diri. Nasihat tentang sabar, malu, amanah, dan menahan hawa nafsu dapat dibaca sebagai latihan kedaulatan diri agar keputusan tidak dikuasai kemarahan atau dorongan sesaat.</p></>,idea:"Karakter adalah kemampuan mengatur perhatian, keinginan, dan tindakan sebelum mengatur orang lain."},
  {n:"III",title:"Bahasa sebagai infrastruktur kepercayaan",text:<><p><em>Bustan al-Katibin</em> dan <em>Kitab Pengetahuan Bahasa</em> menunjukkan bahwa bahasa bukan sekadar alat menyampaikan isi pikiran. Ketepatan kata, susunan kalimat, dan pemahaman makna ikut menentukan ketertiban pikiran serta hubungan sosial.</p><p>Di ruang digital, kata dapat bergerak jauh lebih cepat daripada pemeriksaan. Karena itu, adab berbahasa kini mencakup memeriksa sumber, membedakan fakta dan opini, memberi konteks, menghindari fitnah, serta bersedia memperbaiki informasi yang salah.</p></>,idea:"Ketertiban informasi dimulai dari tanggung jawab atas kata."},
  {n:"IV",title:"Pengetahuan, literasi, dan adab belajar",text:<><p>Tradisi intelektual Raja Ali Haji mempertemukan agama, bahasa, sejarah, sastra, dan pemerintahan. Pengetahuan tidak dipandang sebagai kumpulan data yang terpisah dari pembentukan manusia.</p><p>Pendidikan kontemporer perlu melampaui kemampuan menemukan jawaban. Peserta didik harus mampu menilai sumber, memahami konteks, menguji alasan, mengakui keterbatasan, dan menggunakan pengetahuan bagi kemaslahatan. Teknologi dan kecerdasan buatan membantu belajar, tetapi tidak menggantikan tanggung jawab menilai kebenaran.</p></>,idea:"Literasi yang matang menghubungkan kecakapan, kerendahan hati, verifikasi, dan tanggung jawab."},
  {n:"V",title:"Masyarakat, musyawarah, dan tanggung jawab bersama",text:<><p>Etika sosial Raja Ali Haji menempatkan manusia dalam jaringan kewajiban: keluarga, sahabat, guru, pemimpin, dan rakyat. Kebaikan pribadi diuji melalui hubungan dengan orang lain.</p><p>Musyawarah masa kini bukan hanya berkumpul atau mengambil suara terbanyak. Ia menuntut informasi yang terbuka, kesempatan bicara yang bermakna, perhatian kepada kelompok terdampak, alasan keputusan, pembagian tugas, dan evaluasi hasil. Tanggung jawab bersama tidak boleh berubah menjadi keadaan ketika tidak seorang pun bertanggung jawab.</p></>,idea:"Partisipasi memperoleh makna ketika suara dihubungkan dengan alasan, tugas, dan tindak lanjut."},
  {n:"VI",title:"Kekuasaan, amanah, dan institusi",text:<><p><em>Tsamarat al-Muhimmah</em> menghubungkan kualitas pemerintahan dengan watak pejabat, pelaksanaan tugas, mahkamah, dan keadilan. Kekuasaan bukan milik yang boleh digunakan sesuka hati, melainkan amanah yang harus dipertanggungjawabkan.</p><p>Dalam tata kelola modern, arah moral itu memerlukan institusi: kewenangan yang jelas, prosedur, pencatatan, transparansi, pengelolaan konflik kepentingan, pengawasan, peninjauan, dan pemulihan. Moralitas memberi orientasi; institusi mencegah nasib rakyat bergantung pada kebaikan pribadi seorang pejabat.</p></>,idea:"Amanah harus diterjemahkan menjadi sistem yang dapat memeriksa penggunaan kekuasaan."},
  {n:"VII",title:"Dari warisan menuju tindakan",text:<><p>Warisan intelektual menjadi hidup ketika membantu kita memilih tindakan. Untuk setiap masalah, ajukan lima pertanyaan: apa yang harus ditertibkan dalam diri; kata dan informasi apa yang perlu diperiksa; pengetahuan apa yang belum tersedia; siapa yang harus diajak bermusyawarah; dan kekuasaan apa yang harus dibatasi atau dimintai pertanggungjawaban.</p><p>Kerangka ini dapat digunakan pada sekolah, kampus, pelayanan publik, organisasi, keluarga, dan ruang digital. Jawabannya tidak selalu tunggal, tetapi prosesnya harus memperkuat kebenaran, kemaslahatan, keadilan, serta kemampuan memperbaiki kesalahan.</p></>,idea:"Relevansi dibuktikan melalui keputusan dan praktik, bukan hanya melalui kekaguman kepada tokoh."},
];

const questions = [
  {q:"Aktualisasi pemikiran Raja Ali Haji berarti…",o:["Menyalin kerajaan secara utuh","Mempertemukan nilai dan pertanyaan lama dengan masalah baru","Menghapus konteks sejarah","Menganggap semua nasihat langsung menjadi hukum"],a:1},
  {q:"Tantangan karakter dalam ekonomi perhatian adalah…",o:["Terlalu banyak waktu untuk berpikir","Dorongan bereaksi cepat dan mengejar pengakuan","Tidak adanya media","Semua orang menolak teknologi"],a:1},
  {q:"Bahasa disebut infrastruktur kepercayaan karena…",o:["Semua kata selalu benar","Ketepatan kata memengaruhi pikiran dan hubungan sosial","Bahasa hanya milik ahli","Tata bahasa menggantikan etika"],a:1},
  {q:"Adab berbahasa digital mencakup…",o:["Menyebarkan dahulu, memeriksa kemudian","Memeriksa sumber dan memperbaiki kesalahan","Menghapus semua perbedaan pendapat","Mengikuti informasi terpopuler"],a:1},
  {q:"Peran manusia ketika memakai AI adalah…",o:["Menyerahkan seluruh penilaian kepada mesin","Tetap menilai sumber, konteks, alasan, dan akibat","Menganggap semua keluaran benar","Tidak perlu mengakui keterbatasan"],a:1},
  {q:"Musyawarah yang bermakna memerlukan…",o:["Kehadiran tanpa informasi","Informasi, kesempatan bicara, alasan, dan tindak lanjut","Suara pemimpin saja","Keputusan tanpa evaluasi"],a:1},
  {q:"Mengapa amanah membutuhkan institusi?",o:["Agar moralitas tidak diperlukan","Agar kuasa dapat dicatat, diawasi, diuji, dan dikoreksi","Agar pejabat bebas dari tanggung jawab","Agar prosedur selalu rahasia"],a:1},
  {q:"Hubungan moralitas dan institusi yang tepat adalah…",o:["Keduanya saling meniadakan","Moralitas memberi arah dan institusi membuat batas dapat dijalankan","Institusi menggantikan semua karakter","Moralitas cukup tanpa pengawasan"],a:1},
  {q:"Lima ranah aktualisasi dalam modul ialah…",o:["Diri, bahasa, pengetahuan, masyarakat, kekuasaan","Harta, pangkat, popularitas, teknologi, hiburan","Masa lalu, mitos, nostalgia, gelar, simbol","Sekolah, kantor, jalan, pasar, rumah"],a:0},
  {q:"Ukuran utama bahwa warisan intelektual tetap hidup adalah…",o:["Tokohnya sering dipuji","Karyanya membantu keputusan dan praktik yang bertanggung jawab","Semua teks dihafal","Tidak pernah ditafsirkan ulang"],a:1},
];

export default function ModuleEightLearning(){
  const audioRef=useRef<HTMLAudioElement|null>(null); const [audioError,setAudioError]=useState(false);
  const [active,setActive]=useState("introduction"); const [reflection,setReflection]=useState(""); const [essay,setEssay]=useState(""); const [answers,setAnswers]=useState<AnswerMap>({}); const [score,setScore]=useState<number|null>(null); const [readingDone,setReadingDone]=useState(false); const [analysisDone,setAnalysisDone]=useState(false); const [podcastDone,setPodcastDone]=useState(false); const [hydrated,setHydrated]=useState(false); const [saved,setSaved]=useState(false);
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const d=JSON.parse(raw);setReflection(d.reflection??"");setEssay(d.essay??"");setAnswers(d.answers??{});setScore(d.score??null);setReadingDone(Boolean(d.readingDone));setAnalysisDone(Boolean(d.analysisDone));setPodcastDone(Boolean(d.podcastDone));}}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(!hydrated)return;const id=window.setTimeout(()=>{void saveModuleProgress(STORAGE_KEY,8,{reflection,essay,answers,score,readingDone,analysisDone,podcastDone}).then(()=>{setSaved(true);window.setTimeout(()=>setSaved(false),1200)})},500);return()=>window.clearTimeout(id)},[reflection,essay,answers,score,readingDone,analysisDone,podcastDone,hydrated]);
  const reflectionWords=useMemo(()=>countWords(reflection),[reflection]); const essayWords=useMemo(()=>countWords(essay),[essay]); const reflectionDone=reflectionWords>=100; const essayDone=essayWords>=600; const quizDone=score!==null&&score>=70; const complete=readingDone&&analysisDone&&podcastDone&&reflectionDone&&essayDone&&quizDone;
  function submit(){let correct=0;questions.forEach((q,i)=>{if(Number(answers[i])===q.a)correct++});setScore(Math.round(correct/questions.length*100));setActive("result")}
  async function startPodcast(){try{setAudioError(false);await audioRef.current?.play()}catch{setAudioError(true)}}
  return <main className="min-h-screen bg-[#f7f4ef] text-slate-950"><section className="bg-slate-950 text-white"><div className="mx-auto max-w-7xl px-5 py-7 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-300"><ArrowLeft size={17}/> Kembali ke program</Link><div className="w-56"><div className="flex justify-between text-xs"><span>Progres Modul 8</span><span>{Math.round([readingDone,analysisDone,podcastDone,reflectionDone,essayDone,quizDone].filter(Boolean).length/6*100)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded bg-slate-700"><div className="h-full bg-amber-400" style={{width:`${Math.round([readingDone,analysisDone,podcastDone,reflectionDone,essayDone,quizDone].filter(Boolean).length/6*100)}%`}}/></div></div></div></div><div className="mx-auto max-w-7xl border-t border-slate-800 px-5 py-16 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 8 dari 8 • Modul penutup</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-6xl">Relevansi Pemikiran Raja Ali Haji bagi Dunia Kontemporer</h1><p className="mt-6 max-w-4xl text-lg leading-8 text-slate-300">Menyatukan pelajaran tentang diri, bahasa, pengetahuan, masyarakat, dan kekuasaan untuk membaca tantangan masa kini.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 150–180 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Sintesis</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai akhir, dan kuis</span></div></div></section>
  <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id,label],i)=><button key={id} onClick={()=>setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active===id?"bg-slate-950 text-white":"hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i+1).padStart(2,"0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved?"Tersimpan otomatis ✓":"Progres tersimpan di perangkat ini"}</div></aside><div className="min-w-0">
  {active==="introduction"&&<Panel eyebrow="Mulai di sini" title="Pengantar Modul 8"><p>Modul penutup ini mengajak Anda melakukan sintesis. Kita tidak bertanya apakah semua jawaban abad kesembilan belas dapat dipakai begitu saja, tetapi bagaimana warisan Raja Ali Haji membantu kita berpikir lebih tertib dan bertindak lebih bertanggung jawab hari ini.</p><h3>Tujuan pembelajaran</h3><ol><li>Membedakan aktualisasi kritis dari penyalinan masa lalu.</li><li>Menghubungkan diri, bahasa, pengetahuan, masyarakat, dan kekuasaan.</li><li>Menerapkan kerangka Raja Ali Haji pada satu masalah kontemporer.</li><li>Menyusun esai akhir yang memadukan materi Modul 1–8.</li></ol><blockquote>Warisan intelektual tidak hidup karena terus dipuji, tetapi karena terus menolong manusia membedakan yang benar, patut, adil, dan bermanfaat.</blockquote><Next onClick={()=>setActive("reading")}>Mulai membaca</Next></Panel>}
  {active==="reading"&&<Panel eyebrow="Bacaan sintesis • 40–50 menit" title="Dari Penyengat menuju dunia kontemporer"><p>Tujuh bagian berikut merangkum jalur pemikiran Raja Ali Haji dan menerjemahkannya secara kritis untuk persoalan masa kini.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Kajian pendukung</p><p className="mt-2 text-sm leading-6 text-slate-600">Buku akademik ini menempatkan Raja Ali Haji sebagai pemikir etika politik, ulama, sejarawan, dan pujangga—lebih luas daripada pengarang Gurindam Dua Belas semata.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka Pemikiran Etika Politik Raja Ali Haji <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e=>setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 8.</label><Next onClick={()=>setActive("analysis")}>Lanjut ke kerangka aktualisasi</Next></Panel>}
  {active==="analysis"&&<Panel eyebrow="Analisis integratif" title="Lima ranah aktualisasi"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Concept n="01" title="Diri" text="Kendalikan perhatian, nafsu, dan tindakan."/><Concept n="02" title="Bahasa" text="Periksa kata, makna, konteks, dan akibat."/><Concept n="03" title="Pengetahuan" text="Uji sumber, alasan, serta keterbatasan."/><Concept n="04" title="Masyarakat" text="Musyawarahkan dampak dan tanggung jawab."/><Concept n="05" title="Kekuasaan" text="Batasi, awasi, jelaskan, dan koreksi."/></div><h3>Cara menggunakan kerangka</h3><p>Pilih satu masalah nyata. Telusuri bagaimana masalah itu dipengaruhi kebiasaan pribadi, bahasa dan informasi, mutu pengetahuan, hubungan sosial, serta penggunaan kekuasaan. Setelah itu, rumuskan tindakan pada kelima ranah—bukan hanya menyalahkan satu orang.</p><h3>Contoh: hoaks pelayanan publik</h3><p>Diri perlu menahan dorongan membagikan; bahasa perlu membedakan fakta dan dugaan; pengetahuan perlu memeriksa sumber primer; masyarakat perlu menyediakan ruang klarifikasi; lembaga perlu membuka data, memberi alasan, dan mengoreksi informasi resmi yang keliru.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e=>setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami dan dapat menggunakan lima ranah aktualisasi.</label><Next onClick={()=>setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
  {active==="podcast"&&<Panel eyebrow="Podcast • 13 menit" title="Raja Ali Haji untuk Dunia yang Berubah"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Adab Raja Ali Haji: Penawar Krisis Digital</p><p className="mt-1 text-sm text-slate-400">Audio Overview • Bahasa Indonesia • 13:05</p></div></div><button type="button" onClick={startPodcast} className="mt-7 rounded-xl bg-amber-400 px-6 py-3 font-bold text-slate-950 hover:bg-amber-300">▶ Mulai podcast</button><audio ref={audioRef} className="mt-5 w-full" controls preload="metadata" onCanPlay={()=>setAudioError(false)} onError={()=>setAudioError(true)} onEnded={()=>setPodcastDone(true)}><source src="/audio/adab-raja-ali-haji-penawar-krisis-digital.m4a" type="audio/mp4"/>Peramban Anda tidak mendukung pemutar audio.</audio>{audioError?<p role="alert" className="mt-4 rounded-lg border border-red-400 bg-red-950 p-4 text-sm text-red-100">Audio belum ditemukan. Pastikan file berada di public/audio/adab-raja-ali-haji-penawar-krisis-digital.m4a, lalu muat ulang halaman.</p>:null}</div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan podcast</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p>Podcast membaca Raja Ali Haji sebagai arsitek peradaban yang menghubungkan etika personal, ketertiban bahasa, pengetahuan, tata sosial, dan tata kekuasaan. Pulau Penyengat diperkenalkan sebagai pusat pertukaran pengetahuan dunia Melayu.</p><p><em>Gurindam Dua Belas</em> dibaca sebagai arsitektur karakter berbasis sebab-akibat; <em>Bustan al-Katibin</em> dan <em>Kitab Pengetahuan Bahasa</em> menunjukkan bahasa sebagai instrumen ketertiban pikiran dan akuntabilitas.</p><p>Pembahasan kemudian diterapkan secara kritis pada hoaks, algoritma pemicu kemarahan, AI generatif, musyawarah semu, proporsionalitas, serta keputusan otomatis yang memengaruhi hak manusia. Mesin dapat membantu, tetapi tanggung jawab moral tetap berada pada manusia.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e=>setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mendengarkan podcast ini sampai selesai.</label><Next disabled={!podcastDone} onClick={()=>setActive("reflection")}>Lanjut ke refleksi</Next></Panel>}
  {active==="reflection"&&<Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi perjalanan belajar"><p>Dari tujuh modul sebelumnya, gagasan apa yang paling mengubah cara Anda melihat diri, bahasa, masyarakat, atau kekuasaan? Jelaskan perubahan tersebut dan satu tindakan nyata yang akan Anda lakukan.</p><textarea value={reflection} onChange={e=>setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={()=>setActive("essay")}>Simpan dan lanjut ke esai akhir</Next></Panel>}
  {active==="essay"&&<Panel eyebrow="Tugas akhir • 600–900 kata" title="Esai sintesis Program Dasar"><blockquote>Pilih satu persoalan kontemporer dan jelaskan bagaimana pemikiran Raja Ali Haji dapat membantu mendiagnosis masalah serta merancang respons pada ranah diri, bahasa, pengetahuan, masyarakat, dan kekuasaan.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan gagasan dari sekurang-kurangnya tiga karya atau tiga modul.</li><li>Jelaskan konteks persoalan dan pihak yang terdampak.</li><li>Bedakan nilai moral, pengetahuan yang diperlukan, dan desain kelembagaan.</li><li>Berikan rekomendasi yang konkret serta dapat dievaluasi.</li><li>Akui batas penerapan pemikiran historis pada konteks modern.</li></ul><textarea value={essay} onChange={e=>setEssay(e.target.value)} rows={24} placeholder="Mulai menulis esai akhir…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={600} max={900}/><Next disabled={!essayDone} onClick={()=>setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
  {active==="quiz"&&<Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 8"><div className="space-y-8">{questions.map((q,i)=><fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i+1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o,j)=><label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i])===j?"border-amber-600 bg-amber-50":"border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q8-${i}`} checked={Number(answers[i])===j} value={j} onChange={e=>setAnswers({...answers,[i]:e.target.value})} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
  {active==="result"&&<Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 8"><div className={`border p-7 ${complete?"border-emerald-300 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score??0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone?"Kuis lulus.":"Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan sintesis selesai"/><Req done={analysisDone} text="Kerangka aktualisasi selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai akhir minimal 600 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete?<div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 8 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menuntaskan seluruh Program Dasar Pemikiran Raja Ali Haji. Progres tersimpan di akun peserta dan sedang diperiksa untuk penerbitan sertifikat.</p><a href="/dashboard" className="mt-6 inline-flex rounded-xl bg-white px-6 py-4 font-bold text-emerald-800 hover:bg-emerald-50">Buka dashboard dan sertifikat</a></div>:<button onClick={()=>{setAnswers({});setScore(null);setActive("quiz")}} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
  </div></div></main>
}

function Panel({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}){return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>}
function Next({children,onClick,disabled=false}:{children:React.ReactNode;onClick:()=>void;disabled?:boolean}){return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>}
function Words({count,min,max}:{count:number;min:number;max:number}){return <p className={`text-sm font-semibold ${count>=min?"text-emerald-700":"text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count>=min?"✓":""}</p>}
function Req({done,text}:{done:boolean;text:string}){return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done?"text-emerald-600":"text-stone-300"} size={21}/><span className={done?"font-semibold":"text-slate-500"}>{text}</span></div>}
function Concept({n,title,text}:{n:string;title:string;text:string}){return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>}
function countWords(value:string){return value.trim()?value.trim().split(/\s+/).length:0}
function ReadingAccordion(){const[open,setOpen]=useState<number|null>(0);return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section,i)=><article key={section.n}><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open===i?<ChevronUp size={20}/>:<ChevronDown size={20}/>}</button>{open===i?<div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>:null}</article>)}</div>}
