import type { Metadata } from "next";
import Link from "next/link";
import ActionMatrix from "./ActionMatrix";
import s from "../ismi.module.css";
export const metadata: Metadata = {
  title: "ICSM 2026 — Dokumen & Tindak Lanjut | ISMI Kepri",
  description: "Dokumentasi ICSM 24–25 September 2026: resolusi, deklarasi Selat Malaka, himbauan bersama, analisis, serta 24 usulan tindak lanjut.",
  alternates: { canonical: "/ismi-kepri/icsm-2026" },
  openGraph: { title: "ICSM 2026 | ISMI Kepri", description: "Dokumen konferensi, analisis, dan matriks tindak lanjut Selat Malaka.", url: "https://www.hossibarani.com/ismi-kepri/icsm-2026", locale: "id_ID", type: "website", images: [{ url: "/ismi-kepri/logo.jpeg", width: 1080, height: 1080, alt: "ISMI Kepri" }] },
};
const documents = [
  {name:"Analisis mendalam hasil ICSM 2026",type:"Analisis",format:"PDF",file:"analisis-icsm-2026.pdf",text:"Pembacaan kritis delapan bahan substantif, isu strategis, dan arah pelaksanaan."},
  {name:"Matriks tindak lanjut ICSM 2026",type:"Rancangan kerja",format:"PDF",file:"matriks-icsm-2026.pdf",text:"24 usulan aksi, keluaran, indikator, calon pelaksana, risiko, dan ketergantungan."},
  {name:"Matriks kerja & pemantauan",type:"Rancangan kerja",format:"XLSX",file:"matriks-icsm-2026.xlsx",text:"Empat lembar: Rencana, Pemantauan, Cakupan, dan Petunjuk. Dapat disunting."},
  {name:"Resolusi dan rekomendasi ICSM 2026",type:"Dokumen konferensi",format:"PDF",file:"resolusi-rekomendasi-icsm-2026.pdf",text:"Salinan 10 resolusi serta rekomendasi kepada pemerintah pusat dan daerah."},
  {name:"Deklarasi Selat Malaka 2026",type:"Dokumen konferensi",format:"PDF",file:"deklarasi-selat-malaka-2026.pdf",text:"Salinan deklarasi yang memuat tujuh butir komitmen."},
  {name:"Himbauan bersama",type:"Dokumen konferensi",format:"PDF",file:"himbauan-bersama-2026.pdf",text:"Salinan lima butir himbauan bagi provinsi di koridor Selat Malaka."},
];
export default function IcsmPage(){return <>
  <section className={s.conferenceHero}><Link className={s.breadcrumb} href="/ismi-kepri">← ISMI Kepulauan Riau</Link><p className={s.eyebrow}>Dokumentasi kegiatan · 24–25 September 2026</p><h1>Selat Malaka:<br/><em>ruang hidup, ruang bersama.</em></h1><p className={s.lead}>The 1st International Conference on the Strait of Malacca<br/>Batam dan Tanjungpinang, Kepulauan Riau.</p><div className={s.actions}><a className={s.buttonGold} href="#dokumen">Baca & unduh dokumen ↓</a><a className={s.buttonOutline} href="#tindak-lanjut">Telusuri tindak lanjut ↓</a></div></section>
  <section className={s.section}><div className={s.splitHeading}><div><p className={s.eyebrow}>Tentang Konferensi</p><h2>Dari pernyataan bersama<br/>menuju agenda yang terukur.</h2></div><p>ICSM merupakan inisiatif Ikatan Sarjana Melayu Indonesia. Dokumentasi ini menghimpun hasil forum dan bahan kajian lanjutan dalam ruang digital ISMI Kepri.</p></div><div className={s.summaryGrid}>{[["10","Resolusi","Arah bersama dalam dokumen hasil konferensi."],["10","Rekomendasi","Lima untuk pemerintah pusat dan lima untuk daerah."],["24","Usulan aksi","Rancangan tindak lanjut dari hasil analisis."]].map(([n,title,text])=><article key={title}><strong>{n}</strong><h3>{title}</h3><p>{text}</p></article>)}</div><div className={s.notice}><strong>Memahami status dokumen</strong><p>Dokumen konferensi ditampilkan sesuai salinan yang tersedia. Analisis dan matriks merupakan bahan kajian serta usulan pelaksanaan, belum menunjukkan penetapan program, persetujuan anggaran, atau komitmen lembaga. Validasi versi final dan mandat pelaksana menjadi langkah pertama.</p></div></section>
  <section className={`${s.section} ${s.paperSection}`}><p className={s.eyebrow}>Pokok Pembacaan</p><h2>Tiga arah untuk percakapan lanjutan.</h2><div className={s.themeGrid}>{[["01","Masyarakat sebagai subjek","Partisipasi warga pesisir, perlindungan ruang hidup, dan akses terhadap manfaat perlu menjadi ukuran utama."],["02","Ekonomi yang merawat laut","Nilai tambah perikanan, layanan maritim, pendidikan, dan inovasi perlu ditautkan dengan daya dukung ekologi."],["03","Pelaksanaan yang bisa ditelusuri","Mandat, pembagian peran, data awal, pendanaan, indikator, dan bukti hasil diperlukan agar rekomendasi dapat dijalankan."]].map(([n,title,text])=><article key={n} className={s.theme}><span className={s.number}>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className={s.sourceNote}>Ringkasan editorial dari analisis mendalam ICSM 2026. Penjelasan dan daftar sumber tersedia dalam PDF analisis.</p></section>
  <section id="dokumen" className={s.section}><div className={s.splitHeading}><div><p className={s.eyebrow}>Pusat Dokumen</p><h2>Baca sumbernya.<br/>Lanjutkan pemikirannya.</h2></div><p>Dokumen konferensi, analisis, dan bahan kerja disajikan terpisah agar asal serta tujuan penggunaannya jelas.</p></div><div className={s.documentGrid}>{documents.map(d=><article className={s.document} key={d.file}><div className={s.documentMeta}><span>{d.type}</span><span>{d.format}</span></div><h3>{d.name}</h3><p>{d.text}</p><a href={`/ismi-kepri/dokumen/${d.file}`} download>Unduh {d.format} <span aria-hidden="true">↓</span><span className={s.srOnly}> — {d.name}</span></a></article>)}</div></section>
  <section id="tindak-lanjut" className={`${s.section} ${s.paperSection}`}><div className={s.splitHeading}><div><p className={s.eyebrow}>Matriks Tindak Lanjut</p><h2>24 usulan.<br/>Satu kerangka kerja bersama.</h2></div><p>Telusuri topik, calon pelaksana, target, dan bukti yang diperlukan. Seluruh aksi masih berstatus <strong>Usulan</strong>.</p></div><ActionMatrix/><div className={s.actions}><a className={s.buttonDark} href="/ismi-kepri/dokumen/matriks-icsm-2026.xlsx" download>Unduh Excel untuk pemantauan ↓</a><a className={s.textLink} href="/ismi-kepri/dokumen/matriks-icsm-2026.pdf" download>Unduh versi PDF ↓</a></div></section>
  <section className={s.section}><p className={s.eyebrow}>Langkah Awal yang Diusulkan</p><h2>Mulai dengan mandat dan bukti.</h2><div className={s.steps}>{[["01–15","Validasi hasil","Cocokkan versi dokumen, status adopsi, dan sumber setiap butir."],["01–30","Sepakati tata kerja","Tetapkan mandat, penghubung, pembagian tugas, dan mekanisme keputusan."],["Tahap berikutnya","Bangun data awal","Susun baseline dan pilih prioritas bersama pihak yang terdampak."]].map(([time,title,text])=><article key={title}><span>{time}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className={s.sourceNote}>Rentang angka menunjukkan hari sejak T0 yang harus disepakati, bukan tanggal pelaksanaan yang telah ditetapkan.</p></section>
</>;}
