import ExcelJS from 'exceljs';
import {PDFDocument,StandardFonts,rgb,type PDFPage} from 'pdf-lib';
import {PROGRAM_STATUS,programTotals,type ProgramReport} from './program';
import {rupiah} from './dues';
export async function programExcel(report:ProgramReport){
 const book=new ExcelJS.Workbook();book.creator='PW Persis Kepri';book.created=new Date();const sheet=book.addWorksheet('Anggaran dan realisasi'),t=programTotals(report);
 sheet.addRow([`PROGRAM KERJA PW PERSIS KEPRI ${report.year}`]);sheet.addRow(['Anggaran tercatat',t.budget]);sheet.addRow(['Realisasi tertaut',t.spent]);sheet.addRow(['Sisa anggaran',t.remaining]);sheet.addRow(['Pengeluaran belum tertaut',t.unassigned]);sheet.addRow(['Rekap termasuk program dibatalkan. Hanya pengeluaran kas aktif yang dihitung.']);sheet.addRow(['Pembukuan mulai',report.cash_start_date||'Belum dimulai']);sheet.addRow([]);
 sheet.addRow(['Program','Bidang','Penanggung jawab','Mulai','Selesai','Status','Progres (%)','Anggaran (Rp)','Realisasi (Rp)','Sisa (Rp)','Sumber dana (rencana)','Target','Laporan perkembangan','ID program']);
 for(const p of report.programs)sheet.addRow([p.title,p.division,p.responsible,p.start_date,p.end_date,PROGRAM_STATUS[p.status],p.progress,p.budget,p.spent,p.budget-p.spent,p.funding_source,p.target,p.report,p.id]);
 sheet.columns.forEach((c,i)=>{c.width=[35,23,28,15,15,19,16,23,23,23,40,60,60,40][i];});sheet.eachRow(r=>{r.alignment={wrapText:true,vertical:'top'};});for(let i=2;i<=5;i++)sheet.getCell(`B${i}`).numFmt='#,##0';for(const col of ['H','I','J'])sheet.getColumn(col).numFmt='#,##0';sheet.getRow(1).font={bold:true,size:16};sheet.getRow(9).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(9).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF065F46'}};sheet.views=[{state:'frozen',ySplit:9}];sheet.autoFilter={from:'A9',to:`N${Math.max(9,sheet.rowCount)}`};
 const unassigned=book.addWorksheet('Belum ditautkan');unassigned.addRow(['Tanggal','Penerima','Uraian','Nominal (Rp)','ID transaksi']);for(const e of report.unassigned)unassigned.addRow([e.transacted_on,e.party,e.description,e.amount,e.id]);unassigned.columns.forEach((c,i)=>{c.width=[15,30,60,23,40][i];});unassigned.getColumn(4).numFmt='#,##0';unassigned.getRow(1).font={bold:true};unassigned.eachRow(r=>{r.alignment={wrapText:true,vertical:'top'};});
 return new Uint8Array(await book.xlsx.writeBuffer());
}
export async function programPdf(report:ProgramReport){
 const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold),green=rgb(.02,.31,.23),gray=rgb(.25,.3,.33);let page!:PDFPage,y=0;
 const clean=(s:string)=>Array.from(s).map(c=>{if(/\s/.test(c))return ' ';try{font.encodeText(c);return c;}catch{return '?';}}).join('');
 const addPage=()=>{page=doc.addPage([842,595]);y=550;page.drawText(`PW PERSIS KEPRI | PROGRAM & ANGGARAN ${report.year}`,{x:35,y,size:15,font:bold,color:green});y-=30;};
 const text=(s:string,strong=false,size=10)=>{const f=strong?bold:font;let line='';const draw=()=>{if(y<45)addPage();page.drawText(line,{x:35,y,size,font:f,color:strong?green:gray});y-=size+5;line='';};for(const word of clean(s).split(/\s+/)){const candidate=line+(line?' ':'')+word;if(f.widthOfTextAtSize(candidate,size)<=770){line=candidate;continue;}if(line)draw();for(const c of word){if(f.widthOfTextAtSize(line+c,size)>770)draw();line+=c;}}if(line)draw();};
 addPage();const t=programTotals(report);text(`Anggaran ${rupiah(t.budget)} | Realisasi ${rupiah(t.spent)} | Sisa ${rupiah(t.remaining)}`,true,12);text(`Pengeluaran belum tertaut: ${rupiah(t.unassigned)} (${report.unassigned.length} transaksi). ${t.over} program melebihi anggaran.`);text(`Pembukuan mulai: ${report.cash_start_date||'belum ditetapkan'}. Rekap termasuk program dibatalkan; hanya belanja kas aktif yang dihitung.`);text(`Diunduh ${new Date().toLocaleString('id-ID',{timeZone:'Asia/Jakarta'})} WIB. Laporan mengikuti status saat diunduh; progres kegiatan diperbarui oleh bendahara.`);y-=12;
 if(!report.programs.length)text('Belum ada program pada tahun ini.');
 for(const p of report.programs){if(y<160)addPage();text(p.title,true,12);text(`${p.division} | Penanggung jawab: ${p.responsible} | ${p.start_date} - ${p.end_date}`);text(`${PROGRAM_STATUS[p.status]} | Progres kegiatan ${p.progress}% | ${p.expense_count} pengeluaran aktif`);text(`Anggaran ${rupiah(p.budget)} | Realisasi ${rupiah(p.spent)} | Sisa ${rupiah(p.budget-p.spent)}${p.spent>p.budget?' | MELEBIHI ANGGARAN':''}`,true);text(`Rencana sumber dana: ${p.funding_source}`);text(`Target: ${p.target}`);text(`Laporan perkembangan: ${p.report||'Belum ada laporan.'}`);y-=16;}
 if(report.unassigned.length){if(y<120)addPage();text('PENGELUARAN BELUM DITAUTKAN',true,12);for(const e of report.unassigned)text(`${e.transacted_on} | KAS-${e.id.slice(0,8)} | ${e.party} | ${rupiah(e.amount)} | ${e.description}`);}
 const pages=doc.getPages();pages.forEach((p,i)=>p.drawText(`Halaman ${i+1}/${pages.length} | Dokumen internal PW Persis Kepri`,{x:35,y:20,size:8,font,color:gray}));return doc.save();
}
