import type {Metadata} from 'next';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/server';
import {linkCurrentMember} from '@/lib/persis/master-server';
import {APPLICATION_STATUS} from '@/lib/persis/application';
import {REGIONS,monthLabel} from '@/lib/persis/dues';
import {submitApplication} from './actions';
export const metadata:Metadata={title:'Pendaftaran Data Anggota Persis Kepri',robots:{index:false,follow:false}};
export const dynamic='force-dynamic';
const input='w-full rounded-lg border border-slate-300 bg-white p-3 text-base font-normal text-slate-900';
export default async function ApplicationPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const p=await searchParams,client=await createClient();const {data:{user}}=await client.auth.getUser();
 let linkError='';if(user)try{await linkCurrentMember();}catch{linkError='Status keanggotaan belum dapat diperiksa. Muat ulang halaman sebelum mengirim pendaftaran.';}
 const [memberResult,applications]=user?await Promise.all([
  client.from('persis_members').select('id,full_name,region,start_month').eq('user_id',user.id).maybeSingle(),
  client.from('persis_member_applications').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(20),
 ]):[null,null];
 const member=memberResult?.data,latest=applications?.data?.[0],loadError=linkError||((memberResult?.error||applications?.error)?'Data belum dapat dimuat. Silakan muat ulang halaman.':'');
 const canApply=user&&!member&&!loadError&&(!latest||latest.status==='rejected');
 return <div lang="id" className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><div className="mx-auto max-w-3xl"><Link href="/persis-kepri/iuran" className="text-sm font-semibold text-emerald-800 underline">Kembali ke iuran anggota</Link><p className="mt-6 text-sm font-bold uppercase tracking-widest text-emerald-800">PW Persis Kepulauan Riau</p><h1 className="mt-2 text-3xl font-bold">Daftarkan data anggota</h1><p className="mt-4 leading-7 text-slate-600">Isi data Anda, kirim untuk diperiksa, lalu pantau persetujuan bendahara di halaman ini. Pendaftaran yang disetujui masuk ke master anggota. Bulan mulai wajib iuran ditetapkan oleh bendahara.</p>
 {!user?<section className="mt-7 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Masuk atau buat akun terlebih dahulu</h2><p className="mt-3 leading-7 text-slate-600">Gunakan email pribadi yang dapat Anda akses. Jika membuat akun baru, verifikasi email sebelum mengisi data anggota.</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/login?next=%2Fpersis-kepri%2Fpendaftaran" className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Masuk & isi data</Link><Link href="/persis-kepri/daftar" className="rounded-lg border border-emerald-800 px-5 py-3 font-bold text-emerald-900">Buat akun</Link></div></section>:<>
 <p className="mt-6 break-all rounded-lg bg-emerald-50 p-4 text-sm text-emerald-950">Email akun: <strong>{user.email}</strong></p>
 {p.error&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">{p.error}</p>}{p.success&&<p role="status" className="mt-4 rounded-lg bg-emerald-50 p-4 text-emerald-900">Data berhasil dikirim. Silakan tunggu pemeriksaan bendahara.</p>}{loadError&&<p role="alert" className="mt-4 rounded-lg bg-red-50 p-4 text-red-800">{loadError}</p>}
 {member&&<section className="mt-6 rounded-xl border border-emerald-200 bg-white p-6"><h2 className="text-xl font-bold text-emerald-950">Anda sudah tercatat dalam master anggota</h2><p className="mt-3">{member.full_name} · {member.region}</p><p className="mt-2 text-sm text-slate-600">Mulai wajib iuran: {member.start_month?monthLabel(member.start_month):'belum ditetapkan bendahara'}.</p><div className="mt-5 flex flex-wrap gap-3"><Link className="font-semibold text-emerald-800 underline" href="/persis-kepri/iuran">Catat pembayaran</Link><Link className="font-semibold text-emerald-800 underline" href="/persis-kepri/iuran/kewajiban">Lihat kewajiban saya</Link></div></section>}
 {latest&&!member&&<section className="mt-6 rounded-xl border border-amber-200 bg-white p-6"><h2 className="text-xl font-bold">Status: {APPLICATION_STATUS[latest.status as keyof typeof APPLICATION_STATUS]}</h2><p className="mt-2 text-sm text-slate-600">Diajukan {new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date(latest.created_at))}</p>{latest.review_note&&<p className="mt-3 whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-4 leading-7"><strong>Catatan bendahara:</strong> {latest.review_note}</p>}{latest.status==='pending'&&<p className="mt-3 leading-7 text-slate-600">Data sedang menunggu persetujuan. Pendaftaran ini belum menetapkan kewajiban iuran Anda.</p>}{latest.status==='rejected'&&<p className="mt-3 leading-7 text-slate-600">Perbaiki data sesuai catatan bendahara, kemudian kirim ulang formulir di bawah.</p>}</section>}
 {canApply&&<form action={submitApplication} className="mt-6 grid gap-5 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">{latest?'Perbaiki data anggota':'Data anggota'}</h2><label className="grid gap-2 text-sm font-semibold">Nama lengkap<input name="full_name" required minLength={2} maxLength={120} defaultValue={latest?.full_name||String(user.user_metadata?.full_name||'')} autoComplete="name" className={input}/></label><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Nomor anggota / KTA (jika ada)<input name="member_number" maxLength={60} defaultValue={latest?.member_number||''} className={input}/></label><label className="grid gap-2 text-sm font-semibold">Daerah<select name="region" defaultValue={latest?.region||''} required className={input}><option value="" disabled>Pilih daerah</option>{REGIONS.map(r=><option key={r}>{r}</option>)}</select></label></div><label className="grid gap-2 text-sm font-semibold">Catatan untuk bendahara (opsional)<textarea name="note" maxLength={500} rows={3} defaultValue={latest?.note||''} className={input}/></label><label className="flex items-start gap-3 text-sm leading-6"><input name="declaration" value="yes" type="checkbox" required className="mt-1 h-4 w-4 shrink-0"/>Saya menyatakan data ini benar dan mengajukannya untuk pemeriksaan bendahara PW Persis Kepri.</label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">{latest?'Kirim ulang data':'Kirim pendaftaran'}</button></form>}
 {!!applications?.data?.length&&<details className="mt-6 rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold">Riwayat pengajuan (20 terakhir)</summary><ul className="mt-4 space-y-4">{applications.data.map(a=><li key={a.id} className="border-t border-slate-100 pt-4 text-sm leading-6"><strong>{APPLICATION_STATUS[a.status as keyof typeof APPLICATION_STATUS]}</strong> · {a.full_name} · {a.region}<p>{new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(a.created_at))} WIB</p>{a.review_note&&<p className="whitespace-pre-wrap break-words">Catatan: {a.review_note}</p>}</li>)}</ul></details>}
 </>}
 </div></div>;
}
