import type {Metadata} from 'next';
import {requireTreasurer} from '@/lib/persis/master-server';
import {monthLabel,rupiah} from '@/lib/persis/dues';
import {addRate} from '../master-actions';
import TreasuryNav from '../TreasuryNav';
export const metadata:Metadata={title:'Ketentuan Iuran Persis Kepri',robots:{index:false,follow:false}};
export const dynamic='force-dynamic';
export default async function RatesPage({searchParams}:{searchParams:Promise<{error?:string;success?:string}>}){
 const {client}=await requireTreasurer();const p=await searchParams;
 const {data,error}=await client.from('persis_rates').select('*').order('effective_month',{ascending:false}).limit(1000);
 const input='w-full rounded-lg border border-slate-300 p-3 text-base font-normal';
 return <div lang="id" className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-bold">Ketentuan iuran bulanan</h1><p className="mt-3 leading-7 text-slate-600">Tarif umum berlaku sejak bulan yang ditetapkan, sampai ada ketentuan berikutnya. Bulan sebelum tarif pertama tidak dihitung sebagai tunggakan.</p><TreasuryNav/>
 {p.error&&<p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-red-800">{p.error}</p>}{p.success&&<p role="status" className="mb-5 rounded-xl bg-emerald-50 p-4 text-emerald-900">Ketentuan berhasil disimpan.</p>}
 <form action={addRate} className="grid gap-5 rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Tetapkan ketentuan</h2><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-semibold">Berlaku mulai bulan<input name="effective_month" type="month" min="2020-01" max="2100-12" required className={input}/></label><label className="grid gap-2 text-sm font-semibold">Iuran per anggota per bulan (Rp)<input name="amount" type="number" min={1} max={100000000} step={1} required className={input}/></label></div><label className="grid gap-2 text-sm font-semibold">Tanggal jatuh tempo setiap bulan (1–28)<input name="due_day" type="number" min={1} max={28} step={1} required className={input}/><span className="font-normal text-slate-600">Sisa pembayaran menjadi tunggakan mulai hari setelah tanggal ini (WIB).</span></label><label className="grid gap-2 text-sm font-semibold">Dasar keputusan / keterangan<textarea name="reference" minLength={3} maxLength={300} required rows={2} className={input} placeholder="Nomor keputusan atau hasil rapat pengurus"/></label><p className="rounded-lg bg-amber-50 p-4 text-sm leading-6 text-amber-950">Periksa sebelum menyimpan. Riwayat ketentuan dipertahankan. Ketentuan baru untuk bulan lampau akan menghitung ulang bulan tersebut hingga sebelum ketentuan berikutnya.</p><label className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" required className="mt-1 h-4 w-4"/>Saya telah memeriksa nominal, bulan berlaku, dan dasar keputusannya.</label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Simpan ketentuan</button></form>
 <h2 className="mb-4 mt-8 text-2xl font-bold">Riwayat ketentuan</h2>{error?<p role="alert">Ketentuan belum dapat dimuat.</p>:!data?.length?<p className="rounded-xl border border-dashed border-slate-300 p-6">Belum ada nominal yang ditetapkan. Sistem belum menghitung tunggakan.</p>:<div className="space-y-3">{data.map(r=><article key={r.id} className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-bold">Mulai {monthLabel(r.effective_month)} · {rupiah(r.amount)}/bulan</h3><p className="mt-2 text-sm text-slate-600">Jatuh tempo tanggal {r.due_day} setiap bulan.</p><p className="mt-3 break-words leading-7">{r.reference}</p></article>)}</div>}
 </div></div>;
}
