import type {Member,Rate,Payment} from '@/lib/persis/billing';
import {memberBills,totals} from '@/lib/persis/billing';
import {monthLabel,rupiah} from '@/lib/persis/dues';
export default function BillingReport({members,rates,payments,year,today}:{members:Member[];rates:Rate[];payments:Payment[];year:number;today:string}){
 const rows=members.map(member=>({member,bills:memberBills(member,rates,payments,year,today)}));
 const sum=totals(rows.flatMap(r=>r.bills));
 return <>
  <p className="mb-5 text-sm leading-6 text-slate-600">Posisi per {today.split('-').reverse().join('/')} WIB untuk kewajiban tahun {year}. Pembayaran dihitung berdasarkan status verifikasi saat ini. Lebih bayar pada satu bulan tidak otomatis menutup bulan lain.</p>
  <dl className="mb-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Kewajiban terhitung',sum.expected],['Pembayaran terverifikasi',sum.paid],['Menunggu verifikasi',sum.pending],['Sisa jatuh tempo',sum.arrears]].map(([label,value])=><div key={String(label)} className="rounded-xl border border-slate-200 bg-white p-5"><dt className="text-sm text-slate-600">{label}</dt><dd className="mt-2 text-xl font-bold text-emerald-950">{rupiah(Number(value))}</dd></div>)}</dl>
  <p className="mb-5 text-sm leading-6 text-slate-600">Ringkasan mengikuti anggota yang ditampilkan. Sisa jatuh tempo belum dikurangi pengajuan yang menunggu verifikasi. Penerimaan di luar masa wajib tetap tampil sebagai pembayaran, bukan pengurang bulan lain.</p>
  {sum.unknown>0&&<p role="status" className="mb-5 rounded-xl bg-amber-50 p-4 leading-7 text-amber-950">Perhitungan belum lengkap: ada bulan mulai wajib atau tarif yang belum ditetapkan. Bulan tersebut tidak dinyatakan lunas maupun menunggak.</p>}
  {!members.length?<p className="rounded-xl border border-dashed border-slate-300 p-6">Belum ada anggota yang sesuai. Lengkapi master anggota atau ubah filter.</p>:<>
   <div className="overflow-x-auto rounded-xl border border-slate-200 bg-white" tabIndex={0} aria-label="Matriks iuran, geser horizontal untuk melihat seluruh bulan"><table className="w-full border-collapse text-sm"><caption className="p-4 text-left font-semibold">Matriks kewajiban anggota · {year}</caption><thead className="bg-emerald-950 text-white"><tr><th scope="col" className="min-w-48 p-4 text-left">Anggota</th>{Array.from({length:12},(_,i)=><th scope="col" key={i} className="min-w-32 p-3 text-left">{new Intl.DateTimeFormat('id-ID',{month:'short',timeZone:'UTC'}).format(new Date(Date.UTC(year,i,1)))}</th>)}<th scope="col" className="min-w-40 p-4 text-left">Sisa jatuh tempo</th></tr></thead><tbody>{rows.map(({member,bills})=><tr key={member.id} className="border-t border-slate-200 align-top"><th scope="row" className="p-4 text-left font-semibold">{member.full_name}<span className="mt-1 block text-sm font-normal text-slate-600">{member.region}</span>{!member.user_id&&<span className="mt-2 block text-sm font-normal text-amber-900">Akun belum terhubung</span>}</th>{bills.map(b=><td key={b.month} className={`p-3 ${b.arrears>0?'bg-red-50 text-red-900':b.status.startsWith('Lunas')?'bg-emerald-50 text-emerald-900':'text-slate-600'}`}><span className="font-semibold">{b.status}</span>{b.expected!==null&&<span className="mt-2 block">Sisa {rupiah(b.remaining)}</span>}{b.pending>0&&<span className="mt-1 block text-amber-900">Diajukan {rupiah(b.pending)}</span>}</td>)}<td className="p-4 font-bold text-red-900">{rupiah(totals(bills).arrears)}</td></tr>)}</tbody></table></div>
   <h2 className="mb-4 mt-8 text-2xl font-bold">Rincian per anggota</h2><div className="space-y-3">{rows.map(({member,bills})=><details key={member.id} className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-bold">{member.full_name} · sisa jatuh tempo {rupiah(totals(bills).arrears)}</summary><p className="mt-3 text-sm leading-6 text-slate-600">Mulai wajib: {member.start_month?monthLabel(member.start_month):'belum ditetapkan'}. Bulan terakhir: {member.end_month?monthLabel(member.end_month):'berlanjut'}.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{bills.map(b=><div key={b.month} className="rounded-lg border border-slate-200 p-4 text-sm leading-6"><h3 className="font-bold">{monthLabel(b.month)} · {b.status}</h3><p>Kewajiban: {b.expected===null?'belum dihitung':rupiah(b.expected)}</p><p>Terverifikasi: {rupiah(b.paid)}</p>{b.pending>0&&<p>Menunggu verifikasi: {rupiah(b.pending)}</p>}{b.due&&<p>Jatuh tempo: {b.due.split('-').reverse().join('/')}</p>}{b.surplus>0&&<p>Lebih bayar: {rupiah(b.surplus)}</p>}{b.arrears>0&&<p className="font-semibold text-red-800">Sisa jatuh tempo: {rupiah(b.arrears)}</p>}</div>)}</div></details>)}</div>
  </>}
 </>;
}
