import Link from "next/link";
import { classroomSession } from "@/lib/lexnusa/mayantara/access";
import { assignments, getAssignment, coursePath, roomPath, membershipLabel, reviewLabel } from "@/lib/lexnusa/mayantara/course";
import { requestSeat } from "../actions";
import ActionForm from "../ActionForm";
import Editor from "./Editor";
export const metadata={title:"Ruang Kelas Hukum Kejahatan Mayantara | LexNusa",robots:{index:false,follow:false}};
export default async function Page({searchParams}:{searchParams:Promise<{assignment?:string}>}){
 const q=await searchParams;const assignment=getAssignment(q.assignment??"")??assignments[0];
 const {db,user}=await classroomSession(roomPath+"?assignment="+assignment.id);
 const [{data:member,error},{data:staff}]=await Promise.all([db.from("lexnusa_mayantara_members").select("*").eq("user_id",user.id).maybeSingle(),db.from("lexnusa_mayantara_staff").select("user_id").eq("user_id",user.id).maybeSingle()]);
 if(error)return <main className="p-10"><h1>Ruang kelas sementara tidak tersedia</h1><p>Muat ulang halaman sebelum mengisi tugas.</p></main>;
 if(!member)return <main className="mx-auto max-w-xl space-y-6 px-6 py-14"><Link href={coursePath} className="underline">Panduan kuliah</Link><h1 className="text-3xl font-bold">Ajukan keanggotaan kelas Hukum Kejahatan Mayantara</h1><p>Dosen akan mencocokkan nama dan NIM Anda dengan daftar kelas. Tugas dan nilai Anda hanya dapat diakses oleh Anda dan dosen yang ditugaskan.</p>{staff&&<Link href={coursePath+"/lecturer"} className="block text-teal-800 underline">Buka dasbor dosen</Link>}<ActionForm action={requestSeat}><label className="block">Nama lengkap<input name="display_name" required minLength={2} maxLength={120} defaultValue={user.user_metadata?.full_name??""} className="mt-2 w-full rounded-lg border p-3"/></label><label className="block">Nomor Induk Mahasiswa (NIM)<input name="student_number" required minLength={2} maxLength={50} className="mt-2 w-full rounded-lg border p-3"/></label><button className="rounded-lg bg-teal-800 px-5 py-3 font-bold text-white">Ajukan keanggotaan kelas</button></ActionForm></main>;
 const [{data:works,error:workError},{data:reviews,error:reviewError}]=await Promise.all([db.from("lexnusa_mayantara_work").select("*").eq("user_id",user.id).order("version_number",{ascending:false}),db.from("lexnusa_mayantara_reviews").select("*").eq("student_id",user.id).order("created_at",{ascending:false})]);
 if(workError||reviewError)return <main className="p-10"><h1>Riwayat tugas tidak dapat dimuat</h1><p>Muat ulang halaman sebelum melakukan perubahan.</p></main>;
 const history=works?.filter(w=>w.assignment===assignment.id)??[];const latest=history[0];
 return <main className="mx-auto max-w-6xl space-y-8 px-6 py-12"><div className="flex flex-wrap gap-5"><Link href={coursePath} className="text-teal-800 underline">Panduan dan materi kuliah</Link>{staff&&<Link href={coursePath+"/lecturer"} className="text-teal-800 underline">Dasbor dosen</Link>}</div><h1 className="text-4xl font-bold">Ruang Kelas Hukum Kejahatan Mayantara</h1><p>{member.display_name} · {member.student_number} · Keanggotaan: <strong>{membershipLabel(member.status)}</strong></p>
 <div className="rounded-xl bg-amber-50 p-5">Bantuan AI belum tersedia. Kerjakan tugas secara manual; tidak perlu membeli layanan AI.</div>
 <nav aria-label="Tugas" className="grid gap-3 sm:grid-cols-2">{assignments.map(a=>{const w=works?.find(w=>w.assignment===a.id);const r=reviews?.find(r=>r.work_id===w?.id);return <Link aria-current={a.id===assignment.id?"page":undefined} key={a.id} href={roomPath+"?assignment="+a.id} className={`rounded-xl border p-4 ${a.id===assignment.id?"border-teal-700 bg-teal-50":"bg-white"}`}><strong>{a.title}</strong><span className="mt-2 block text-sm">{r?reviewLabel(r.decision)+" · "+r.score+"/100":w?.submitted?"Menunggu tinjauan":w?"Draf tersimpan":"Belum dimulai"}</span></Link>;})}</nav>
 <article className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">{assignment.title}</h2><p className="text-sm font-semibold text-teal-800">{assignment.suggested}</p><p className="leading-7">{assignment.case}</p><p className="leading-7"><strong>Hasil yang dikumpulkan:</strong> {assignment.deliverable}</p><ul className="list-disc space-y-2 pl-5">{assignment.questions.map(question=><li key={question}>{question}</li>)}</ul><Link href={coursePath+"#assessment"} className="inline-block text-teal-800 underline">Bobot penilaian dan rubrik RPS</Link><p className="text-sm text-slate-600">Batas waktu pengumpulan belum diatur. Ikuti petunjuk perkuliahan dari dosen.</p></article>
 {member.status==="active"?<Editor key={assignment.id} assignment={assignment.id} initial={latest??null}/>:<p role="status" className="rounded-xl border border-amber-300 p-5">{member.status==="pending"?"Pengajuan Anda menunggu persetujuan dosen. Anda dapat membaca seluruh materi selama menunggu.":"Akses pengumpulan ditangguhkan. Hubungi dosen; tugas sebelumnya tetap dapat dibaca."}</p>}
 <section><h2 className="text-2xl font-bold">Riwayat versi dan umpan balik</h2>{!history.length&&<p className="mt-3">Belum ada versi tersimpan untuk tugas ini.</p>}{history.map(w=>{const review=reviews?.find(r=>r.work_id===w.id);return <details key={w.id} className="mt-4 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">Versi {w.version_number} · {w.submitted?"Dikumpulkan":"Draf"} · {new Date(w.created_at).toLocaleString("id-ID",{timeZone:"Asia/Jakarta"})} WIB</summary><h3 className="mt-4 font-bold">Analisis</h3><p className="mt-2 whitespace-pre-wrap break-words">{w.answer||"Draf kosong"}</p><h3 className="mt-4 font-bold">Sumber</h3><p className="whitespace-pre-wrap break-words">{w.sources}</p><h3 className="mt-4 font-bold">Refleksi</h3><p className="whitespace-pre-wrap break-words">{w.reflection}</p>{review?<div className="mt-5 rounded-lg bg-teal-50 p-4"><strong>{reviewLabel(review.decision)} · {review.score}/100</strong><p className="mt-2 whitespace-pre-wrap break-words">{review.feedback}</p></div>:<p className="mt-4">Belum ada keputusan dosen untuk versi ini.</p>}</details>;})}</section></main>;
}
