import Link from "next/link";
import { classroomSession } from "@/lib/lexnusa/mayantara/access";
import { assignments, getAssignment, coursePath, roomPath } from "@/lib/lexnusa/mayantara/course";
import { requestSeat } from "../actions";
import ActionForm from "../ActionForm";
import Editor from "./Editor";
export const metadata={title:"My Cybercrime Law Classroom | LexNusa",robots:{index:false,follow:false}};
export default async function Page({searchParams}:{searchParams:Promise<{assignment?:string}>}){
 const q=await searchParams;const assignment=getAssignment(q.assignment??"")??assignments[0];
 const {db,user}=await classroomSession(roomPath+"?assignment="+assignment.id);
 const [{data:member,error},{data:staff}]=await Promise.all([db.from("lexnusa_mayantara_members").select("*").eq("user_id",user.id).maybeSingle(),db.from("lexnusa_mayantara_staff").select("user_id").eq("user_id",user.id).maybeSingle()]);
 if(error)return <main className="p-10"><h1>Classroom temporarily unavailable</h1><p>Please refresh before entering work.</p></main>;
 if(!member)return <main className="mx-auto max-w-xl space-y-6 px-6 py-14"><Link href={coursePath} className="underline">Course guide</Link><h1 className="text-3xl font-bold">Request a place in Hukum Kejahatan Mayantara</h1><p>Your lecturer will check your name and student number against the class list. Your work and grades are private to you and assigned lecturers.</p>{staff&&<Link href={coursePath+"/lecturer"} className="block text-teal-800 underline">Open lecturer dashboard</Link>}<ActionForm action={requestSeat}><label className="block">Full name<input name="display_name" required minLength={2} maxLength={120} defaultValue={user.user_metadata?.full_name??""} className="mt-2 w-full rounded-lg border p-3"/></label><label className="block">Student number / NIM<input name="student_number" required minLength={2} maxLength={50} className="mt-2 w-full rounded-lg border p-3"/></label><button className="rounded-lg bg-teal-800 px-5 py-3 font-bold text-white">Request class membership</button></ActionForm></main>;
 const [{data:works,error:workError},{data:reviews,error:reviewError}]=await Promise.all([db.from("lexnusa_mayantara_work").select("*").eq("user_id",user.id).order("version_number",{ascending:false}),db.from("lexnusa_mayantara_reviews").select("*").eq("student_id",user.id).order("created_at",{ascending:false})]);
 if(workError||reviewError)return <main className="p-10"><h1>Work history could not be loaded</h1><p>Refresh before making changes.</p></main>;
 const history=works?.filter(w=>w.assignment===assignment.id)??[];const latest=history[0];
 return <main className="mx-auto max-w-6xl space-y-8 px-6 py-12"><div className="flex flex-wrap gap-5"><Link href={coursePath} className="text-teal-800 underline">Course guide and materials</Link>{staff&&<Link href={coursePath+"/lecturer"} className="text-teal-800 underline">Lecturer dashboard</Link>}</div><h1 className="text-4xl font-bold">My Cybercrime Law Classroom</h1><p>{member.display_name} · {member.student_number} · Membership: <strong>{member.status}</strong></p>
 <div className="rounded-xl bg-amber-50 p-5">AI assistance is unavailable. Complete the tasks manually; no AI purchase is required.</div>
 <nav aria-label="Assignments" className="grid gap-3 sm:grid-cols-2">{assignments.map(a=>{const w=works?.find(w=>w.assignment===a.id);const r=reviews?.find(r=>r.work_id===w?.id);return <Link aria-current={a.id===assignment.id?"page":undefined} key={a.id} href={roomPath+"?assignment="+a.id} className={`rounded-xl border p-4 ${a.id===assignment.id?"border-teal-700 bg-teal-50":"bg-white"}`}><strong>{a.title}</strong><span className="mt-2 block text-sm">{r?r.decision+" · "+r.score+"/100":w?.submitted?"Awaiting review":w?"Draft saved":"Not started"}</span></Link>;})}</nav>
 <article className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-bold">{assignment.title}</h2><p className="text-sm font-semibold text-teal-800">{assignment.suggested}</p><p className="leading-7">{assignment.case}</p><p className="leading-7"><strong>Deliverable:</strong> {assignment.deliverable}</p><ul className="list-disc space-y-2 pl-5">{assignment.questions.map(question=><li key={question}>{question}</li>)}</ul><Link href={coursePath+"#assessment"} className="inline-block text-teal-800 underline">RPS assessment weights and rubric</Link><p className="text-sm text-slate-600">No submission deadline has been configured. Follow your lecturer&apos;s class instructions.</p></article>
 {member.status==="active"?<Editor key={assignment.id} assignment={assignment.id} initial={latest??null}/>:<p role="status" className="rounded-xl border border-amber-300 p-5">{member.status==="pending"?"Your request is awaiting lecturer approval. You can read all materials while waiting.":"Submission access is suspended. Contact your lecturer; previous work remains readable."}</p>}
 <section><h2 className="text-2xl font-bold">Version history and feedback</h2>{!history.length&&<p className="mt-3">No versions saved for this task.</p>}{history.map(w=>{const review=reviews?.find(r=>r.work_id===w.id);return <details key={w.id} className="mt-4 rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">Version {w.version_number} · {w.submitted?"Submitted":"Draft"} · {new Date(w.created_at).toLocaleString("en-GB",{timeZone:"Asia/Jakarta"})} WIB</summary><h3 className="mt-4 font-bold">Analysis</h3><p className="mt-2 whitespace-pre-wrap break-words">{w.answer||"Empty draft"}</p><h3 className="mt-4 font-bold">Sources</h3><p className="whitespace-pre-wrap break-words">{w.sources}</p><h3 className="mt-4 font-bold">Reflection</h3><p className="whitespace-pre-wrap break-words">{w.reflection}</p>{review?<div className="mt-5 rounded-lg bg-teal-50 p-4"><strong>{review.decision} · {review.score}/100</strong><p className="mt-2 whitespace-pre-wrap break-words">{review.feedback}</p></div>:<p className="mt-4">No lecturer decision on this version.</p>}</details>;})}</section></main>;
}
