import type {Metadata} from 'next';
import {requireTreasurer} from '@/lib/persis/master-server';
import {APPLICATION_STATUS} from '@/lib/persis/application';
import {reviewApplication} from '../../../pendaftaran/actions';
import {Pagination} from '../../DuesList';
import TreasuryNav from '../TreasuryNav';
export const metadata:Metadata={title:'Persetujuan Pendaftaran Anggota Persis',robots:{index:false,follow:false}};
export const dynamic='force-dynamic';
export default async function ApplicationsQueue({searchParams}:{searchParams:Promise<{status?:string;page?:string;error?:string;success?:string}>}){
 const {client}=await requireTreasurer('/persis-kepri/iuran/bendahara/pendaftaran');const p=await searchParams,status=['pending','approved','rejected'].includes(p.status||'')?p.status!:'pending',page=Math.max(1,Number.parseInt(p.page||'1')||1);
 const {data,error,count}=await client.from('persis_member_applications').select('*',{count:'exact'}).eq('status',status).order('created_at',{ascending:false}).order('id',{ascending:false}).range((page-1)*20,page*20);
 return <div lang="id" className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><div className="mx-auto max-w-4xl"><h1 className="text-3xl font-bold">Pendaftaran anggota</h1><p className="mt-3 leading-7 text-slate-600">Periksa data yang diajukan anggota. Persetujuan membuat atau menghubungkan data master dalam satu proses.</p><TreasuryNav/>
 {p.error&&<p role="alert" className="mb-5 rounded-lg bg-red-50 p-4 text-red-800">{p.error}</p>}{p.success&&<p role="status" className="mb-5 rounded-lg bg-emerald-50 p-4 text-emerald-900">Keputusan berhasil disimpan. Pengajuan yang disetujui sudah terhubung dengan master anggota.</p>}
 <form className="mb-6 flex flex-wrap items-end gap-3"><label className="grid gap-2 text-sm font-semibold">Status<select name="status" defaultValue={status} className="rounded-lg border border-slate-300 bg-white p-3 text-base">{Object.entries(APPLICATION_STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><button className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Tampilkan</button></form>
 {error?<p role="alert" className="rounded-lg bg-red-50 p-5 text-red-800">Pendaftaran belum dapat dimuat. Coba muat ulang halaman.</p>:<><p className="mb-4 text-sm text-slate-600">{count||0} pengajuan sesuai filter</p>{!data?.length&&<p className="rounded-xl border border-dashed border-slate-300 p-6">Belum ada pengajuan dengan status ini.</p>}<div className="space-y-4">{(data||[]).slice(0,20).map(a=><article key={a.id} className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">{a.full_name}</h2><p className="mt-2 break-all text-sm text-slate-600">{a.email}</p><p className="mt-2 text-sm">{a.region} · Nomor anggota: {a.member_number||'belum diisi'}</p><p className="mt-2 text-sm text-slate-600">Diajukan {new Intl.DateTimeFormat('id-ID',{dateStyle:'long',timeZone:'Asia/Jakarta'}).format(new Date(a.created_at))}</p>{a.note&&<p className="mt-4 whitespace-pre-wrap break-words rounded-lg bg-slate-50 p-4 leading-7">{a.note}</p>}
 {a.status==='pending'?<form action={reviewApplication} className="mt-5 grid gap-4 border-t border-slate-200 pt-5"><input name="id" type="hidden" value={a.id}/><label className="grid gap-2 text-sm font-semibold">Mulai wajib iuran (opsional)<input name="start_month" type="month" min="2020-01" max="2100-12" className="rounded-lg border border-slate-300 p-3 text-base font-normal"/><span className="text-sm font-normal leading-6 text-slate-600">Kosongkan jika belum ditetapkan. Untuk master yang sudah ada, tanggal dan data resminya dipertahankan.</span></label><label className="grid gap-2 text-sm font-semibold">Catatan pemeriksaan<textarea name="review_note" maxLength={500} rows={2} placeholder="Wajib diisi jika meminta perbaikan" className="rounded-lg border border-slate-300 p-3 text-base font-normal"/></label><div className="flex flex-wrap gap-3"><button name="decision" value="approved" className="rounded-lg bg-emerald-800 px-5 py-3 font-bold text-white">Setujui & masukkan ke master</button><button name="decision" value="rejected" className="rounded-lg border border-red-300 px-5 py-3 font-bold text-red-800">Minta perbaikan</button></div></form>:<><p className="mt-4 font-semibold">{APPLICATION_STATUS[a.status as keyof typeof APPLICATION_STATUS]}</p>{a.review_note&&<p className="mt-2 whitespace-pre-wrap break-words leading-7">Catatan bendahara: {a.review_note}</p>}</>}
 </article>)}</div><Pagination page={page} hasNext={(data?.length||0)>20} base={`/persis-kepri/iuran/bendahara/pendaftaran?status=${status}`}/></>}
 </div></div>;
}
