"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, BookOpen, CheckCircle2, ChevronDown, ChevronUp, Clock, ExternalLink, FileText, Headphones, RotateCcw, Save } from "lucide-react";
import { saveModuleProgress } from "@/lib/learning-progress";

type AnswerMap = Record<number, string>;
const STORAGE_KEY = "rahi-module-7-v1";
const SOURCE_URL = "https://jurnalhukumperatun.mahkamahagung.go.id/index.php/peratun/article/download/144/28";

const nav = [
  ["introduction", "Pengantar"], ["reading", "Bacaan utama"], ["analysis", "Kerangka batas kuasa"],
  ["podcast", "Podcast"], ["reflection", "Refleksi"], ["essay", "Esai"], ["quiz", "Kuis"], ["result", "Hasil"],
];

const readings = [
  { n:"I", title:"Keadilan sebagai ukuran kekuasaan", text:<><p>Dalam pemikiran Raja Ali Haji, kekuasaan tidak cukup dinilai dari kemampuan memerintah atau mempertahankan negeri. Kekuasaan memperoleh kualitas moral ketika digunakan untuk menegakkan hukum, menjaga kemaslahatan, dan melindungi rakyat dari kezaliman.</p><p>Keadilan menjadi ukuran yang berada di atas kehendak pribadi penguasa. Seorang pemimpin dapat memiliki kewenangan formal, tetapi kehilangan dasar moral ketika keputusan dibuat untuk kesenangan diri, kerabat, atau kelompoknya.</p></>, idea:"Kewenangan menjelaskan siapa yang boleh memutuskan; keadilan menguji apakah keputusan itu patut." },
  { n:"II", title:"Hukum adil atas rakyat", text:<><p>Pasal XII <em>Gurindam Dua Belas</em> memuat rumusan terkenal: “Hukum adil atas rakyat, tanda raja beroleh inayat.” Bait ini menghubungkan mutu seorang raja dengan keadilan hukum yang dirasakan rakyat, bukan hanya dengan kebesaran gelar atau luasnya kuasa.</p><p>Hukum yang adil menuntut aturan diketahui, diterapkan secara konsisten, dan tidak dijadikan alat untuk menghukum lawan atau melindungi orang dekat. Rakyat harus dapat mengetahui alasan keputusan dan memperoleh jalan untuk meminta koreksi.</p></>, idea:"Tanda kekuasaan yang baik tampak pada keadilan hukum bagi rakyat." },
  { n:"III", title:"Hawa nafsu sebagai batas dari dalam", text:<><p><em>Tsamarat al-Muhimmah</em> memberi perhatian pada sifat yang menghalangi keadilan: takabur, pemarah, dengki, tamak, bakhil, lalai, berlebihan, dusta, tergesa-gesa, dan malas. Daftar ini memperlihatkan bahwa kerusakan lembaga dapat bermula dari kegagalan mengendalikan diri.</p><p>Pemimpin yang marah dapat menghukum sebelum memeriksa. Pemimpin yang tamak dapat mengubah anggaran menjadi keuntungan pribadi. Pemimpin yang takabur dapat menolak nasihat. Karena itu, pengendalian moral harus disertai aturan, pencatatan, dan pengawasan.</p></>, idea:"Batas pertama kekuasaan adalah kemampuan pemegangnya mengendalikan dirinya." },
  { n:"IV", title:"Mahkamah, bukti, dan ketidakberpihakan", text:<><p>Keadilan harus hadir dalam lembaga dan prosedur. Pengambil keputusan perlu mendengar para pihak, memeriksa bukti yang relevan, menghindari konflik kepentingan, dan menjelaskan hubungan antara fakta, aturan, serta kesimpulan.</p><p>Ketidakberpihakan bukan berarti hakim atau pejabat tidak memiliki nilai. Ia berarti perkara tidak diputus berdasarkan hubungan pribadi atau tekanan. Ketika terdapat kepentingan pribadi, pejabat harus menyatakannya dan tidak ikut memutuskan apabila independensinya terganggu.</p></>, idea:"Watak adil menjadi nyata melalui proses yang dapat diperiksa." },
  { n:"V", title:"Larangan kesewenang-wenangan", text:<><p>Wewenang memiliki tujuan dan batas. Keputusan menjadi sewenang-wenang ketika dibuat tanpa dasar, untuk tujuan yang menyimpang, dengan faktor yang tidak relevan, atau melalui tindakan yang berlebihan dibandingkan kebutuhan.</p><p>Keadilan mengharuskan tindakan proporsional. Kesalahan kecil tidak semestinya memperoleh hukuman yang menghancurkan masa depan seseorang. Sebaliknya, pelanggaran berat tidak boleh diabaikan karena pelakunya dekat dengan pemimpin.</p></>, idea:"Kuasa yang sah tetap dapat digunakan secara tidak adil ketika tujuan, alasan, atau ukurannya menyimpang." },
  { n:"VI", title:"Alasan, pengawasan, dan hak untuk mengoreksi", text:<><p>Keputusan yang memengaruhi hak atau kepentingan orang lain harus dapat dijelaskan. Alasan memungkinkan rakyat memahami dasar keputusan, membedakan hukum dari selera pribadi, serta menilai apakah bukti dan aturan digunakan secara konsisten.</p><p>Namun alasan saja tidak cukup. Diperlukan pengawasan, pengaduan, peninjauan, atau banding sesuai jenis lembaga. Kesediaan mengoreksi kesalahan bukan tanda kehilangan wibawa; ia menunjukkan bahwa hukum dan keadilan lebih tinggi daripada gengsi pejabat.</p></>, idea:"Tidak ada kekuasaan yang sehat tanpa kemungkinan pemeriksaan dan koreksi." },
  { n:"VII", title:"Menerjemahkan batas moral ke lembaga modern", text:<><p>Bahasa moral Raja Ali Haji dapat dikembangkan dalam tata kelola modern melalui asas legalitas, hak asasi, pemisahan atau pembagian kewenangan, transparansi, konflik kepentingan, peradilan yang independen, pengawasan, dan pemulihan bagi pihak yang dirugikan.</p><p>Kita tidak menyamakan kerajaan Riau–Lingga dengan negara konstitusional masa kini. Kita mempertemukan pertanyaan etiknya dengan perangkat kelembagaan modern: siapa berwenang, apa batasnya, siapa terdampak, apa alasannya, siapa mengawasi, dan bagaimana kesalahan dipulihkan.</p></>, idea:"Moralitas memberi arah; institusi membuat batas kekuasaan dapat dijalankan dan diuji." },
];

const questions = [
  { q:"Dalam Modul 7, keadilan berfungsi sebagai…", o:["Hiasan pidato","Ukuran moral penggunaan kekuasaan","Hak istimewa pejabat","Pengganti seluruh aturan"], a:1 },
  { q:"Bait Pasal XII yang menjadi poros modul adalah…", o:["Hukum adil atas rakyat, tanda raja beroleh inayat","Barang siapa mengenal diri","Jika hendak mengenal orang berbangsa","Cahari olehmu akan sahabat"], a:0 },
  { q:"Hukum yang adil menuntut…", o:["Aturan rahasia","Penerapan konsisten dan alasan yang dapat diperiksa","Perlindungan orang dekat","Hukuman berdasarkan kemarahan"], a:1 },
  { q:"Salah satu sifat penghalang keadilan ialah…", o:["Menerima koreksi","Takabur dan tamak","Memeriksa bukti","Menjelaskan alasan"], a:1 },
  { q:"Ketidakberpihakan berarti…", o:["Tidak memiliki nilai apa pun","Tidak memutus berdasarkan hubungan pribadi atau tekanan","Selalu setuju kepada mayoritas","Mengabaikan semua pihak"], a:1 },
  { q:"Keputusan dapat disebut sewenang-wenang ketika…", o:["Memiliki alasan dan tujuan sah","Dibuat tanpa dasar atau untuk tujuan yang menyimpang","Dapat ditinjau","Buktinya diperiksa"], a:1 },
  { q:"Prinsip proporsionalitas meminta agar…", o:["Semua kesalahan dihukum sama","Tindakan tidak berlebihan dibandingkan kebutuhan","Pejabat bebas memilih hukuman","Hukuman selalu maksimal"], a:1 },
  { q:"Mengapa alasan keputusan penting?", o:["Agar dokumen lebih panjang","Agar hubungan fakta, aturan, dan kesimpulan dapat diperiksa","Agar kritik dilarang","Agar keputusan tidak dapat diubah"], a:1 },
  { q:"Koreksi terhadap keputusan menunjukkan…", o:["Lembaga selalu lemah","Keadilan lebih tinggi daripada gengsi pejabat","Pejabat kehilangan semua kewenangan","Aturan tidak diperlukan"], a:1 },
  { q:"Cara tepat membawa gagasan Raja Ali Haji ke masa kini adalah…", o:["Menyalin kerajaan secara harfiah","Menghubungkan arah moral dengan batas kelembagaan modern","Menghapus konteks sejarah","Mengandalkan moral pribadi saja"], a:1 },
];

export default function ModuleSevenLearning() {
  const [active, setActive] = useState("introduction");
  const [reflection, setReflection] = useState("");
  const [essay, setEssay] = useState("");
  const [answers, setAnswers] = useState<AnswerMap>({});
  const [score, setScore] = useState<number | null>(null);
  const [readingDone, setReadingDone] = useState(false);
  const [analysisDone, setAnalysisDone] = useState(false);
  const [podcastDone, setPodcastDone] = useState(false);
  const [hydrated, setHydrated] = useState(false);
  const [saved, setSaved] = useState(false);

  useEffect(() => { try { const raw = localStorage.getItem(STORAGE_KEY); if (raw) { const d = JSON.parse(raw); setReflection(d.reflection ?? ""); setEssay(d.essay ?? ""); setAnswers(d.answers ?? {}); setScore(d.score ?? null); setReadingDone(Boolean(d.readingDone)); setAnalysisDone(Boolean(d.analysisDone)); setPodcastDone(Boolean(d.podcastDone)); } } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; const id = window.setTimeout(() => { void saveModuleProgress(STORAGE_KEY, 7, { reflection, essay, answers, score, readingDone, analysisDone, podcastDone }).then(() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200); }); }, 500); return () => window.clearTimeout(id); }, [reflection, essay, answers, score, readingDone, analysisDone, podcastDone, hydrated]);

  const reflectionWords = useMemo(() => countWords(reflection), [reflection]);
  const essayWords = useMemo(() => countWords(essay), [essay]);
  const reflectionDone = reflectionWords >= 100;
  const essayDone = essayWords >= 500;
  const quizDone = score !== null && score >= 70;
  const done = [readingDone, analysisDone, podcastDone, reflectionDone, essayDone, quizDone];
  const progress = Math.round(done.filter(Boolean).length / 6 * 100);
  const complete = done.every(Boolean);

  function submit() { if (Object.keys(answers).length < questions.length) { alert("Jawab seluruh pertanyaan terlebih dahulu."); return; } setScore(questions.filter((q, i) => Number(answers[i]) === q.a).length * 10); setActive("result"); window.scrollTo({ top: 0, behavior: "smooth" }); }

  return <main className="min-h-screen bg-[#f7f4ee] text-slate-950">
    <header className="border-b border-white/10 bg-[#070916] px-5 py-5 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5"><Link href="/raja-ali-haji/programmes/pemikiran-raja-ali-haji" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-300 hover:text-amber-400"><ArrowLeft size={17}/> Kembali ke program</Link><div className="min-w-56"><div className="flex justify-between text-xs"><span>Progres Modul 7</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-400 transition-all" style={{ width: `${progress}%` }}/></div></div></div></header>
    <section className="bg-[#070916] px-5 pb-14 pt-10 text-white sm:px-8 md:pb-20"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Modul 7 dari 8</p><h1 className="mt-4 max-w-5xl text-4xl font-black tracking-tight sm:text-5xl md:text-6xl">Keadilan dan Batas Moral Kekuasaan</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Membaca Gurindam Dua Belas dan Tsamarat al-Muhimmah tentang hukum yang adil, mahkamah, pengendalian diri, dan pembatasan kekuasaan.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-slate-400"><span className="inline-flex items-center gap-2"><Clock size={17}/> 120–150 menit</span><span className="inline-flex items-center gap-2"><BookOpen size={17}/> Tingkat dasar</span><span className="inline-flex items-center gap-2"><FileText size={17}/> Refleksi, esai, dan kuis</span></div></div></section>
    <div className="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:px-8 lg:grid-cols-[250px_1fr] lg:py-14"><aside className="h-fit border border-stone-300 bg-white p-3 lg:sticky lg:top-24">{nav.map(([id, label], i) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center gap-3 px-4 py-3 text-left text-sm font-semibold ${active === id ? "bg-slate-950 text-white" : "hover:bg-stone-100"}`}><span className="text-xs text-amber-600">{String(i + 1).padStart(2, "0")}</span>{label}</button>)}<div className="mt-3 border-t border-stone-200 px-4 py-3 text-xs text-slate-500">{saved ? "Tersimpan otomatis ✓" : "Progres tersimpan di perangkat ini"}</div></aside>
      <div className="min-w-0">
        {active === "introduction" && <Panel eyebrow="Mulai di sini" title="Pengantar Modul 7"><p>Modul 7 mempertemukan bait politik Pasal XII <em>Gurindam Dua Belas</em> dengan pembahasan keadilan dan mahkamah dalam <em>Tsamarat al-Muhimmah</em>. Fokusnya bukan hanya bagaimana kuasa diperoleh, tetapi bagaimana kuasa dibatasi agar tidak berubah menjadi kezaliman.</p><h3>Tujuan pembelajaran</h3><ol><li>Menjelaskan keadilan sebagai ukuran moral dan legitimasi penggunaan kekuasaan.</li><li>Menganalisis hubungan pengendalian diri, hukum, mahkamah, dan ketidakberpihakan.</li><li>Mengenali keputusan sewenang-wenang, konflik kepentingan, dan tindakan yang tidak proporsional.</li><li>Menerjemahkan batas moral kekuasaan ke dalam pengawasan dan koreksi kelembagaan modern.</li></ol><blockquote>Jika sebuah tindakan dilakukan oleh pejabat yang berwenang, tetapi tanpa alasan yang adil dan tanpa jalan koreksi, apakah tindakan itu tetap sah secara moral?</blockquote><Next onClick={() => setActive("reading")}>Mulai membaca</Next></Panel>}
        {active === "reading" && <Panel eyebrow="Bacaan utama • 35–45 menit" title="Ketika hukum menjadi batas kekuasaan"><p>Tujuh bagian bacaan berikut menyatukan bahasa etika dan hukum Raja Ali Haji. Konteks kerajaan tetap dibedakan dari negara modern; yang dikembangkan adalah tuntutan keadilan, ketidakberpihakan, alasan, pengawasan, dan koreksi.</p><ReadingAccordion/><div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 p-5"><p className="font-bold">Baca kajian pendukung</p><p className="mt-2 text-sm leading-6 text-slate-600">Kajian hukum administrasi menghubungkan karya politik Raja Ali Haji dengan asas keadilan, ketidakberpihakan, profesionalitas, akuntabilitas, kepastian hukum, kepentingan umum, dan larangan mencampuradukkan kewenangan.</p><a href={SOURCE_URL} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 font-bold text-amber-700 hover:text-amber-900">Buka artikel Jurnal Hukum Peratun <ExternalLink size={17}/></a></div><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={readingDone} onChange={e => setReadingDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mempelajari seluruh bacaan Modul 7.</label><Next onClick={() => setActive("analysis")}>Lanjut ke kerangka batas kuasa</Next></Panel>}
        {active === "analysis" && <Panel eyebrow="Analisis konseptual" title="Tiga lapis pembatas kekuasaan"><div className="grid gap-4 md:grid-cols-3"><Concept n="01" title="Diri" text="Pengendalian hawa nafsu mencegah kuasa tunduk kepada marah, tamak, dan takabur."/><Concept n="02" title="Hukum" text="Wewenang, bukti, prosedur, ketidakberpihakan, dan proporsionalitas membatasi keputusan."/><Concept n="03" title="Koreksi" text="Alasan, pengawasan, pengaduan, peninjauan, dan pemulihan membuat kuasa dapat diuji."/></div><h3>Batas dari dalam</h3><p>Karakter pemegang jabatan menentukan bagaimana kewenangan digunakan. Namun keutamaan pribadi tidak boleh menjadi satu-satunya perlindungan terhadap penyalahgunaan.</p><h3>Batas melalui hukum</h3><p>Aturan menentukan kewenangan dan tujuan. Prosedur memastikan pihak didengar, bukti diperiksa, konflik kepentingan dikelola, dan tindakan tidak berlebihan.</p><h3>Batas melalui koreksi</h3><p>Keputusan harus mempunyai alasan dan dapat diperiksa. Pengaduan, pengawasan, peninjauan, dan pemulihan mencegah pejabat menjadi hakim terakhir atas tindakannya sendiri.</p><label className="mt-8 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={analysisDone} onChange={e => setAnalysisDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya memahami hubungan pengendalian diri, batas hukum, pengawasan, dan koreksi.</label><Next onClick={() => setActive("podcast")}>Lanjut ke podcast</Next></Panel>}
        {active === "podcast" && <Panel eyebrow="Podcast • 25 menit" title="Ketika Kekuasaan Harus Berhenti"><div className="rounded-2xl bg-slate-950 p-7 text-white"><div className="flex items-center gap-4"><div className="rounded-full bg-amber-400 p-4 text-slate-950"><Headphones size={28}/></div><div><p className="font-bold">Raja Ali Haji: Penawar Penyakit Digital</p><p className="mt-1 text-sm text-slate-400">Audio Overview • Bahasa Indonesia • 25:09</p></div></div><audio className="mt-7 w-full" controls preload="metadata" onEnded={() => setPodcastDone(true)}><source src="/audio/raja-ali-haji-penawar-penyakit-digital.m4a" type="audio/mp4"/>Peramban Anda tidak mendukung pemutar audio.</audio></div><details className="mt-7 border border-stone-300 bg-white p-5"><summary className="cursor-pointer font-bold">Baca ringkasan podcast</summary><div className="mt-4 space-y-4 leading-8 text-slate-600"><p>Podcast membahas keadilan sebagai batas moral kekuasaan: hukum yang adil atas rakyat, sifat batin yang mengganggu keputusan, mahkamah yang tidak memihak, dan larangan kesewenang-wenangan.</p><p>Gagasan Raja Ali Haji kemudian dibawa ke kehidupan digital: bagaimana bahasa, informasi, reputasi, dan kewenangan harus dikelola dengan tanggung jawab, alasan yang dapat diuji, serta mekanisme koreksi.</p><p>Dalam konteks modern, prinsip tersebut diterjemahkan melalui legalitas, proporsionalitas, pengawasan, peninjauan, dan pemulihan bagi pihak yang dirugikan.</p></div></details><label className="mt-7 flex cursor-pointer items-center gap-3 border border-amber-300 bg-amber-50 p-5 font-semibold"><input type="checkbox" checked={podcastDone} onChange={e => setPodcastDone(e.target.checked)} className="h-5 w-5 accent-amber-700"/> Saya telah mendengarkan podcast ini sampai selesai.</label><Next onClick={() => setActive("reflection")} disabled={!podcastDone}>Lanjut ke refleksi</Next></Panel>}
        {active === "reflection" && <Panel eyebrow="Aktivitas wajib • 100–150 kata" title="Refleksi tentang batas kekuasaan"><p>Pilih satu tindakan pejabat atau pimpinan yang Anda ketahui. Jelaskan sumber kewenangannya, batas moral atau hukumnya, pihak yang terdampak, alasan yang diperlukan, dan bentuk koreksi jika tindakannya keliru.</p><textarea value={reflection} onChange={e => setReflection(e.target.value)} rows={10} placeholder="Tuliskan refleksi Anda…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={reflectionWords} min={100} max={150}/><Next disabled={!reflectionDone} onClick={() => setActive("essay")}>Simpan dan lanjut ke esai</Next></Panel>}
        {active === "essay" && <Panel eyebrow="Penilaian • 500–700 kata" title="Tugas esai Modul 7"><blockquote>Jelaskan bagaimana gagasan keadilan dalam <em>Gurindam Dua Belas</em> dan <em>Tsamarat al-Muhimmah</em> dapat dikembangkan menjadi kerangka pembatasan kekuasaan masa kini.</blockquote><h3>Ketentuan</h3><ul><li>Gunakan sedikitnya tiga bagian bacaan Modul 7.</li><li>Bahas hukum yang adil, pengendalian hawa nafsu, dan ketidakberpihakan.</li><li>Jelaskan hubungan kewenangan, tujuan, alasan, proporsionalitas, pengawasan, dan koreksi.</li><li>Gunakan satu contoh tindakan pejabat, sekolah, kampus, organisasi, atau pelayanan publik.</li></ul><textarea value={essay} onChange={e => setEssay(e.target.value)} rows={22} placeholder="Mulai menulis esai…" className="mt-6 w-full border border-stone-300 bg-white p-5 leading-7 outline-none focus:border-amber-700"/><Words count={essayWords} min={500} max={700}/><Next disabled={!essayDone} onClick={() => setActive("quiz")}>Simpan dan mulai kuis</Next></Panel>}
        {active === "quiz" && <Panel eyebrow="10 pertanyaan • Nilai minimum 70" title="Kuis Modul 7"><div className="space-y-8">{questions.map((q, i) => <fieldset key={q.q} className="border border-stone-300 bg-white p-6"><legend className="px-2 font-bold">{i + 1}. {q.q}</legend><div className="mt-4 grid gap-3">{q.o.map((o, j) => <label key={o} className={`flex cursor-pointer gap-3 border p-4 ${Number(answers[i]) === j ? "border-amber-600 bg-amber-50" : "border-stone-200 hover:bg-stone-50"}`}><input type="radio" name={`q7-${i}`} checked={Number(answers[i]) === j} value={j} onChange={e => setAnswers({ ...answers, [i]: e.target.value })} className="mt-1 accent-amber-700"/><span>{o}</span></label>)}</div></fieldset>)}</div><button onClick={submit} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700"><CheckCircle2 size={18}/> Kirim jawaban</button></Panel>}
        {active === "result" && <Panel eyebrow="Ringkasan kemajuan" title="Hasil Modul 7"><div className={`border p-7 ${complete ? "border-emerald-300 bg-emerald-50" : "border-amber-300 bg-amber-50"}`}><p className="text-5xl font-black">{score ?? 0}</p><p className="mt-2 font-bold">Nilai kuis</p><p className="mt-3 text-slate-600">{quizDone ? "Kuis lulus." : "Nilai belum mencapai 70. Pelajari kembali materi lalu ulangi kuis."}</p></div><div className="mt-7 space-y-3"><Req done={readingDone} text="Bacaan utama selesai"/><Req done={analysisDone} text="Kerangka batas kuasa selesai"/><Req done={podcastDone} text="Podcast/ringkasan selesai"/><Req done={reflectionDone} text={`Refleksi minimal 100 kata (${reflectionWords} kata)`}/><Req done={essayDone} text={`Esai minimal 500 kata (${essayWords} kata)`}/><Req done={quizDone} text="Nilai kuis minimal 70"/></div>{complete ? <div className="mt-8 rounded-2xl bg-emerald-700 p-7 text-white"><CheckCircle2 size={34}/><h3 className="mt-4 text-2xl font-black">Modul 7 selesai</h3><p className="mt-2 text-emerald-100">Anda telah menyelesaikan pembelajaran keadilan, pengendalian diri, hukum, mahkamah, alasan keputusan, pengawasan, dan koreksi sebagai batas moral kekuasaan.</p></div> : <button onClick={() => { setAnswers({}); setScore(null); setActive("quiz"); }} className="mt-8 inline-flex items-center gap-2 rounded-xl border border-slate-950 px-6 py-4 font-bold hover:bg-white"><RotateCcw size={18}/> Ulangi kuis</button>}</Panel>}
      </div>
    </div>
  </main>;
}

function Panel({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="border border-stone-300 bg-[#fffdf9] p-6 shadow-sm sm:p-9 md:p-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-700">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight md:text-4xl">{title}</h2><div className="mt-8 space-y-5 leading-8 [&_h3]:pt-4 [&_h3]:text-xl [&_h3]:font-black [&_ol]:list-decimal [&_ol]:pl-6 [&_ul]:list-disc [&_ul]:pl-6 [&_blockquote]:border-l-4 [&_blockquote]:border-amber-600 [&_blockquote]:bg-amber-50 [&_blockquote]:p-5 [&_blockquote]:text-lg [&_blockquote]:italic">{children}</div></section>; }
function Next({ children, onClick, disabled = false }: { children: React.ReactNode; onClick: () => void; disabled?: boolean }) { return <button onClick={onClick} disabled={disabled} className="mt-8 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-6 py-4 font-bold text-white hover:bg-amber-700 disabled:cursor-not-allowed disabled:bg-slate-300"><Save size={18}/>{children}</button>; }
function Words({ count, min, max }: { count: number; min: number; max: number }) { return <p className={`text-sm font-semibold ${count >= min ? "text-emerald-700" : "text-slate-500"}`}>{count} kata • ketentuan {min}–{max} kata {count >= min ? "✓" : ""}</p>; }
function Req({ done, text }: { done: boolean; text: string }) { return <div className="flex items-center gap-3 border border-stone-200 bg-white p-4"><CheckCircle2 className={done ? "text-emerald-600" : "text-stone-300"} size={21}/><span className={done ? "font-semibold" : "text-slate-500"}>{text}</span></div>; }
function Concept({ n, title, text }: { n: string; title: string; text: string }) { return <article className="border border-stone-300 bg-white p-5"><p className="text-xs font-bold text-amber-700">{n}</p><h3 className="pt-2">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{text}</p></article>; }
function countWords(value: string) { return value.trim() ? value.trim().split(/\s+/).length : 0; }
function ReadingAccordion() { const [open, setOpen] = useState<number | null>(0); return <div className="divide-y divide-stone-300 border-y border-stone-300">{readings.map((section, i) => <article key={section.n}><button onClick={() => setOpen(open === i ? null : i)} className="flex w-full items-center justify-between gap-5 py-5 text-left"><span><small className="mr-3 font-bold text-amber-700">BAGIAN {section.n}</small><strong>{section.title}</strong></span>{open === i ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>{open === i && <div className="pb-7"><div className="space-y-4 border-l-4 border-amber-600 bg-amber-50 p-6 leading-8">{section.text}</div><div className="mt-5 rounded-lg border border-stone-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">Gagasan kunci</p><p className="mt-2 text-slate-700">{section.idea}</p></div></div>}</article>)}</div>; }
