import Link from "next/link";
import { Award, BarChart3, CheckCircle2, Download, MessageSquareText, Users } from "lucide-react";
import { requireRahiAdmin } from "../../admin";
import { loadPilotData } from "@/lib/rahi/pilot-data";
import { reportSummary } from "@/lib/rahi/report-summary";

export default async function PilotReportPage(){
  const {admin}=await requireRahiAdmin("/raja-ali-haji/admin/pilot-01/report");const data=await loadPilotData(admin);const s=reportSummary(data);const completionRate=s.participants?Math.round(s.completed/s.participants*100):0;const responseRate=s.participants?Math.round(s.evaluation/s.participants*100):0;
  return <main className="min-h-screen bg-[#eef1f4] px-5 py-12 text-slate-950 sm:px-8"><div className="mx-auto max-w-7xl">
    <div className="flex flex-wrap items-end justify-between gap-6"><div><Link href="/raja-ali-haji/admin/pilot-01" className="font-bold text-amber-800">← Dashboard cohort</Link><p className="mt-8 text-xs font-bold uppercase tracking-[.25em] text-amber-700">Executive dashboard · Restricted</p><h1 className="mt-3 text-4xl font-black sm:text-6xl">Laporan Akhir Pilot</h1><p className="mt-3 text-slate-600">Pilot Cohort 1 · 5 Oktober-1 November 2026</p></div><div className="flex flex-wrap gap-3"><Link href="/raja-ali-haji/admin/pilot-01/report/history" className="rounded-xl border border-slate-950 px-5 py-4 font-black">Arsip Laporan</Link><Link href="/raja-ali-haji/admin/pilot-01/report/pdf" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-4 font-black text-white"><Download size={19}/> Unduh Executive PDF</Link></div></div>
    <section className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi icon={Users} label="Peserta" value={s.participants}/><Kpi icon={CheckCircle2} label="Penyelesaian 8 modul" value={`${s.completed} · ${completionRate}%`}/><Kpi icon={Award} label="Layak sertifikat" value={s.eligible}/><Kpi icon={BarChart3} label="Perubahan rata-rata" value={s.averageChange===null?"—":`${s.averageChange.toFixed(1)} poin`}/></section>
    <section className="mt-8 grid gap-7 lg:grid-cols-2"><article className="rounded-2xl bg-white p-7 shadow-sm"><h2 className="text-2xl font-black">Pengukuran hasil</h2><div className="mt-6 space-y-5"><Metric label="Baseline" value={s.baseline} max={s.participants}/><Metric label="Endline" value={s.endline} max={s.participants}/><Metric label="Evaluasi program" value={s.evaluation} max={s.participants}/><Metric label="Sertifikat diterbitkan" value={s.certificates} max={s.participants}/></div><p className="mt-6 text-sm text-slate-500">Response rate evaluasi: {responseRate}%</p></article>
      <article className="rounded-2xl bg-[#111526] p-7 text-white"><MessageSquareText className="text-amber-400"/><h2 className="mt-4 text-2xl font-black">Pendampingan dan komunikasi</h2><div className="mt-7 grid grid-cols-2 gap-4"><Box label="Check-in masuk" value={s.checkins}/><Box label="Pesan terkirim" value={s.messagesSent}/><Box label="Intervensi" value={s.interventions}/><Box label="Selesai ditangani" value={s.resolved}/></div></article></section>
    <section className="mt-8 grid gap-7 lg:grid-cols-[.8fr_1.2fr]"><article className="rounded-2xl bg-amber-100 p-7"><h2 className="text-2xl font-black">Komposisi peserta</h2><p className="mt-5 text-lg capitalize leading-8">{s.categorySummary||"Belum ada data peserta."}</p></article><article className="rounded-2xl border border-stone-300 bg-white p-7"><h2 className="text-2xl font-black">Rekomendasi pascapilot</h2><ol className="mt-5 list-decimal space-y-3 pl-5 leading-7 text-slate-700"><li>Tindak lanjuti peserta yang belum menyelesaikan modul melalui periode remedial terukur.</li><li>Gunakan perubahan baseline-endline dan evaluasi untuk menyempurnakan materi serta pendampingan.</li><li>Terbitkan sertifikat hanya bagi peserta yang lolos validasi 8 modul dan 8 kuis.</li><li>Dokumentasikan temuan pilot sebagai evidence untuk Cohort 2 dan proposal kolaborasi.</li></ol></article></section>
  </div></main>;
}
function Kpi({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string|number}){return <article className="rounded-2xl bg-white p-6 shadow-sm"><Icon size={22} className="text-amber-700"/><p className="mt-5 text-sm font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>}
function Metric({label,value,max}:{label:string;value:number;max:number}){const width=max?Math.min(100,value/max*100):0;return <div><div className="flex justify-between font-bold"><span>{label}</span><span>{value}/{max}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-stone-200"><div className="h-full bg-emerald-700" style={{width:`${width}%`}}/></div></div>}
function Box({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-white/[.08] p-5"><p className="text-3xl font-black text-amber-300">{value}</p><p className="mt-2 text-sm text-slate-300">{label}</p></div>}
