-- LexNusa CRM v1.2 reconstructed baseline for local reproducibility.
-- Reconstructed from current application dependencies only; contains no Production data.

create extension if not exists pgcrypto;

create table if not exists public.lexnusa_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.lexnusa_pilot_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  name text not null check (char_length(name) between 1 and 120),
  organization text,
  email text not null check (char_length(email) <= 254),
  project_type text not null,
  message text not null check (char_length(message) between 1 and 6000),
  source text not null default 'lexnusa-landing',
  status text not null default 'new' check (status in ('new','contacted','qualified','won','lost','spam')),
  notes text check (notes is null or char_length(notes) <= 4000),
  notification_status text not null default 'pending',
  notification_provider_id text,
  notified_at timestamptz,
  consent_at timestamptz,
  consent_version text,
  follow_up_at timestamptz,
  estimated_value numeric(16,2) check (estimated_value is null or estimated_value >= 0),
  currency text not null default 'USD' check (currency in ('USD','IDR','SGD','MYR')),
  owner_user_id uuid references public.lexnusa_admins(user_id) on delete set null
);

create table if not exists public.lexnusa_lead_activities (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  lead_id bigint not null references public.lexnusa_pilot_leads(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  activity_type text not null,
  summary text not null check (char_length(summary) between 1 and 1000),
  details jsonb not null default '{}'::jsonb,
  constraint lexnusa_lead_activities_activity_type_check check (activity_type in (
    'created','status_changed','note_updated','follow_up_changed','value_changed','owner_changed',
    'email_opened','email_prepared','email_sent','email_sent_manual','email_failed','manual_note'
  ))
);

create table if not exists public.lexnusa_rate_limits (
  rate_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0 check (request_count >= 0)
);

create index if not exists lexnusa_pilot_leads_created_at_idx on public.lexnusa_pilot_leads(created_at desc);
create index if not exists lexnusa_pilot_leads_status_idx on public.lexnusa_pilot_leads(status);
create index if not exists lexnusa_pilot_leads_follow_up_at_idx on public.lexnusa_pilot_leads(follow_up_at);
create index if not exists lexnusa_pilot_leads_owner_user_id_idx on public.lexnusa_pilot_leads(owner_user_id);
create index if not exists lexnusa_lead_activities_lead_created_idx on public.lexnusa_lead_activities(lead_id, created_at desc);

alter table public.lexnusa_admins enable row level security;
alter table public.lexnusa_pilot_leads enable row level security;
alter table public.lexnusa_lead_activities enable row level security;
alter table public.lexnusa_rate_limits enable row level security;

revoke all on table public.lexnusa_admins, public.lexnusa_pilot_leads, public.lexnusa_lead_activities, public.lexnusa_rate_limits from anon, authenticated;
grant select, insert, update, delete on table public.lexnusa_admins, public.lexnusa_pilot_leads, public.lexnusa_lead_activities, public.lexnusa_rate_limits to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.lexnusa_check_rate_limit(p_key text, p_limit integer, p_window_seconds integer)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  current_row public.lexnusa_rate_limits%rowtype;
  now_ts timestamptz := now();
begin
  if p_key is null or p_key = '' or p_limit < 1 or p_window_seconds < 1 then
    return false;
  end if;

  insert into public.lexnusa_rate_limits(rate_key, window_started_at, request_count)
  values (p_key, now_ts, 1)
  on conflict (rate_key) do nothing;

  select * into current_row
  from public.lexnusa_rate_limits
  where rate_key = p_key
  for update;

  if current_row.window_started_at <= now_ts - make_interval(secs => p_window_seconds) then
    update public.lexnusa_rate_limits
      set window_started_at = now_ts, request_count = 1
      where rate_key = p_key;
    return true;
  end if;

  if current_row.request_count >= p_limit then
    return false;
  end if;

  update public.lexnusa_rate_limits
    set request_count = request_count + 1
    where rate_key = p_key;
  return true;
end;
$$;

revoke all on function public.lexnusa_check_rate_limit(text, integer, integer) from public, anon, authenticated;
grant execute on function public.lexnusa_check_rate_limit(text, integer, integer) to service_role;
